### ISSUE TITLE
feat[dev]: ✨ implement new brandshape variants

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#1004]
## Description
This tasks describes the Figma implementation for: #792 

## DoR
- [x] Item has been estimated by the team
- [x] Item dependencies have been identified and documented

## DoD
- [x] Documentation has been created/updated (if applicable)
- [x] Migration Guide has been created/updated (if applicable)
- [x] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [x] Relevant stories (Features, A11y) are created/updated
- [x] Implementation works successfully on `feature` branch

**Comment by karlbaumhauer** [comment]
@abudd1094 we just changed our ticket process. This is now the implementation subtask for the original main ticket #792

**Comment by abudd1094** [comment]
This is my last day at Union for now so I wasn't able to pick this up, I suspect the topic will return soon.  Thanks for keeping me in the loop and all the best

**Comment by karlbaumhauer** [comment]
ah... sad to hear but thx for updating me. 

I will remove you as asignee and see when we will be ready to pick this up. 

all the best to you as well and thx again for your great support.

**Comment by yoezlem** [comment]
Branch: https://github.com/solid-design-system/solid/tree/feat/extend-sd-brandshape-variants
