### ISSUE TITLE
feat[design]: ✨ implement sd-flipcard component

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1011]
## Description
This tasks describes the Figma implementation for: #299

### Open Questions towards development
- [ ] Question1
- [ ] Question2

## DoR
- [x] Item has been estimated by the team
- [x] Item dependencies have been identified and documented

## DoD
- [x] Brand approval (if neccessary)
- [x] Figma documentation file incl. hand-off has been created/updated (if applicable)
- [x] Tokens have been applied/updated (if applicable)
- [ ] Crosslinks are created/updated
- [x] Implementation works successfully on `figma` branch

**Comment by coraliefeil** [comment]
Can this issue be closed? Is there only the publishing subtasks still open? Or do we still need to refactor the design comp?

**Comment by yoezlem** [comment]
I wasn't sure if you need this task. If you don't need it, feel free to close it! :)
