### ISSUE TITLE
feat[design]: ✨ publish sd-flipcard component

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1013]
## Description
This tasks describes the Figma release for: #299 

Current Figma version: V.0.0.1
New Figma version: V.1.0.0
Figma Branch: [sd-flipcard](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/7fdazJGMgMwbFwriO1Wfs4/Solid-DS-–-Component-Library?type=design&node-id=21989-3247&mode=design&t=2XUjpowB2JwKuFH0-11)

### Open Questions towards development
- [ ] Question1
- [ ] Question2

## DoR
- [ ] Item has been estimated by the team
- [ ] Item dependencies have been identified and documented

## DoD
- [ ] Figma documentation file incl. hand-off has been created/updated (if applicable)
- [ ] Crosslinks are created/updated
- [ ] Release Notes have been updated

**Comment by van-nguyen-ht** [comment]
@yoezlem I've added the info to the description, I have a question regarding the ticket itself, does this mean I publish on design side now? I have no question for development here.

**Comment by yoezlem** [comment]
@van-nguyen-ht please publish the figma style after the implementation of dev.
We done this, because of all the design Tickets which was done but couldn't close because of not publishing it before dev implementation. Therefore we now have for all Feature an extra Subtask for publishing it.

**Comment by van-nguyen-ht** [comment]
@yoezlem ok so when you publish you'll write me and then I'll publish. Copied.

**Comment by yoezlem** [comment]
@coraliefeil you can merge the design component now! :)

**Comment by coraliefeil** [comment]
Done
