### ISSUE TITLE
feat[design]: ✨ implement sd-quickfact component

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1014]
## Description
This tasks describes the Figma implementation for: #305 

### Open Questions towards development
- [ ] Question1
- [ ] Question2

## DoR
- [x] Item has been estimated by the team
- [x] Item dependencies have been identified and documented

## DoD
- [x] Brand approval (if neccessary)
- [x] Figma documentation file incl. hand-off has been created/updated (if applicable)
- [x] Tokens have been applied/updated (if applicable)
- [ ] Crosslinks are created/updated
- [x] Implementation works successfully on `figma` branch

**Comment by coraliefeil** [comment]
Can this issue be closed? Is there only the publishing subtasks still open? Or do we still need to refactor the design comp?

**Comment by yoezlem** [comment]
Wasn't sure about this. If you don't need it, feel free to close it!

**Comment by van-nguyen-ht** [comment]
@yoezlem 
here's the [refactored design component ](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/eJJKt0CGHUpkx6RKK7dJOG/Solid-DS-–-Component-Library?type=design&node-id=2206-18617&mode=design&t=KrQkgIgm2K25UMWg-11)
I will close this issue with this comment.
