### ISSUE TITLE
feat[design]: ✨ implement sd-audio component

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1017]
## Description
This tasks describes the Figma implementation for: #270

[Figma branch](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/cHffrwo9yDeKpqsPcYN8R7/Solid-DS-–-Component-Library?type=design&node-id=3112-20014&mode=design&t=kxA7YwK2lEX3onY1-11)

### Open Questions towards development
- [ ] Question1
- [ ] Question2

## DoR
- [ ] Item has been estimated by the team
- [x] Item dependencies have been identified and documented

## DoD
- [x] Brand approval (if neccessary)
- [x] Figma documentation file incl. hand-off has been created/updated (if applicable)
- [x] Tokens have been applied/updated (if applicable)
- [ ] Crosslinks are created/updated
- [x] Implementation works successfully on `figma` branch

**Comment by coraliefeil** [comment]
Design comp is ready for code implementation. Closing this subtask.
