### ISSUE TITLE
feat[design]: ✨ publish sd-audio component

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1019]
## Description
This tasks describes the Figma release for: #270 

Current Figma version:
New Figma version:
Figma Branch:

### Open Questions towards development
- [ ] Question1
- [ ] Question2

## DoR
- [x] Item has been estimated by the team
- [x] Item dependencies have been identified and documented

## DoD
- [x] Figma documentation file incl. hand-off has been created/updated (if applicable)
- [x] Crosslinks are created/updated
- [x] Release Notes have been updated

**Comment by coraliefeil** [comment]
We need to swap the cc icon with a transcript icon. I’ve ordered this new icon (showing a doc with 2 lines) from brand.

**Comment by coraliefeil** [comment]
Published
