### ISSUE TITLE
feat[design]: ✨ publish sd-prose component

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1028]
## Description
This tasks describes the Figma release for: #417 

Current Figma version:
New Figma version:
Figma Branch: https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/Yuq4DmElgwOSyS3R2Zw9PO/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=22233-131&mode=design&t=YWY1xKr5hwWEeg8W-11

### Open Questions towards development
- [ ] Question1
- [ ] Question2

## DoR
- [x] Item has been estimated by the team
- [x] Item dependencies have been identified and documented

## DoD
- [ ] Figma documentation file incl. hand-off has been created/updated (if applicable)
- [ ] Crosslinks are created/updated
- [ ] Release Notes have been updated

**Comment by coraliefeil** [comment]
The code counterpart is almost done. Could you publish this whenever it suits you, pls? Thanks a lot
