### ISSUE TITLE
feat[design]: ✨ publish sd-step & sd-step-group component

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1030]
## Description
This tasks describes the Figma release for: #304 

Current Figma version: V.0.0.1
New Figma version: V.1.0.0
Figma Branch: [sd-step-group, sd-step](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/XQ86g7rO9VAF1zCeb3fMlh/Solid-DS-–-Component-Library?type=design&node-id=2573-18784&mode=design&t=kEojP6G1ZPpYvT2l-11)

### Open Questions towards development
- [ ] Question1
- [ ] Question2

## DoR
- [x] Item has been estimated by the team
- [x] Item dependencies have been identified and documented

## DoD
- [x] Figma documentation file incl. hand-off has been created/updated (if applicable)
- [x] Crosslinks are created/updated
- [x] Release Notes have been updated

**Comment by coraliefeil** [comment]
@van-nguyen-ht pls see updated component FYI
During coding we added the not interactive variant which can display a content icon or a number. It is not clickable and serves as a basis  to migrate the current CMS component.

Code comp is almost ready so you can publish the design comp.

And could you write a release note that is advertising the benefits and possibilities of this comp in an exciting and appealing way, pls?

**Comment by van-nguyen-ht** [comment]
component is published.
