### ISSUE TITLE
feat[design]: ✨ implement sd-status-bade component

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1047]
## Description
This tasks describes the Figma implementation for: #775

### Open Questions towards development
- [ ] Question1
- [ ] Question2

## DoR
- [ ] Item has been estimated by the team
- [ ] Item dependencies have been identified and documented

## DoD
- [ ] Brand approval (if neccessary)
- [ ] Figma documentation file incl. hand-off has been created/updated (if applicable)
- [ ] Tokens have been applied/updated (if applicable)
- [ ] Crosslinks are created/updated
- [ ] Implementation works successfully on `figma` branch

**Comment by yoezlem** [comment]
@coraliefeil @van-nguyen-ht can this ticket be closed directly?

**Comment by coraliefeil** [comment]
Done.
