### ISSUE TITLE
docs: 📚 add accessibility info to sd-prose

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#1094]
## Description
 
Was ist der Unterschied zwischen `<strong>` und `<b>`?
https://blogs.uni-bielefeld.de/blog/internetservice/entry/was_ist_der_unterschied_zwischen
 
We only offer `<strong>` in sd-prose.
 
-> Add the accessibility info to our documentation to raise awareness here

## DoR
- [x] Item has business value
- [ ] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by coraliefeil** [comment]
"We advise against using bold <b>, and italic <i> tags when you want to emphasize a word or passage."

https://help.siteimprove.com/support/solutions/articles/80000448460-accessibility-the-use-of-emphasis-in-text

**Comment by karlbaumhauer** [comment]
added to the #417 and close this ticket.

**Comment by yoezlem** [comment]
I would like to close the ticket because we will be conducting a comprehensive a11y audit of our components and will subsequently redefine the documentation and accessibility guidelines for each individual component: https://github.com/solid-design-system/solid/issues/1140

**Comment by karlbaumhauer** [comment]
@yoezlem fine for me.
