### ISSUE TITLE
feat[design]: ✨ implement hidden accessiblity buttons

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1101]
## Description
This tasks describes the Figma implementation for: #3 

Design proposal in [Figma Branch](https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/branch/y9Enil1bkF7bznHEdLi4XG/Solid-DS-–-Component-Library?node-id=25439-3495&t=roXak36cjXUXWkRu-11)

### Open Questions towards development
- [x] Any plans on if/how the design pattern could be reflected in code? What we’d like to provide from dev side. -> a template devs can copy & paste

## DoR
- [ ] Item has been estimated by the team
- [ ] Item dependencies have been identified and documented

## DoD
- [ ] Brand approval (if neccessary)
- [x] Figma documentation file incl. hand-off has been created/updated (if applicable)
- [x] Tokens have been applied/updated (if applicable)
- [ ] Crosslinks are created/updated
- [x] Implementation works successfully on `figma` branch

**Comment by van-nguyen-ht** [comment]
@coraliefeil Hi Coralie, here's the [pattern](https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/branch/y9Enil1bkF7bznHEdLi4XG/Solid-DS-–-Component-Library?node-id=25439-3495&t=7RdYFjFQd0tQcZbT-11), can you have a look and give me feedback? Thank you.

**Comment by van-nguyen-ht** [comment]
Thank you! I adjusted accordingly

**Comment by coraliefeil** [comment]
Thanks @van-nguyen-ht - nice job!

@mariohamann could you review this, pls? Merci

**Comment by coraliefeil** [comment]
Peer review done. Can be implemented in Storybook.
