### ISSUE TITLE
feat[dev]: ✨ WCAG 2.2 conformity on sd-navigation-item

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1103]
## Description
This tasks describes the Figma implementation for: #844

### Open Questions towards design
- [ ] Question1
- [ ] Question2

## DoR
- [x] Item has been estimated by the team
- [x] Item dependencies have been identified and documented

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by coraliefeil** [comment]
@solid-design-system/development the feature can be coded ... 

WRT A11y - it is all ok, as long as it complies with wcag 2.2

Damaris offers to double-check the updated comp when ready.
