### ISSUE TITLE
feat: ✨ add "Open in Codepen" to our storybook

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1105]
## User Story
As a user of the Solid Design System, I would like a playground environment (could be also codepen) within Storybook where I can test components, patterns, and placeholders.

### Suggested Solution
<img width="1467" alt="image" src="https://github.com/solid-design-system/solid/assets/98025014/c91f6f2a-a929-4699-97ba-4ab66c28b62c">

## Subtasks
- [ ] Design_implementation_task
- [ ] Development_implementation_task
- [ ] Design_release_task

## DoR
- [ ] Item has business value
- [ ] Item all subtasks have been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] All subtasks have been closed

**Comment by karlbaumhauer** [comment]
duplicate to #1138

**Comment by yoezlem** [comment]
I would close this one.
