### ISSUE TITLE
docs: 📚 Add storybook link to figma dev mode

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#1111]
## Description

Add storybook link to master component in figma dev mode.

Double-check in dev mode if link to figma documentation is correct.

## Where to put the documentation

![Image](https://github.com/solid-design-system/solid/assets/41894356/76241c0d-66f4-4452-b9de-1dcd5fe905ea)

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by coraliefeil** [comment]
Let’s check if the url path stays the same or if it changes due to restructuring tasks.
As soon as we are clear on that we can execute this task.

**Comment by MartaPintoTeixeira** [comment]
Storybook generic Link has been applied to all Figma Files in this folders:
- Solid DS Documentation
- Solid DS Library

@yoezlem Please let me know if:

1) I should also apply a generic Link to the remain Figma folder files:
- Playground
- Onboarding and updates
- Trainings

2) I should link each Figma component page (from Solid DS Documentation folder) with the respective page in the storybook (see image attached as an example)

**Comment by yoezlem** [comment]
@MartaPintoTeixeira I take the blocked label out of this ticket. So you can start with day anytime.

**Comment by MartaPintoTeixeira** [comment]
![Image](https://github.com/user-attachments/assets/9b46a584-5a19-47c9-8aa3-eafd5e4f7afd)

Done for all components
- Dev Links done (as in image above)
- Storybook links updated when missing
- Figma Documentation links updated
- Main Components linking to Figma Documentation

**Comment by MartaPintoTeixeira** [comment]
- Dev Links done in Figma Rewrite docs

**Comment by coraliefeil** [comment]
Could you also add DEV resources to each master component when in DEV mode, plS?

See on the right hand side in the Inspect panel.

![Image](https://github.com/user-attachments/assets/95086705-dc65-4d9e-9968-00354570694e)

You added dev resources to the figma page which is also good.

**Comment by MartaPintoTeixeira** [comment]
Done @coraliefeil please check again.

**Comment by coraliefeil** [comment]
Thanks a lot @MartaPintoTeixeira
