### ISSUE TITLE
ci: 👷 Random Playwright Fails due to Import error (Chromium)

### ISSUE THREAD

**Issue by Vahid1919** [solid-design-system/solid#1112]
## User Story
As a Developer for the Solid Design System, I would like to remove, or at least, understand why our CI piplines randomly fails due to a "Could not import test module" error that is only resolved with subsequent retries, so that I can push error free PRs and move on to my next task without worrying about random/wrong errors that slow down development in general. 

## Technical Information
Below is the logs for the failing CI build specifically the *install, verify and build check*. The specific area of interest for me was this line:  "❌ Could not import your test module. Check the browser logs or open the browser in debug mode for more information.  (failed on Chromium)"

[0_Install, verify and build.txt](https://github.com/solid-design-system/solid/files/15402827/0_Install.verify.and.build.txt)

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Implementation works successfully on `feature` branch

**Comment by karlbaumhauer** [comment]
@yoezlem I would like to prioritize this higher. @Vahid1919 had to run it 8-9 times yesterday to get the pipeline pass... :/
