### ISSUE TITLE
docs: improve FAQ

### ISSUE THREAD

**Issue by miguelxnxn** [solid-design-system/solid#1116]
## Improving FAQ Section
The FAQ content and structure can be improved to meet the different stakeholders' needs.

**Comment by yoezlem** [comment]
Hi @miguelxnxn whats the status of this ticket?

**Comment by miguelxnxn** [comment]
Questions from internal survey have been included and await review. We still need feedback on the question about the use of SDS for private projects @yoezlem 

Once reviewed I will import those questions to the github FAQ.
