### ISSUE TITLE
fix: 🤔 wrong icon accent color

### ISSUE THREAD

**Issue by christophsaile** [solid-design-system/solid#1125]
## Current behavior

currently the accent color of the icons is wrong:
![grafik](https://github.com/solid-design-system/solid/assets/54807480/18c67c55-27b8-4fb1-9aad-cd362c9b597f)

![grafik](https://github.com/solid-design-system/solid/assets/54807480/b8c57445-0ee1-42a1-97d4-4c67f09191b8)

## Expected behavior

rgb should be: 45 157 0 -> #2d9d00
rgb is: 67 176 42

## Steps to reproduce

https://cd.union-investment.de/grundlagen/Basiselemente/iconbibliothek

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by coraliefeil** [comment]
@christophsaile thank you for bringing that up. You are correct, the content icons should have 

fill: "icon-fill.accent"; (rgb 45 157 0, #2d9d00)

But – the issue is not on our end. Issue comes from Celum. 
As far as I know people responsible for Celum are currently working on a solution using for that.

@EllaELSA FYI

**Comment by christophsaile** [comment]
@coraliefeil I think this actually has to be fixed by the SDS Frontend since the SDS uses a mutator to add this value.
fyi: @mariohamann @yoezlem

**Comment by coraliefeil** [comment]
@mariohamann could you have a look, pls? THX

**Comment by mariohamann** [comment]
@christophsaile is absolutely right, this is on our side. @yoezlem I would count that as critical to be fixed soon.
