### ISSUE TITLE
docs: 📚 add changelog file to each package

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#1134]
## Description
In order to provide a consitant changelog for all our packages, we should add each changelog separately to our storybook. Currently only the components package is provided in stroybook.
## Open Questions

- [ ] Describe the change more clearly in the changelogs (was noted in the workshop => what was the intention here?)
- [ ] also for design? where is design writing the changelog?
- [ ] depending on the epic to separate our documentation into package folders.

## Where to put the documentation
Storybook
## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by yoezlem** [comment]
blocked by https://github.com/solid-design-system/solid/issues/1206
