### ISSUE TITLE
docs: 📚 split storybook into package-folder and add TOC to show available packages

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#1137]
## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by yoezlem** [comment]
Duplicate of #1131
