### ISSUE TITLE
feat: ✨ adjust state for step

### ISSUE THREAD

**Issue by van-nguyen-ht** [solid-design-system/solid#1162]
## User Story
As a consumer of the Solid Design System, I want to show steps that haven't been visited yet in the progress in an accessible way.

## Suggested Solution
-Restyle "waiting" variant with text.secondary (neutral-700) to comply with A11y
-Add "disabled" variant 

## Description

Since "disabled" already added in development, "waiting" needs to be added

Current Figma version: V.1.0.0
New Figma version: V.1.0.1
Figma Branch: [sd-step](https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/branch/f5TMyDvTKet0x4oLQzJuYB/Solid-DS-–-Component-Library?node-id=2573-18784&t=6XScs8Y7YI9RiYrK-11)

## DoD
- [x] Figma documentation file incl. hand-off has been created/updated (if applicable)
- [x] Adjust build
- [x] Tokens have been applied/updated (if applicable)
- [ ] Crosslinks are created/updated
- [x] Implementation works successfully on `figma` branch
- [ ] Published in Figma and communicated in release notes

**Comment by van-nguyen-ht** [comment]
@coraliefeil I'm done with the implementation so I moved it to "to be pre-refined" for development to handle because there's a mismatch: "disabled" already existed in storybook.

**Comment by coraliefeil** [comment]
@van-nguyen-ht see figma comments

**Comment by van-nguyen-ht** [comment]
I replied to you :)

**Comment by coraliefeil** [comment]
@van-nguyen-ht publish it, pls. THX

**Comment by van-nguyen-ht** [comment]
it is published :)
