### ISSUE TITLE
feat[design]: ✨ add inverted boolean to sd-audio component

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#1164]
This tasks describes the additional Figma implementation for: https://github.com/solid-design-system/solid/issues/270

- [x] Pls add inverted boolean to the current figma branch
- [x] Update documentation
- [x] Create new tokens

## DoR
- [ ] Item has business value
- [ ] Item all subtasks have been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

**Comment by van-nguyen-ht** [comment]
[Figma Branch](https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/branch/cHffrwo9yDeKpqsPcYN8R7/Solid-DS-–-Component-Library?node-id=21709-9318&t=TDQHbpfwDm7t27IG-11)

**Comment by coraliefeil** [comment]
Hey @van-nguyen-ht thanks for inverting ;)
I’ve left you some comments.
<3

**Comment by coraliefeil** [comment]
Ok, it’s alright. Thanks.

**Comment by van-nguyen-ht** [comment]
ok then I will close this issue
