### ISSUE TITLE
fix: [design] 🤔 color contrast for successfully validated form fields when hovered

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#1165]
## Current behavior

[See figma comment
](https://www.figma.com/design/xSIeTnyfW2T21Uw5JgdZOg?node-id=0-1#849850679)

We have the issue that when hovering the successful form fields ... the bg gets darker using neutral-200 ... unfortunately the success green has only 4.3 instead of 4.5 ...

## Expected behavior
Suggestion is not to change the green color again and also not to change the grey 200 color but to just get rid of red and green text INSIDE the validated field.

Since there is already the border color changing and a colored icon is shown ... that’s enough.
Also in case of an error message below ... this is also red text. 
There are no success messages below. But if there where ... light backgrounds are ok.

## Affected comps
-Textarea
-Datepicker
-Select
-Input & sample-autocomplete

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [x] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [x] Implementation works successfully on `feature` branch

[Figma Branch](https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/branch/G4Gaev1cbMDXQ4xBbVTR4U/Solid-DS-–-Component-Library?node-id=1211-14425&t=kqF7PUXQZrnmNZ6d-11)

**Comment by coraliefeil** [comment]
What do you think @EllaELSA ?

**Comment by coraliefeil** [comment]
Ok thanks @EllaELSA we’ll implement it as suggested.

**Comment by coraliefeil** [comment]
@van-nguyen-ht could you first list all affected comps and then adjust them as described above, pls?
Is this a breaking change or can we avoid that?

**Comment by coraliefeil** [comment]
We need to open up the corresponding dev ticket.

**Comment by van-nguyen-ht** [comment]
@coraliefeil since error text is a swappable slot, unfortunately this will create breaking changes.

**Comment by van-nguyen-ht** [comment]
[Figma Branch](https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/branch/G4Gaev1cbMDXQ4xBbVTR4U/Solid-DS-–-Component-Library?node-id=1211-14425&t=kqF7PUXQZrnmNZ6d-11)

**Comment by coraliefeil** [comment]
I’ll grab it for review

**Comment by coraliefeil** [comment]
What about updating documentation and hand-off?

**Comment by coraliefeil** [comment]
And the hand-off?

[This needs to be adjusted](https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/branch/G4Gaev1cbMDXQ4xBbVTR4U/Solid-DS-–-Component-Library?node-id=26116-2490&t=BPge2zhbURvEtFDb-11) as well
I think the comp got detached somehow.

When you are done, you can publish it ... pls. THX

**Comment by van-nguyen-ht** [comment]
it is published :)
