### ISSUE TITLE
docs: 📚 Remove duplicate in sd-flipcard variant story

### ISSUE THREAD

**Issue by Vahid1919** [solid-design-system/solid#1175]
## Description
 The primary variant is duplicated on the Variant story of the sd-flipcard (#1121 ). This is an emergent bug created with the interaction of our formatter and Storybook. Since the number of options is large prettier formats it like this:
![image](https://github.com/solid-design-system/solid/assets/63849626/1757ceb0-5c9b-4e68-aadf-5f4e89a0a6f3)

Storybook interprets the empty space before the first pipe(|) as an option, hence resulting in this duplication. 
![image](https://github.com/solid-design-system/solid/assets/63849626/6ff8f5c2-b05d-4e77-a984-c218f00835f3)

## Where to put the documentation
Storybook

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by coraliefeil** [comment]
Could be includes while working on https://github.com/solid-design-system/solid/issues/1314

**Comment by mariohamann** [comment]
Closed with https://github.com/solid-design-system/solid/pull/1689
