### ISSUE TITLE
Translate Processes to EN

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#1190]
We need to update our process charts and translate them to EN.

- [x] [Collaboration Process](https://www.figma.com/board/D0caneHSPvaVyJ1s8HLlVf/Collaboration-Process?node-id=0-1&t=cmyHmoVQW7057HVZ-1)

- [x] [VRT/QA Process](https://www.figma.com/board/yg2PKZ0ghndLBAPYm7kbaN/VRT-%2F-QA-Workflow?node-id=0-1&t=fIZLjL4oVod8HXrw-1)

- [x] [Icon Sourcing Process](https://www.figma.com/board/R87jmbwcrqXnMeM4HT1Zo5/Icon-Sourcing-Process?node-id=0-1&t=i4O1AMz4O3gmj6Vh-1)

**Comment by karlbaumhauer** [comment]
@coraliefeil pls review. I kept the original Frames and replaced the texts in order to keep all created deep links available.

To review it, I copied the original frames with German texts to the left side, which should be deleted as soon as you are fine with the result.

**Comment by coraliefeil** [comment]
All good. THX
