### ISSUE TITLE
fix: 🤔 sd-carousel - numbered variant - show total clicks

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#1191]
## Current behavior

For multiple slides per view:

The numbered variant does not show the total amount of clicks on the right: < 1 / 10 > (Immediate fix needed!)

## Expected behavior

The numbered variant shows the total amount of clicks on the right: < 1 / 10 >

![Image](https://github.com/solid-design-system/solid/assets/41894356/baaaac67-2442-47cb-ba6a-daa6a6d5f57f)

## Steps to reproduce

https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/story/components-sd-carousel--default&args=variant-attr:10;slides-per-page-attr:2;slides-per-move-attr:1&globals=outline:!true

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by coraliefeil** [comment]
I’ve updated the [figma documentation](https://www.figma.com/design/F856KwF4q6ksLJzwj0tW56/Carousel?node-id=971-4578&t=czWvfvApbY1yd5TE-11) to make it easier to understand.

**Comment by MartaPintoTeixeira** [comment]
Proposals discussed in the previous daily:

# 5 Slides, 1 slide move, 2 per view
1–2 → “1/5”
2-3 → “2/5”
3–4 → “3/5” → ?!
4–5 → “4/5” → ?!
5–1 → “5/5” → ?!
 
# 5 Slides, 2 slide move, 2 per view
1–2 → “1/5”
3–4 → “2/5”
5–1 → “3/5” → ?!
2–3 → “4/5”
4–5 → “5/5”

Another proposal could be: 
 
# 5 Slides, 1 slide move (with exception), 2 per view
1–2 → “1/4”
2-3 → “2/4”
3–4 → “3/4” 
4–5 → “4/4”

**Comment by mariohamann** [comment]
Finally having the time to write it down, sorry for the big delay. One big issue we discussed was: How do we handle uneven amounts here, how should the last slide bheave, what happens with the transition from the last slide to the first slide etc. We discussed several proposals and their impacts and this is our final result:

1. The number shows the amount of clicks until the last/first slide is reached.
2. The carousel always moves the amount slides that is stated in `slides-per-move`. The final click to the right always shows the last slide in the last position.

<video src="https://github.com/user-attachments/assets/7ceb689e-3b96-46f1-9c3a-71e07eb8bb58"></video>

3. When moving back from there, the carousel again moves the amount of slides that is stated in `slides-per-move`. The final click to the right always shows the first slide in the first position.

<video src="https://github.com/user-attachments/assets/8adce3d6-697d-404a-87c6-954702efabda"></video>

4. This allows us to have a clean state when carousels are able to circle.

<video src="https://github.com/user-attachments/assets/ee6db43e-14cb-46e7-b130-5d0112e466d1"></video>

Here's the Figma Prototype: https://www.figma.com/design/SnCa3cptOXecI3ajxLim6a/Carousel-Demo?node-id=1-14&t=nI4uRwfMUGx0771j-11

In the PR there should be definitely some tests with different `slides-per-move` and `slides-per-page` that show that everything is calculated correctly.

**Comment by mariohamann** [comment]
@karlbaumhauer @yoezlem This is now done from my side and definitely reviewable! :)

**Comment by karlbaumhauer** [comment]
thx @mariohamann for the explanation. As you stated in your intro, one big issue was the behavior with uneven numbers of slides. Unfortunately, I only see the solution for 8 slides but I still don't unterstand how this works with eg, 9 slides. Could you provide a screen capture for this as well?

**Comment by mariohamann** [comment]
It's not about uneven but about number of slides / number of moves per page not being dividable.

So in the example we have 8 slides and move 3 per page, which didn't work out before. The proposal now works for every example.
