### ISSUE TITLE
docs: 📚 update migration guide `sd-tab/-group`

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#1218]
## Description
The old CL component has the functinality to open a specific tab by setting the `active` property to the respective tab.
Our component only uses this property to style the active tab and therewith we reduced the functionality.

This should be explained in the respective migration guide.
## Where to put the documentation
Storybook
## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by Vahid1919** [comment]
@karlbaumhauer sd-tab has the "active" attribute that can be toggled to set a tab as "active". This goes beyond styles and changes the tab's property. Additionally, the sd-tab-group has the "setActiveTab" method that is also documented in the tab-group migration guide.

From my perspective, we already covered our bases here. Did I miss anything?

**Comment by karlbaumhauer** [comment]
your right, I mixed up the bad docs in CL...
sorry for that. I therefore close the ticket.
