### ISSUE TITLE
feat: ✨ Create a Support Channel in MS Teams for the Solid Design System Community

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1219]
## User Story
As a user of the Solid Design System, I would like to have a dedicated Support Channel for my support inquiries, as well as keep the General Channel focused on announcements and general discussions, so that support requests are addressed more efficiently, and the General Channel remains organized and easier to navigate.

### Suggested Solution

- [x] Create a new channel named "Support" within the Solid Design System Community MS Teams.
- [x] Communicate the change to all users, specifying that the General Channel is now exclusively for announcements and general discussions.
- [x] Remove write permissions in the General Channel for all users of the Solid Design System, ensuring it remains for announcements only.
- [x] Keep the Support Channel open so that all users can post their inquiries freely.

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [x] All tasks from the Suggested Solution have been completed.

**Comment by karlbaumhauer** [comment]
@yoezlem pls have a look if you need anything else. If not, pls close the ticket.
