### ISSUE TITLE
fix: 🤔 <sd-link> empty download attribute does not get passed to <a> tag

### ISSUE THREAD

**Issue by christophsaile** [solid-design-system/solid#1222]
## Current behavior
Currently a empty download attribute `download=""` on a `<sd-link>` does not get passed to the underlying `<a>` tag.

MDN Spec:
![image](https://github.com/user-attachments/assets/7b1b2812-255c-4570-9bf8-4ea7de09fd0d)
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#download

## Expected behavior
empty download attribute gets passed to `<a>` tag.

## Steps to reproduce
1. add `download=""` to <sd-link>
2. inspect DOM

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
On `sd-tag` it seems to work. Do you want to give it a shot how we implemented it there?
https://github.com/solid-design-system/solid/blob/d7069ef1e8a847a406c054ce2726d6c8fd681318/packages/components/src/components/link/link.ts#L96
