### ISSUE TITLE
fix: 🤔 sd-brandshape image should not be cut at the bottom

### ISSUE THREAD

**Issue by MartaPintoTeixeira** [solid-design-system/solid#1241]
## Current behavior
The image in the brandshape is cut off at the bottom.
![Image](https://github.com/user-attachments/assets/52effb92-a684-4380-924d-f33664533d50)

## Expected behavior
We should be able to see the full shape and the image should fill it.
Figma Link: https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-%E2%80%93-Component-Library?node-id=8713-2940&t=9j5W6Vvj2CwLpBA2-0
![Image](https://github.com/user-attachments/assets/881b51f4-dc01-4ff2-9ead-e171caed1f7d)

## Steps to reproduce
Open Link: https://64469bd84c5ea1ce2dd5d016-dalsbcuqyd.chromatic.com/?path=/story/components-sd-brandshape-screenshot-tests--sample&globals=viewport:mobile1

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by smfonseca** [comment]
@MartaPintoTeixeira I believe this ticket can be closed since the issue was fixed with the changes introduced by this PR [1415](https://github.com/solid-design-system/solid/pull/1415). Can you please double check? FYI @yoezlem

**Comment by coraliefeil** [comment]
@MartaPintoTeixeira pls double-check if the issue still exists like @karlbaumhauer mentioned

**Comment by MartaPintoTeixeira** [comment]
Issue has been closed before
