### ISSUE TITLE
fix: 🤔 sd-brandshape missing copyright on variant

### ISSUE THREAD

**Issue by MartaPintoTeixeira** [solid-design-system/solid#1246]
## Current behavior
Missing copyright variant on sd-brandshape

## Expected behavior
Add copyright variant.
Open figma: https://www.figma.com/file/XU1a0M2ammirJ5ka1vigfY/Brandshape?type=design&node-id=1601-195&mode=design&t=R5qAGkMCUnR15JXQ-11&fuid=1389641047778298367 - see last image
![Image](https://github.com/user-attachments/assets/503165fb-ef8a-4ed9-a629-569a8951bb17)

## Steps to reproduce
https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/story/components-sd-brandshape--variants - copyright variant does not exist.

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by karlbaumhauer** [comment]
blocked by #1319
