### ISSUE TITLE
fix: 🤔 wrong type in `sd-carousel` variant property

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#1249]
## Current behavior
Currently the variant property is described as string but shown as number type in Storybook. 
## Expected behavior
Storybook shows the correct type.
## Steps to reproduce

![Image](https://github.com/user-attachments/assets/0fc3e393-60e7-48fa-9b06-790d17dd4fc6)

## Technical Information
- [ ] if this is a storybook bug, we will leave a hint in the description of the component.

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by Vahid1919** [comment]
![Image](https://github.com/user-attachments/assets/f374a937-dd63-4ef7-9ba9-da93e4d4aa7c)

![Image](https://github.com/user-attachments/assets/69176f52-0380-423f-a295-8384b6dbf433)

![Image](https://github.com/user-attachments/assets/0558c5cf-0b2e-49b1-b068-e4c7cee33235)

**Comment by Vahid1919** [comment]
Waiting for #1131 as it could possibility allow us to close this issue.

**Comment by mariohamann** [comment]
Closed with https://github.com/solid-design-system/solid/pull/1689
