### ISSUE TITLE
fix: 🤔 pause not working in `sd-carousel`

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#1250]
## Current behavior
The current "inverted" sample shows different sd-carousel samples but all of them keep moving even though 2 of them are paused. 

## Expected behavior
Pause should work if paused is clicked and if you hover (or focusing it via keyboard) the carousel.

## Steps to reproduce
https://github.com/user-attachments/assets/06c56630-8c13-4415-8a8b-290586623ec3

## Technical Information
- Please first check the autoplay function
- As soon as you hover on the sd-carousel (in paused state) its working
- Please add documentation to Autoplay Story (Figma + Storybook)

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by Vahid1919** [comment]
@karlbaumhauer One of the bullet points in here mentions: "Please add documentation to Autoplay Story (Figma + Storybook)"
I took a look and I am not sure what is missing. 
![Image](https://github.com/user-attachments/assets/2ee91807-8277-4ab4-b02c-5e4178615eea)

**Comment by karlbaumhauer** [comment]
> @karlbaumhauer One of the bullet points in here mentions: "Please add documentation to Autoplay Story (Figma + Storybook)" I took a look and I am not sure what is missing. 

@Vahid1919 this was about the behavior of the autoplay in addition to hovering over the element etc. As we had a short discussion while talking about this ticket until everybody understood what to expect, we agreed that we at least give some hints to understand how this should work. Especially with/for the pause-button.
