### ISSUE TITLE
fix: 🤔 sd-teaser-media variant title alignment

### ISSUE THREAD

**Issue by MartaPintoTeixeira** [solid-design-system/solid#1296]
## Current behavior
Issues:
On storybook the variant "Gradient-light" is named "Gradient-white"

## Expected behavior
Variant should be named "Gradient-light" as it is in FIGMA.

## Steps to reproduce
https://solid-design-system.fe.union-investment.de/x.x.x/storybook/index.html?path=/docs/components-sd-teaser-media--docs

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by karlbaumhauer** [comment]
@coraliefeil pls check if the secondpoint is still valid.

**Comment by coraliefeil** [comment]
If we don’t change the default variant it is not a breaking change IMO @yoezlem that’s why I removed the label.

**Comment by mariohamann** [comment]
It is a breaking change, as if someone set `gradient-white` in the past, this won't work anymore.

**Comment by coraliefeil** [comment]
Ah ok. Understood. THX
