### ISSUE TITLE
fix: 🤔 consolidate sizes in input components (sd-radio/sd-checkbox/...)

### ISSUE THREAD

**Issue by Vahid1919** [solid-design-system/solid#1326]
## Current behavior
You cannot set `sd-radio-group` as size ="md" (options are 'lg', 'sm'). This means that even though `sd-radio-button` has a "md" size, there is no way to set this since `sd-radio-button` does not accept "md" as a size option and will reset all sizes set on the child `sd-radio-buttons` to the default "lg"

![Image](https://github.com/user-attachments/assets/0dfd36db-ce47-48ff-9d4c-f14be51ef6ca)

## Expected behavior
You can set the `sd-radio-group`'s size as "md", in order to showcase medium sizes `sd-radio-buttons`

![Image](https://github.com/user-attachments/assets/d8505f0c-661b-4ccd-ab10-2f7e78af2f63)

## Steps to reproduce
Take a look at the Docs page of sd-radio-group and sd-radio-button, the group lacks a size "md" making sd-radio-buttons for this size incompatible.

## Technical Information
- [x] Design will rename the size in sd-radio / sd-checkbox & the group components
- [x] Code will add 3 sizes for sd-radio / sd-checkbox consistency wise

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by yoezlem** [comment]
@coraliefeil why do we only have sm and lg in the group? 
it would be much easier in code to add a md in the group, otherwise we need some different logic for sd-radio-button with sd-radio-group.

**Comment by coraliefeil** [comment]
We do have md as size.

[Figma Docs](https://www.figma.com/design/YDktJcseQIIQbsuCpoKS4V/Component-Docs?node-id=2269-23175&node-type=frame&t=eEEw9aJ7m2gbprCK-11)
[Figma Handoff](https://www.figma.com/design/YDktJcseQIIQbsuCpoKS4V/Component-Docs?node-id=2269-23208&node-type=frame&t=eEEw9aJ7m2gbprCK-11)

**Comment by MartaPintoTeixeira** [comment]
Pulished in figma and updated in figma docs

**Comment by coraliefeil** [comment]
This can be closed, right? @MartaPintoTeixeira
