### ISSUE TITLE
feat[dev]: ✨ brandshape image without default slot

### ISSUE THREAD

**Issue by smfonseca** [solid-design-system/solid#1339]
## User Story
As a user of the Solid Design System, I want to display images with the brandshape and there should be no option to include content on top of the image. 

### Suggested Solution
If the chosen variant is `image`, the default slot should not be rendered.

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
This was per accident already tackled in https://github.com/solid-design-system/solid/pull/1585

**Comment by mariohamann** [comment]
I misread this and reopened.
