### ISSUE TITLE
fix: 🤔 sd-tab container variant icon spacing

### ISSUE THREAD

**Issue by smfonseca** [solid-design-system/solid#1345]
## Current behavior
Currently the icon shows without spacing to the label.
![image](https://github.com/user-attachments/assets/1125a85b-af41-4b9c-ad1a-f7db8e0ad105)

## Expected behavior
The icon and label have the correct spacing between each other.

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
Is duplicate of [#1709](https://github.com/solid-design-system/solid/issues/1709)
