### ISSUE TITLE
feat[design]: ✨ Publish tmpl-button-group in Figma

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1373]
## Description
This tasks describes the Figma release for: #1158 

Current Figma version:
New Figma version:
Figma Branch:

### Open Questions towards development
- [ ] Question1
- [ ] Question2

## DoR
- [ ] Item has been estimated by the team
- [x] Item dependencies have been identified and documented

## DoD
- [x] Figma documentation file incl. hand-off has been created/updated (if applicable)
- [x] Crosslinks are created/updated
- [x] Release Notes have been updated

**Comment by MartaPintoTeixeira** [comment]
Already done

**Comment by MartaPintoTeixeira** [comment]
Already done
