### ISSUE TITLE
feat[design]: ✨ create overview page for all components

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1383]
## Description
This tasks describes the Figma implementation for: #1379 

### Open Questions towards development
- [ ] Question1
- [ ] Question2

## DoR
- [ ] Item has been estimated by the team
- [x] Item dependencies have been identified and documented

## DoD
- [ ] Brand approval (if neccessary)
- [ ] Figma documentation file incl. hand-off has been created/updated (if applicable)
- [ ] Tokens have been applied/updated (if applicable)
- [ ] Crosslinks are created/updated
- [ ] Implementation works successfully on `figma` branch

**Comment by coraliefeil** [comment]
The overview page already exists in figma.
