### ISSUE TITLE
feat[design]: ✨ sd-audio - delete volume slider

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#1417]
## Description
This tasks describes the adjusted Figma implementation for: #270 

### Open Questions towards development
- [x] Design Proposal [Figma Link](https://www.figma.com/design/cHffrwo9yDeKpqsPcYN8R7?node-id=3112-20014#955597576) - Does it work for dev?

## DoR
- [ ] Item has been estimated by the team
- [ ] Item dependencies have been identified and documented

## DoD
- [ ] Brand approval (if neccessary)
- [ ] Figma documentation file incl. hand-off has been created/updated (if applicable)
- [ ] Tokens have been applied/updated (if applicable)
- [ ] Crosslinks are created/updated
- [ ] Implementation works successfully on `figma` branch

**Comment by SoldierFace** [comment]
This might help:This file might fix it
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw

you may need to install the c compiler

**Comment by coraliefeil** [comment]
The proposal did not work for dev. Apparently the feature causes glitches. We decided together to simplify sd-audio by only using a toggle to mute/unmute the volume.
