### ISSUE TITLE
fix: 🤔 Navigation-Item medium size name

### ISSUE THREAD

**Issue by auroraVasconcelos** [solid-design-system/solid#1418]
## Current behavior
The medium size name for the sd-navigation-item is 'base'.

## Expected behavior
In order to keep consistence with other components and with figma the expected value would be 'md'

## Steps to reproduce
[Link to storybook](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/components-sd-navigation-item--docs)

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
Closed with https://github.com/solid-design-system/solid/pull/1689
