### ISSUE TITLE
docs: 📚 bring back documentation

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#1420]
## Description

> We're documenting how a component works and what it does and which features it offers – not just single attributes!

During our docs migration, there were former docs migrated to templates (instead of the definition that only samples are moved to templates), that are definitely needed for proper documentation to understand how to use the component:

- [Media / Description](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/templates-media--docs#description): We need to document how to use descriptions, as this is more or less the only thing what media does and why `inverted` exists.
- [Tab Group / Scrollable](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/templates-tabs--docs#tabs%20scrollable): Scrollable is something designers and developers have to be aware of from the documentation. It's part of how it works and they have to do nothing about it.
- [Tab Group / Contained](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/templates-tabs--docs#tabs%20variants): It's worth bringing this into the docs as well. Container is a default feature and therefore has to be shown in context. Move this to `sd-tab` instead of `sd-tab-group`. It's more or less the same as for `sd-option` – it makes not really sense to document `sd-option` `disabled` without the surrounding group.´

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by Vahid1919** [comment]
One the sidenote regarding radio-button template. I believe that was created before we decided to turn all radio/radio-button stories into sd-radio-groups. It was not an intentional choice to add it after the fact. But I see how it is somehow "obsolete" now.
