### ISSUE TITLE
feat: ✨ create tooltip slot for input elements

### ISSUE THREAD

**Issue by auroraVasconcelos** [solid-design-system/solid#1437]
## Description
Implement in code the [Figma template](https://www.figma.com/design/YDktJcseQIIQbsuCpoKS4V/Component-Docs?node-id=3274-20693&t=mH0nYpTWLtKplwyF-4)

- Please add the links as _Related Templates_ to the components used in the templates.

## Where to put the documentation
[Storybook](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/docs-general-introduction--docs)

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by yoezlem** [comment]
@Vahid1919 could you add SP to the Ticket?
