### ISSUE TITLE
docs: 📚 create carousel template

### ISSUE THREAD

**Issue by auroraVasconcelos** [solid-design-system/solid#1439]
## Description
Implement in figma a solution. Current solution in [code](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/templates-carousel--docs)

- Please add the links as _Related Templates_ to the components used in the templates.

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by MartaPintoTeixeira** [comment]
Done
