### ISSUE TITLE
docs: 📚 update accordion group template

### ISSUE THREAD

**Issue by auroraVasconcelos** [solid-design-system/solid#1441]
## Description
The sections are correct but in
[Figma](https://www.figma.com/design/YDktJcseQIIQbsuCpoKS4V/Component-Docs?node-id=2751-1280&t=6HRILZbABowUMyVM-4)
example contains images that are not present in
[storybook](https://solid-design-system.github.io/solid/main/?path=/docs/templates-accordion-group-on-different-backgrounds--docs).

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by MartaPintoTeixeira** [comment]
1 ) Please sync the titles with FIGMA:
Accordion Group Background White
Accordion Group Background Neutral-100
Accordion Group Background Primary-100

2 ) This copy: Examples of the sd-accordion-group component in different backgrounds.
Should be after the title
