### ISSUE TITLE
docs: 📚 Update autocomplete template

### ISSUE THREAD

**Issue by auroraVasconcelos** [solid-design-system/solid#1442]
## Description
Missing section ["Input with Autocomplete"](https://www.figma.com/design/YDktJcseQIIQbsuCpoKS4V/Component-Docs?node-id=2858-511&t=nUqqPqJcrcmXxv4R-4) in [storybook](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/templates-autocomplete--docs).

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by yoezlem** [comment]
We're going to create a combobox Component. So we can close this one! :)
