### ISSUE TITLE
docs: 📚 update tag template

### ISSUE THREAD

**Issue by auroraVasconcelos** [solid-design-system/solid#1447]
## Description
Missing sections ["Filter Tag Group", "Filter Tag Group with Morningstar Rating", "Filter Tag Group with Risk", "Removable Filter Tag Group" and "Tag Group with Links"](https://www.figma.com/design/YDktJcseQIIQbsuCpoKS4V/Component-Docs?node-id=3274-20467&t=nUqqPqJcrcmXxv4R-4) in [storybook](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/templates-tag--docs).

## DoR
- [x] Item has business value
- [ ] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by MartaPintoTeixeira** [comment]
Copy change:
Filter Tag Group Risk
Should be:
Filter Tag Group with Risk

**Comment by MartaPintoTeixeira** [comment]
Copy change:
Tag Group Links
Should be:
Tag Group with Links

**Comment by MartaPintoTeixeira** [comment]
Copy change:
Tag Background options
Should be:
Tag Background Options
