### ISSUE TITLE
docs: 📚 update header template

### ISSUE THREAD

**Issue by auroraVasconcelos** [solid-design-system/solid#1448]
## Description
Missing section ["Header Sample A-02"](https://www.figma.com/design/YDktJcseQIIQbsuCpoKS4V/Component-Docs?node-id=3502-218572&t=nUqqPqJcrcmXxv4R-4) in [storybook](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/templates-header--docs).

## DoR
- [x] Item has business value
- [ ] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by MartaPintoTeixeira** [comment]
The 3rd sample has different copy from FIGMA. But let me check with Coralie if we should actually translate all to english before you edit the copy here.

**Comment by MartaPintoTeixeira** [comment]
When the drawer is open in the hamburger format there is a bug in the last items. Will create a fix ticket to fix the alignment of this bug.

 ![Image](https://github.com/user-attachments/assets/151244fd-13ae-436c-8c73-40b741496d55)
