### ISSUE TITLE
feat[dev]: ✨ implement A11y improvements to sd-map-marker

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1480]
## Description
This task describes the Storybook implementation for the sd-map-marker component as part of the A11y improvements outlined in Epic https://github.com/solid-design-system/solid/issues/1465.

A11y improvements for sd-map-marker can be found here: [sd-map-marker Notes](https://www.notion.so/matuzo/sd-map-marker-dab1a192e8e9439b972479597195d29d).

------------------------------

## Comment
Problem: The map marker is focusable but has no semantic role and accessible name.
Solution: Include not-interactive property (see sd-step), remove hover/focus styles according to this. It should include functionality to switch between link/button depending on existence of href, and also into a div and not-interactive is set to true. 

- [x] Include not-interactive property (see sd-step)
- [x] Remove hover/focus styles according to not-interactive property
- [x] Include functionality to switch between link/button depending on existence of href
- [x] And also into a div and not-interactive is set to true

## Notes
Focus Styles are different in Safari. Don’t rely on the user agent styles, you have to set the outline-style explicitly.

- [x] Fix focus styles in Safari

**Safari**
![Image](https://github.com/user-attachments/assets/07dd984d-59c2-4a73-84e6-bf4ec3182483)

**Chrome**
![Image](https://github.com/user-attachments/assets/dcf39776-7ce8-489a-aec3-4407a88e0db7)

Design

- [x] Include `not interactive` and `href` in Figma

### Open Questions
- [ ] Question1
- [ ] Question2

## DoR
- [x] Item has been estimated by the team
- [x] Item dependencies have been identified and documented

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by smfonseca** [comment]
@MartaPintoTeixeira this ticket requires updates in Figma regarding some new attributes in the map marker. Please check storybook on my [feature branch](https://solid-design-system.github.io/solid/feat_sd-map-marker-a11y/?path=/docs/components-sd-map-marker--docs). If you have any questions or suggestions for the descriptions, please let me know

**Comment by MartaPintoTeixeira** [comment]
@smfonseca on the state sample the cluster of the 2nd line is not in line with the map makers on its side. can you aline them?
