### ISSUE TITLE
feat[dev]: ✨ implement A11y improvements to sd-tag

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1490]
## Description
This task describes the Storybook implementation for the sd-tag component as part of the A11y improvements outlined in Epic https://github.com/solid-design-system/solid/issues/1465.

A11y improvements for sd-tag can be found here: [sd-tag Notes](https://www.notion.so/matuzo/sd-tag-10ef3f6e1bc080df951fcd49f55c5ffa).

--------------------------------------

## Comment
**Problem:** Selected tags communicate they're selected state purely visually.
**Solution:** 

- [x] Bind `aria-pressed="true|false"` to the `selected` to indicate that state semantically.
- [x] Add a new attribute `toggleable` to make sure the `aria-pressed` state is not used when being not a toggle (eg. a button or link).
- [x] Update the docs to explain/describe the new attributes and their purpose.
- [x] refactor the "Selected" story to show the exact behavior (select and de-select), add the "toggleable" attribute and add a hint to the story in order to make clear the 2 attributes are only working together
- [x] add code-only description to Figma

## Notes
- Disabled tags: See [@sd-button](https://www.notion.so/sd-button-104f3f6e1bc0800b9f72d2a046316ec3?pvs=24). Everything I wrote there about disabling form elements applies here as well.

## Related WCAG criteria
- https://www.w3.org/WAI/WCAG22/quickref/#name-role-value

## DoR
- [x] Item has been estimated by the team
- [x] Item dependencies have been identified and documented

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by MartaPintoTeixeira** [comment]
"Code-only: Use the attribute ”toggleable” to reflect the selected state on the ”aria-pressed” attribute." - added to figma

**Comment by MartaPintoTeixeira** [comment]
Approved
