### ISSUE TITLE
feat[dev]: ✨ implement A11y improvements to sd-teaser and sd-teaser-media

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1491]
## Description
This task describes the Storybook implementation for the sd-teaser and sd-teaser-media component as part of the A11y improvements outlined in Epic https://github.com/solid-design-system/solid/issues/1465.

A11y improvements for sd-teaser and sd-teaser-media can be found here: [sd-teaser and sd-teaser-media Notes](https://www.notion.so/matuzo/sd-teaser-sd-teaser-media-10ef3f6e1bc080c69381d77ac67e232f).

### Open Questions / Todos
- Nested interactive elements is going to be tackeld in #1541 
- [x] Transparency: Align with brand A11y expert (or @coraliefeil & @EllaELSA) as he said 80% transparency is fine
- [x] Focus style: Clarify on the focus style as the inverted button has white focus => test the template and/or fix it
- [x] Expandable teaser: 
  - [x] extend the A11y hint to make clear it should not contain any important content AND its only for mouse users.
  - [x] add "aria-hidden" attribute to the expandable part in order to make it "not available" to keyboard users
- [x] Add "notes" to a11y dad (dos and donts)
- [x] Add "best practices" to a11y dad (dos and donts)
- [ ] copy A11y section from figma zu Storybook

## Template Ticket
- [ ] Pick up the template ticket when working on the component story for A11y improvement, as it references the component and will be resolved once the component is made accessible:
#1526

## DoR
- [x] Item has been estimated by the team
- [x] Item dependencies have been identified and documented

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by smfonseca** [comment]
@coraliefeil @EllaELSA do you have any news regarding this point =>  _Transparency: Align with brand A11y expert (or @coraliefeil & @EllaELSA) as he said 80% transparency is fine_

It seems the only variant which is not using 80% transparency right now is `gradient-dark` with 60%. Should I update it?

**Comment by coraliefeil** [comment]
> [@coraliefeil](https://github.com/coraliefeil) [@EllaELSA](https://github.com/EllaELSA) do you have any news regarding this point => _Transparency: Align with brand A11y expert (or [@coraliefeil](https://github.com/coraliefeil) & [@EllaELSA](https://github.com/EllaELSA)) as he said 80% transparency is fine_
> 
> It seems the only variant which is not using 80% transparency right now is `gradient-dark` with 60%. Should I update it?
> 
> Also regarding this => _copy A11y section from figma zu Storybook_ Currently there is only one point in the accessility section of the teaser media. Will there be anything else to include or it's only this?
> 
> Thank you

@smfonseca we are save contrast-wise with 4.79:1 (white text on gradient #051530 (60% - 75%) on image.

No action needed.

**Comment by smfonseca** [comment]
Thanks @coraliefeil, I will then consider the transparency criteria as done.

**Comment by coraliefeil** [comment]
@smfonseca could you copy [the a11y section from figma](https://www.figma.com/design/YDktJcseQIIQbsuCpoKS4V/Component-Docs?node-id=9398-12315&node-type=frame&t=cSo2skXfTeHdnzTT-11) to storybook, pls? Then this issue is solved.
