### ISSUE TITLE
feat[dev]: ✨ implement A11y improvements to sd-media

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1506]
## Description
This task describes the Storybook implementation for the sd-media component as part of the A11y improvements outlined in Epic https://github.com/solid-design-system/solid/issues/1465.

A11y improvements for sd-media can be found here: [sd-media Notes](https://www.notion.so/matuzo/sd-media-111f3f6e1bc0804491b5e692c57ba857).

----------------------------------

## Comment
No critical issues found.

## Notes
- Inverted example: According to the WCAG contrast algorithm, the contrast ratio is high enough, but the algorithm isn't perfect, which can be seen here. The ratio is 4.78:1, but the text is still hard to read.

### Open Questions
- [ ] Question1
- [ ] Question2

## DoR
- [ ] Item has been estimated by the team
- [x] Item dependencies have been identified and documented

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by karlbaumhauer** [comment]
we either keep the WCAG as baseline or not => closed
