### ISSUE TITLE
feat[dev]: ✨ implement A11y improvements to sd-table and sd-table-cell

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1507]
## Description
This task describes the Storybook implementation for the sd-table and sd-table-cell component as part of the A11y improvements outlined in Epic https://github.com/solid-design-system/solid/issues/1465.

A11y improvements for sd-table and sd-table-cell can be found here: [sd-table and sd-table-cell Notes](https://www.notion.so/matuzo/sd-table-sd-table-cell-111f3f6e1bc080e4a9f7c5eba3b34548).

--------------------------------

## Comment
The default example doesn’t show a proper data table.

### Open Questions
- [ ] Question1
- [ ] Question2

## DoR
- [ ] Item has been estimated by the team
- [x] Item dependencies have been identified and documented

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by karlbaumhauer** [comment]
changing this would make the code sample more complex => 10 lines of code but only 1 is important
