### ISSUE TITLE
feat[dev]: ✨ implement A11y improvements for Dialog Template

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1515]
## Description
This task describes the Storybook implementation for the Dialog template as part of the A11y improvements outlined in Epic https://github.com/solid-design-system/solid/issues/1465.

A11y improvements for the Dialog template can be found here: [Dialog Notes](https://www.notion.so/matuzo/Dialog-10ef3f6e1bc080208085f65e9e0ea80c).

------------------------

## Comment
Dialog with scrollable content: see [@sd-dialog](https://www.notion.so/sd-dialog-107f3f6e1bc080948724df1760e8afad?pvs=24)

### Open Questions
- [ ] Question1
- [ ] Question2

## DoR
- [ ] Item has been estimated by the team
- [x] Item dependencies have been identified and documented

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by karlbaumhauer** [comment]
closed as handled in #1473
