### ISSUE TITLE
feat[dev]: ✨ implement A11y improvements for Expandable Template

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1517]
## Description
This task describes the Storybook implementation for the Expandable template as part of the A11y improvements outlined in Epic https://github.com/solid-design-system/solid/issues/1465.

A11y improvements for the Expandable template can be found here: [Expandable Notes](https://www.notion.so/matuzo/Expandable-112f3f6e1bc080df9a33e0bfc7cdee80).

----------------------------------------------

## Comment
See [@sd-expandable](https://www.notion.so/sd-expandable-10af3f6e1bc0801ca8a3dbddf01d541c?pvs=24) 

### Open Questions towards design
- [ ] Question1
- [ ] Question2

## DoR
- [ ] Item has been estimated by the team
- [x] Item dependencies have been identified and documented

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by karlbaumhauer** [comment]
closed as handeled in #1476
