### ISSUE TITLE
feat[design]: ✨ UX concept for new sd-flipcard

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#1543]
## Description
This tasks describes the Figma implementation for: #1540 

### Open Questions towards development
- [ ] Question1
- [ ] Question2

## DoR
- [x] Item has been estimated by the team
- [x] Item dependencies have been identified and documented

## DoD
- [ ] Brand approval (if neccessary)
- [ ] Figma documentation file incl. hand-off has been created/updated (if applicable)
- [ ] Tokens have been applied/updated (if applicable)
- [ ] Crosslinks are created/updated
- [ ] Implementation works successfully on `figma` branch

**Comment by coraliefeil** [comment]
We can implement the icon for flipping the card like here:
https://jobs.union-investment.de/index.php?ac=jobad&id=15971

**Comment by MartaPintoTeixeira** [comment]
Published in figma.
Docs updated.
Template updated.
