### ISSUE TITLE
discuss: variant names in sd-badge

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#1545]
## Problem:
In the docs, it says that the success and error variants don't imply any semantic meaning. They kinda do because they tell me that something good, bad, or neutral is going on. [...]

**Discussion so far:**
> @coraliefeil 
> The color of sd-badge should not tell that sth good, bad or neutral is going on. 
> Plattforms can simply decide which color they would like to use depending on how important a badge should appear.
> 
> (See reference https://atlassian.design/components/badge/examples, https://m3.material.io/components/badges/overview
> 
> Only sd-status-badge is communicating a certain meaning.

> matuzo
> Okay but the values of the variant attribute (error and success) and the associated colors imply meaning.

## Idea/approach/suggestion
We need to rename the variants with a more generic/semantic value in order to keep the colors flexible (sikinning) but remove the semantic meaning.

**Comment by coraliefeil** [comment]
@smfonseca is this still an issue or didn’t we solve this already when fixing the a11y issue in sd-badge?

**Comment by smfonseca** [comment]
@coraliefeil the variants still need to be renamed and there is a [ticket](https://github.com/solid-design-system/solid/issues/1593) that I created when we had our discussion.

**Comment by karlbaumhauer** [comment]
> @coraliefeil the variants still need to be renamed and there is a [ticket](https://github.com/solid-design-system/solid/issues/1593) that I created when we had our discussion. @karlbaumhauer I guess this ticket is not needed since we already have another.

your right. I close this issue as the topic is covered in #1593
