### ISSUE TITLE
feat[design]: ✨ concept release notes

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1552]
## Description
This tasks describes the Figma implementation for: #1135 

Brainstorming:
- [x] -  Research for release notes in other systems
- [x] -  keep in mind: keep changelog 
- [x] - find other examples and best practices
- [x] -  how can we communicate cool things we publish?
- [ ] -  demo videos?
- ...

### Open Questions towards development
- [ ] Question1
- [ ] Question2

## DoR
- [x] Item has been estimated by the team
- [ ] Item dependencies have been identified and documented

## DoD
- [ ] Brand approval (if neccessary)
- [ ] Figma documentation file incl. hand-off has been created/updated (if applicable)
- [ ] Tokens have been applied/updated (if applicable)
- [ ] Crosslinks are created/updated
- [ ] Implementation works successfully on `figma` branch

**Comment by MartaPintoTeixeira** [comment]
For the template instead of:
"Map Maker with Images"
Lets have:
"Map Maker with Image"

**Comment by MartaPintoTeixeira** [comment]
@coraliefeil please have a look at the figma file I shared with you. I have polished the concept page and would like your feedback. Thanks

**Comment by MartaPintoTeixeira** [comment]
I am closing this ticket as "done" as the concept release notes have been created.

Whats next?
Wait for @yoezlem okay to proceed with changes + align with dev + publish when ready.
