### ISSUE TITLE
chore: 🔧 update GitHub template to ask for reproduction

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#1561]
## User Story
As a maintainer of the Solid Design System, I would like to see a reproduction of the issue, so that I don't have to do everything on my own and to give the possibility to narrow the issue down to our components and not to other things happening.

### Suggested Solution
Ask for Codepen for basic HTML issues and for Stackblitz or similar for things that make problems in the context of frameworks. 

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
@karlbaumhauer Maybe you could take this one over?

**Comment by karlbaumhauer** [comment]
sounds good. 
just for clarification. This is about adding the part into our bug-teamplates right?
