### ISSUE TITLE
fix: 🤔 disabled icon color correction for sd-input

### ISSUE THREAD

**Issue by MartaPintoTeixeira** [solid-design-system/solid#1602]
## Current behavior
disabled icon color correction for sd-input
![Image](https://github.com/user-attachments/assets/80b90042-d3fd-4302-b7d9-bf13efb7bc26)

currently is: neutral-400 in figma

## Expected behavior
Disabled icons should be neutral-500.

## Steps to reproduce
1. Check figma and storybook.

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by coraliefeil** [comment]
Checked: No issues on code side.
I’ve fixed the issue in figma in will publish the comp.
