### ISSUE TITLE
docs: 📚 Update general accessibility docs

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#1692]
## Description

Figma and Storybook docs should be in sync and display latest information.

We should get rid of outdated information like "new" green accent color. 

We should look through the 2 pages and consolidate/update them.

New proposal: https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/branch/KhDN1hkdSIozSmgDDofFPZ/Solid-DS-%E2%80%93-Component-Library?node-id=29-75&node-type=canvas&t=O2lXLkSjvxXVa3Dy-0

## Where to put the documentation

[Figma](https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-%E2%80%93-Component-Library?node-id=5101-25917&node-type=frame&t=uG8nAsmSY6Uku1Cp-11)
[Storybook](https://solid-design-system.fe.union-investment.de/docs/?path=/docs/docs-general-accessibility--docs)

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Implementation works successfully on `feature` branch

**Comment by MartaPintoTeixeira** [comment]
@solid-design-system/development Hi Dev team, I need your review on this ticket please.
Please open this link: https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/branch/KhDN1hkdSIozSmgDDofFPZ/Solid-DS-%E2%80%93-Component-Library?node-id=29-75&node-type=canvas&t=O2lXLkSjvxXVa3Dy-0
You will find 3 pages next to each other:
before: what we have in figma for accessibility
proposal: the new proposal that is a bridge from dev + design + new content
storybook: what you have in storybook for accessibility.

Please give me your okay to publish this.

**Comment by karlbaumhauer** [comment]
@MartaPintoTeixeira I left a comment in Figma. Other than that, it looks nice. 

I would now combine the Figma and Storybook pages to align on the content.

**Comment by smfonseca** [comment]
@MartaPintoTeixeira just left you a remark regarding alt texts, other than that looks good from my side 👍

**Comment by MartaPintoTeixeira** [comment]
Ticket is done from Design side.
A new ticket has been created to sync Storybook with the new accessibility notes.
docs: 📚 Update general accessibility docs in storybook
[#1737](https://github.com/solid-design-system/solid/issues/1737)
