### ISSUE TITLE
ci: 👷 fix tests on GitHub

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#175]
It seems like the container containing the playwright environment might be tool slow or whatever. It worked flawless some weeks ago...

Two ways:
1. finding other ways then `fixture` or adding something like await shadowDom or similar...
2. improving the envorinment in the GitHub action

If we go the latter way, task would be to rewrite every test which contains fixture that it waits at least for the shadowRoot or even to querySelect stuff inside.

**Comment by mariohamann** [comment]
I had the same problem in my Mouseless-Stories.

I resolved it like that:
```js
import { waitUntil } from '@open-wc/testing-helpers';

// ...

await waitUntil(() => el?.shadowRoot?.querySelector('header'));
```

**Comment by Vahid1919** [comment]
> If we go the latter way, task would be to rewrite every test which contains fixture that it waits at least for the shadowRoot or even to querySelect stuff inside.

@mariohamann Is this referring to the second option of "improving the environment in the GitHub action" or the first one? I was unsure because you called it latter, but the instructions sounded like the steps for the first option.

**Comment by mariohamann** [comment]
We improve the tests on GitHub by improving the tests. :D (For the latter my though was something like a non Docker-environment or even paying for better machines or whatever.)
