### ISSUE TITLE
feat: ✨ add sd-radio-button-group

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#216]
## User Story
As a user of the Solid Design System, I need a Radio Button component that allows me to create button groups where only one button can be selected at a time. Additionally, I should have the option to display labels for each radio button in the group.

## API
https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=401-2292&mode=design

## Documentation
https://www.figma.com/file/T3mpP0ROquh93IDTqfFScU/Radio-Button-Group?type=design&node-id=0-1&mode=design

## Hand-off
https://www.figma.com/file/T3mpP0ROquh93IDTqfFScU/Radio-Button-Group?type=design&node-id=6-4&mode=design&t=ZUN1NQhEvk0PbgKZ-0

### Components detailed requirements
- [ ] Props, CSS-Properties, Parts & Slots
  - [ ] Capability to create exclusive button groups where only one button can be selected.
  - [ ] Option to display labels for each radio button.
- [ ] Stories
  - [ ] TBD

## DoR (Definition of Ready)
- [x] This user story provides value to the product.
- [x] The development team has estimated this user story.
- [x] The user story is clear and well-defined.
- [x] Any dependencies related to this user story have been identified.

## DoD (Definition of Done)
- [x] Documentation for the Radio Button component has been created or updated if applicable.
- [x] A migration guide is available or updated if applicable.
- [x] Relevant end-to-end tests for features, accessibility, and bug fixes are created or updated.
- [x] Relevant stories for features and accessibility are created or updated.
- [ ] Implementation successfully works on the `feature` branch.

**Comment by coraliefeil** [comment]
Can be discussed in next refinement.

**Comment by yoezlem** [comment]
@karlbaumhauer #12 is blocked by #216

**Comment by karlbaumhauer** [comment]
so what exactly is the blocking element / task here?
