### ISSUE TITLE
feat: ✨ add sd-dialog

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#229]
## Description
A dialog appears over other content. It requires an interaction from the user before they can return to whatever is underneath. 

## Documentation
https://www.figma.com/file/WwLYG6UHIUUGGKa59tjGhJ/sd-dialog-V.1.0.0?type=design&node-id=11404-3459&mode=design&t=cmZ7ws0b1ugnBTsn-4
## Hand-off
https://www.figma.com/file/WwLYG6UHIUUGGKa59tjGhJ/sd-dialog-V.1.0.0?type=design&node-id=15256-2501&mode=design&t=cmZ7ws0b1ugnBTsn-4

#### Props
| Status | Name | Type | Default | Description |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <ul><li>[x] </li></ul>  | `no-close-button` | `boolean` | `false` | removes to close button from the top right => close option (e.g. cancle button) needs to be added into the slot |
| <ul><li>[x] </li></ul>  | `headline` | `string` | '' | to be used for simple text content - rename from shoelace `label` and adopt description |
| <ul><li>[x] </li></ul>  | `noHeader` | N/A | N/A | Remove from component |
| <ul><li>[x] </li></ul>  | `open` | `boolean` | `false` | opens up the dialog |

 - [x] The dialog always has a dark background

#### CSS-Properties
  - [x] `--width` - offers a possibility to set a "responsive" width of the dialog window
  - [x] remove all other properties
#### Parts (besides the shoelace parts)
- [x] `background` - Offers the possibility to change the dark background (`overlay` part already exists)
#### Slots
  - [x] `headline` - used for complex content - rename from shoelace `label` and adopt description | NOTE: its a nested component in Figma
  - [x] `default` - the components content area
  - [x] `footer` - A footer section to add additional elements eg. buttons
  - [x] remove all other slots
#### Stories (besides the `default` story)
  - [x] no-close-button
  - [ ] headline - shows complex headline content => DEV-only
  - [x] scrolling - shows longer content (default slot) and the scrollbar inside the dialog
#### Samples
  - [ ] `default footer` - sample that shows the button in the footer
  - [x] `extended footer` - sample that shows button group with secondary + primary button to show that people should not used the same button variant
  - [x] `small headline` - sample that shows smaller headline sizes (using `<span>` not H2, H3, etc.)
  - [x] `no close button` - sample showing "no-close-button" - closing the dialog using a button in the footer
  - [x] `prevent-closing` - sample showing how to prevent a dialog being closed by clicking on the background

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [x] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

## Annotations
Height is flexible according to dialog content. 
Width is to be set via `--width` CSS-property

https://shoelace.style/components/dialog

Compare with current shoelace version on GitHub => our shoelace component is outdated => make sure we update it if needed.

**Comment by van-nguyen-ht** [comment]
Hello @mariohamann 
Here's the [Figma draft](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/WwLYG6UHIUUGGKa59tjGhJ/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=1559-17254&mode=design&t=B4y4BYHLROHBq3bi-11) :)

**Comment by karlbaumhauer** [comment]
Waiting for Design adoptions =>

**Comment by karlbaumhauer** [comment]
blocked by #560
