### ISSUE TITLE
feat: ✨ add sd-carousel

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#239]
## API
[Figma Component](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=3291-20872&mode=design&t=kJ8QONCzBaLeN7St-11)
[Figma Documentation](https://www.figma.com/file/F856KwF4q6ksLJzwj0tW56/Carousel?type=design&node-id=971-4578&mode=design&t=0x3lZ9VzypBJBqG5-11)

## Handoff
Figma Hand-off [https://www.figma.com/file/F856KwF4q6ksLJzwj0tW56/Carousel?type=design&node-id=6-4&mode=design](url)

## Dev Info

We take this as our base: https://shoelace.style/components/carousel
Please copy carousel and carousel-item from here: https://github.com/shoelace-style/shoelace/tree/next/src/components

- [x]   Step 1: Convert current styles to TailwindCSS.
- [x] Step 2: Adapt API and Styles to our needs
  - [x] We still need slides per page, don't remove it, even if it's not documented in Figma.
  - [x] Default `variant` will be `numbers`, it can be changed to `dots` (different to design default in Figma)
  - [x] I'm questioning that the arrows are hidden on smaller sizes. I think we should clarify that. => clarified in the refinement: never remove the arrows as this might lead to very bad UX (not usable anymore)
  - [x] `vertical` is not provided.
  - [x] `--aspect-ratio` is not provide.
- [x] Step 3: Write stories for all the different props etc.
- [x] Step 4: Write migration guide for sd-slider: Yes, this carousel will have less options, as we don't use a third-party-lib anymore... if people need more options, they have to build theirselves.

**Comment by coraliefeil** [comment]
Autoplay - if we don’t allow it we are fine. If it can be switched on, we need to provide a pause button due to A11.

**Comment by coraliefeil** [comment]
@mariohamann if there are focusable areas for screen readers we could leave out arrow buttons on mobile and only use pager dots / paging as swipe indicator. Therefore distinguishing between desktop and mobile would be neccessary.

**Comment by coraliefeil** [comment]
I replaced the chevron icons used as base components in the figma comp by tertiary icon button.
To look exactly the same, padding had to be adjusted. 
[Figma Branch](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/NFt4ryYNtAXLpJ0yixEow9/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=3291-20820&mode=design&t=ivo0ANiR99PD3zar-11)
If this is fine and we have an agreement on chevron button on mobile or not  we’ll update the handover.

**Comment by van-nguyen-ht** [comment]
@Vahid1919 Hey Vahid I've updated the documentation [here](https://www.figma.com/file/F856KwF4q6ksLJzwj0tW56/Carousel?type=design&node-id=971-14325&mode=design&t=Wzq27N1INYqXkMRe-11)

**Comment by Vahid1919** [comment]
Hey @coraliefeil!  Mario and I discussed that it could be helpful to have active states for the navigation buttons, which currently don't have one. Is it something that can be provided?

**Comment by mariohamann** [comment]
Just in addition: In the sd-interactive we reused the styles of the sd-button, but for the inverted state they conflict with those provided in the carousel.

**Comment by coraliefeil** [comment]
sd-interactive has no background .. therefore it has the same stylings as the icon in sd-link.

I don’t see atm why we would need an active state ... do you have an example?

**Comment by mariohamann** [comment]
Ah, it was just about the active state while clicking on the element – but sure, we can copy from `sd-link`, forgot that – I used `sd-button` as a base, but `sd-link` makes a lot more sense.

**Comment by coraliefeil** [comment]
review done. adjust sd-interactive - hover color inverted to primary-200 ... then it’s all good.
