### ISSUE TITLE
docs: 📚 fix Storybook on Safari

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#249]
https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/components-sd-accordion--docs

![CleanShot 2023-07-21 at 13 27 52@2x](https://github.com/solid-design-system/solid/assets/26542182/1e2a8035-99ed-400b-9205-728957024627)

Problem: Safari doesn't support negative lookbehind in Regex. `html-formatter` uses lots of negative lookbehnds – and therefore breaks the docs.

Solution: different package or no optimized HTML. Or we make an exception for Safari, so all browsers get the nice code, Safari not the best (and maybe even a hint, that it might look better in other browsers.)

**Comment by karlbaumhauer** [comment]
@mariohamann pls check if still existing

**Comment by karlbaumhauer** [comment]
not relevant anymore
