### ISSUE TITLE
feat: ✨ add sd-textarea

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#256]
## User Story
As a user of the Solid Design System, I require the `sd-textarea` component to facilitate the input of multiline text. This component should offer the following functionalities:

- [x] Allow hiding the default label for enhanced user experience.
- [x] Provide the option to display additional hints for guidance.
- [x] Automatically add an asterisk (*) to the label for mandatory fields to indicate their importance.

This way, I can create forms and input fields that are both user-friendly and flexible in accommodating various input scenarios.

## API
https://www.figma.com/file/07Bzd23A0QSrSWiXy6w2uM/Text-Area?node-id=1010%3A1736&mode=dev

## Hand-off
https://www.figma.com/file/07Bzd23A0QSrSWiXy6w2uM/Text-Area?node-id=6%3A4&mode=dev

### Components detailed requirements
- [ ] Props, CSS-Properties, Parts & Slots
  - [ ] Implement props for configuring the behavior of `sd-textarea` components, such as label, hint, and mandatory field indicators.
  - [ ] Define CSS properties to enable customization of the component's styling, including typography, colors, and layout.
  - [ ] Specify available parts and slots for advanced customization, such as custom labels or additional content.

- [ ] Stories
  - [ ] Create usage examples and stories demonstrating how to effectively use `sd-textarea` components.
  - [ ] Include scenarios showcasing the component's versatility for different form designs and input requirements.

## DoR
- [x] The `sd-textarea` component adds significant value to the user experience, especially in form inputs.
- [x] The team has provided an accurate estimate of the effort required for implementation.
- [x] The requirements for the component are well-defined and unambiguous.
- [x] Dependencies related to the `sd-textarea` component have been identified.

## DoD
- [ ] Documentation has been created or updated to guide users on effectively using `sd-textarea` components.
- [ ] A migration guide has been created or updated if applicable.
- [ ] Comprehensive end-to-end tests, including features and accessibility, have been developed and updated as needed.
- [ ] Relevant user stories, including various use cases and form designs, have been created or updated.
- [ ] The implementation of `sd-textarea` components functions successfully and meets the acceptance criteria on the `feature` branch.

**Comment by yoezlem** [comment]
It would make sense to have the sd-input first, so we can use the state for the sd-textarea.

**Comment by saemik94** [comment]
As discussed in the Daily (13.11), the icons are dealt with in a separate ticket and are no longer part of this ticket.
https://github.com/solid-design-system/figma/issues/157
