### ISSUE TITLE
feat: ✨ add sd-checkbox & sd-checkbox-group

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#257]
## User Story
As a user of the Solid Design System, I want to use a checkbox component with various features and styling options, so that I can create intuitive and customizable form elements that enhance the user experience.

### API
https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=88-1057&mode=design
### Hand-off
https://www.figma.com/file/Q7E9GTBET7Gs2HyH1kbpu5/Checkbox-%2F-Checkbox-Group?type=design&node-id=6-4&mode=design
### Documentation
https://www.figma.com/file/Q7E9GTBET7Gs2HyH1kbpu5/Checkbox-%2F-Checkbox-Group?type=design&node-id=0-1&mode=design

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [x] Documentation has been created/updated (if applicable)
- [x] Migration Guide has been created/updated (if applicable)
- [x] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [x] Relevant stories (Features, A11y) are created/updated
- [x] Implementation works successfully on `feature` branch

**Comment by karlbaumhauer** [comment]
@mariohamann pls specify the `required` prop and behavior

**Comment by coraliefeil** [comment]
prop name should be "error-text"

**Comment by karlbaumhauer** [comment]
result from the pre-refinement:
- hints will be renamed to `help-text`
- `error-text` will show up (additionally) below the input field => watch out for a11y (https://shoelace.style/getting-started/form-controls#inline-form-validation)
- `success-text` will be removed

needs to be replaced in this ticket, #255, #12 & #216 => also in all respective figma issues.

**Comment by abudd1094** [comment]
![image](https://github.com/solid-design-system/solid/assets/39494579/c4f60052-afda-4aeb-bf0b-51f2aba63fe1)
from #255 (:

**Comment by karlbaumhauer** [comment]
> ![image](https://user-images.githubusercontent.com/39494579/277967633-c4f60052-afda-4aeb-bf0b-51f2aba63fe1.png) from #255 (:

yeah... I know... we had a nice back and forth on this but finally (fingers crossed) agreed on this now.
