### ISSUE TITLE
feat: ✨ add  sd-select

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#258]
## User Story
As a user of the Solid Design System, I require the `sd-select` component to facilitate the selection of items from a dropdown menu. This component should provide the following functionalities:

It will work like an original `<input type="select">`:

```
<sd-select label="Select one">
  <sd-option value="option-1">Option 1</sd-option>
  <sd-option value="option-2">Option 2</sl-option>
  <sd-option value="option-3">Option 3</sd-option>
</sl-select>
```

- [x] Display a dropdown menu containing a list of choices when clicked.
- [x] Keep the dropdown menu open until a menu item is selected or the user clicks outside of it.
- [x] In the `multiple` variant it should stay open until outside click
- [x] Allow hiding the default label for improved aesthetics.
- [x] Provide the option to display an additional hint for user guidance.
- [x] Automatically add a blank & an asterisk (*) to the label for mandatory fields to indicate their importance.
- [x] It should support multiple select like here: https://shoelace.style/components/select#multiple
- [x] In multiple select we could try to re-use the `sd-tag` and just override rectangle, as this could fit to the design: https://www.figma.com/file/ZphyVFsUHL72voMrJagMeo/Select?type=design&node-id=1013-8030&mode=design&t=8uInNVKl2s9IQzhf-0

By implementing these features, I can create user-friendly forms and interfaces that enable users to make selections efficiently, enhancing the overall usability of the system.

## Open questions
- [ ] can we use `sd-dropdown` for the select wrapper? Especially in terms of outline, sizes and status colors

## API

From design the following props are defined:

https://www.figma.com/file/ZphyVFsUHL72voMrJagMeo/Select?node-id=1002%3A2284&mode=dev

Besides those design related props we should add technical props of Shoelace: https://shoelace.style/components/select

## Hand-off
https://www.figma.com/file/ZphyVFsUHL72voMrJagMeo/Select?node-id=6%3A4&mode=dev

## Technical Information
Pls try to re-use the styles from #257 if possible.

### Components detailed requirements

We're building on https://github.com/solid-design-system/solid/blob/main/packages/components/src/_components/select/select.ts

We need `sd-select` and `sd-option`.
- [ ] Props, CSS-Properties, Parts & Slots
  - [ ] Implement props for configuring the behavior of `sd-select` components, such as label, hint, and mandatory field indicators.
  - [ ] Define CSS properties to allow customization of the component's appearance, including dropdown menu style and layout.
  - [ ] Specify available parts and slots for advanced customization, such as custom labels or additional content.
- [ ] Stories
  - [ ] Create usage examples and stories demonstrating how to effectively use `sd-select` components.
  - [ ] Include scenarios showcasing the component's versatility for different selection requirements and form designs.

**_In case of doubts, pls reach out to the team to clarify the component API._**

## DoR
- [x] The `sd-select` component enhances the user experience by simplifying item selection through a user-friendly dropdown menu.
- [x] The team has provided an accurate estimate of the effort required for implementation.
- [x] The requirements for the component are well-defined and unambiguous.
- [x] Dependencies related to the `sd-select` component have been identified.

## DoD
- [ ] Documentation has been created or updated to guide users on effectively using `sd-select` components.
- [ ] A migration guide has been created or updated if applicable.
- [ ] Comprehensive end-to-end tests for item selection functionality and accessibility have been developed and updated as needed.
- [ ] Relevant user stories, including various item selection scenarios, have been created or updated.
- [ ] The implementation of `sd-select` components functions successfully and meets the acceptance criteria on the `feature` branch.

--------------------------------------------------------------------------------------------------------------------------------

Additional Info from @abudd1094 

## Resources
[WIP Figma Branch](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/YOAYmWoCPqJAmqggvTFquY/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=197-1968&mode=design&t=c4HkwfI9Ot8u7uhX-0)

**Comment by karlbaumhauer** [comment]
includes #335

**Comment by yoezlem** [comment]
It would make sense to have the sd-checkbox first (so we can grab the styles from that).

**Comment by karlbaumhauer** [comment]
blocked by #257

**Comment by karlbaumhauer** [comment]
@mariohamann pls have a look into this ticket. The description looks old and might lead to too many questions for the new devs starting next week.

**Comment by abudd1094** [comment]
I'm going to start documenting problems in this comment as I go so they don't get lost.  
I will add to it over time so we have a clear overview when it comes time to review.

#Borders:
Figma specifies a border for the input which is rounded when closed and flush (not rounded on bottom) with the dropdown when it is open:
![Image](https://github.com/solid-design-system/solid/assets/39494579/1463d6f9-cfd2-4849-b2c7-0a41cc107c0a)

This becomes problematic when the dropdown is forced to open either above or on top of the element based on visibility (sd-popup utility uses a reposition method to forcibly keep the dropdown visible regardless of the "placement" attribute):
![Image](https://github.com/solid-design-system/solid/assets/39494579/1d1c37b3-d7e5-4e0a-a365-048e2f2a8ec1)
![Image](https://github.com/solid-design-system/solid/assets/39494579/92945991-1bec-459c-9245-b62c4c201425)

Shoelace does not apply thick borders with varying radius values.  It opts for a simpler presentation.
![Image](https://github.com/solid-design-system/solid/assets/39494579/6f305c51-f1b2-4ee5-982e-471f20c6d39d)

**Comment by mariohamann** [comment]
What do you think about setting a mutation observer on `data-current-placement` to adapt the roundedness accordingly?

**Comment by abudd1094** [comment]
@mariohamann nice, that was the attribute I was looking for.  Added a debounced mutation observer in sd-popup that fires an event "sd-current-placement", works well:
![image](https://github.com/solid-design-system/solid/assets/39494579/3a74b20b-5c80-4483-9dd1-ad6b6c12da00)

**Comment by abudd1094** [comment]
For the future, stuff like this would be really great to include in the ticket:

![Image](https://github.com/solid-design-system/solid/assets/39494579/d89b1496-c4af-46e0-a92c-f2387ed61607)

Extra work could have been avoided with a sentence.  Furthermore, not including old documentation.  The API linked above was more misleading than helpful.
