### ISSUE TITLE
feat: ✨ add sd-container - CSS style

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#271]
## Description
As a user of the Solid Design System, I would like to utilize `sd-container`, so that I can structure content on the page.

## API
[Figma Link](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=1664-15968&mode=design)

## Documentation
[Figma Link](https://www.figma.com/file/ffdz9zO1CISlr8aHCZ7Bzp/Container?type=design&node-id=1001-3239&mode=design&t=Uq3OmZrR6FzL3iHN-11)

## Hand-off
[Figma Link](https://www.figma.com/file/ffdz9zO1CISlr8aHCZ7Bzp/Container?type=design&node-id=6-4&mode=design)

#### Classes
| Status | Name | Type | Default | Description |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <ul><li>[ ] </li></ul>  | `--variant-` | `neutral-100` / `primary-100` / `primary` / `border-neutral-400` / `white` | `neutral-100` | defines the background color and border of the container |
| <ul><li>[ ] </li></ul>  | `--padding-` | `sm` / `lg` | `lg` | defines the padding of the container to be used on smaller component widths |

#### Stories (besides the `default` story)
  - [ ] `variant` (white container on primary background)
  - [ ] `default-padding` (shows the different paddings)
  - [x] `custom-padding` (shows how to override padding)

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Changes have been pushed and reviewed
- [ ] Documentation has been created/updated
- [ ] Migration Guide has been created/updated
- [ ] Implementation works successfully on `feature` branch
- [ ] Automatic tests have passed on `feature` branch
- [ ] Accessibility has been approved on `feature` branch
- [ ] Changes have been merged (`feature` branch has been deleted)
- [ ] Automatic tests have passed on `main` branch
- [ ] Accessibility has been approved on `main` branch

**Comment by Vahid1919** [comment]
@solid-design-system/development Moving this conversation from teams...

I am having some doubts on the sd-container--padding-sm attribute? 
 
From what I understand, the idea was to adapt the container to smaller screens. From a technical point of view, this can easily be done as a media query (eg: `sm:..`) Given that, is there another reason we want to use attributes here?

**Comment by karlbaumhauer** [comment]
> @solid-design-system/development Moving this conversation from teams...
> 
> I am having some doubts on the sd-container--padding-sm attribute?
> 
> From what I understand, the idea was to adapt the container to smaller screens. From a technical point of view, this can easily be done as a media query (eg: `sm:..`) Given that, is there another reason we want to use attributes here?

I will try... ;-) 
So there are 2 different paddings which should be used. `lg` for bigger component widths and `sm` for smaller use cases of the component. The 2 values of the property should provide more or less all the user needs/is supposed to use without adding any additional code. 

The media-query which should be used in the `custom-padding` story is supposed to show how it should be done, in case someone needs something completely different.

@mariohamann pls correct if I am wrong.

**Comment by Vahid1919** [comment]
> I will try... ;-) So there are 2 different paddings which should be used. `lg` for bigger component widths and `sm` for smaller use cases of the component. The 2 values of the property should provide more or less all the user needs/is supposed to use without adding any additional code.
> 
> The media-query which should be used in the `custom-padding` story is supposed to show how it should be done, in case someone needs something completely different.
> 
> @mariohamann pls correct if I am wrong.

Hmm...so with the media queries, lg would be the default (which we already decided), and it would automatically change to sm for smaller screens with no additional configuration. Then we could have `custom-padding` if the developer wants to add something different. That seemed cleaner from my point of view. But I am open to your ideas as well.
