### ISSUE TITLE
feat: ✨ add sd-chip (CSS style component)

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#272]
## User Story
As a user of the Solid Design System, I would like to have a `sd-chip` component, a small, non-interactive label that represents a status, property, or other metadata

## Hand-off
https://www.figma.com/file/IUiRoK2jiW8ydM77uiY2RX/Chip?type=design&node-id=1103-913&mode=design&t=9jVZgnCcpvwX9rLA-4
## Documentation
https://www.figma.com/file/IUiRoK2jiW8ydM77uiY2RX/Chip?type=design&node-id=804-717&mode=design&t=9jVZgnCcpvwX9rLA-4

#### Props
| Status | Name | Type | Default | Description |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <ul><li>[ ] </li></ul>  | `--variant-` | `white` / `primary--200` / `primary--300` / `primary--500` | `primary--200` | defines the background color |

#### Stories (besides the `default` story)
  - [x] variant (shows different color variants and in which combination it should be used)

#### Samples
- ~~A sample that shows and highlights the difference between `sd-flag` & `sd-chip` => import from #275~~

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [x] Documentation has been created/updated (if applicable)
- [x] Relevant stories (Features, A11y) are created/updated
- [x] Implementation works successfully on `feature` branch

**Comment by karlbaumhauer** [comment]
@mariohamann maybe you can prefill some information here. Fine tuning will be done by me.

**Comment by karlbaumhauer** [comment]
Blocked by #595

**Comment by saemik94** [comment]
Samples will be provided by the sd-flag story.
