### ISSUE TITLE
feat: ✨ add sd-media + sd-copyright - CSS style

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#276]
## User Story
As a user of the Solid Design System, I would like to utilize a style component to preview an image or a video with an optional caption and copyright, so that media content can be displayed semantically correct and accessible.
## Documentation
https://www.figma.com/file/EYUUCI9hFhfxKB5zn3jpju/Media?type=design&node-id=1705-4634&mode=design&t=HA8PYxdKVbxgblUJ-4

### Copyright

![CleanShot 2024-02-09 at 11 07 32](https://github.com/solid-design-system/solid/assets/26542182/94f4317b-7128-41f3-9cbb-c39b0c852bb4)

https://www.figma.com/file/8u2hIRmhVX3mjW8462Au5I/Image?type=design&node-id=1705-4634&mode=design&t=hDEWaIwPrHkdNn0M-11

### Description

![CleanShot 2024-02-09 at 11 08 31](https://github.com/solid-design-system/solid/assets/26542182/9ee2dd6b-95f5-40d7-8a39-ac698cde5ee8)

>Note: 
The Figma component needs to be adjusted as well => not blocking and can be done in parallel 

## Technical Hint

To force best semantics, we will utilize figure and figcaption:

```html
<figure class="sd-media">
      <img src="https://image.url">
    <figcaption>
      This is a media caption
    </figcaption>
  </figure>
```

https://codepen.io/mariohamann/pen/LYaJJJN

For ease of use, we will use a CSS custom property for copyrights:

```html
<div class="sd-copyright" style="--copyright: '© 2024 Solid Design System';">
      <img src="https://image.url">
</div>
```

Combined this should result in the following prototype:

![CleanShot 2024-02-09 at 11 18 54](https://github.com/solid-design-system/solid/assets/26542182/fc691ddf-b5ba-432b-86af-50c4809bb735)

https://codepen.io/mariohamann/pen/LYaJJJN

Have in mind, that it has to be ensured, that the copyright has to be able to be multilined depending on the width of its container.

## Hand-off
https://www.figma.com/file/EYUUCI9hFhfxKB5zn3jpju/Media?type=design&node-id=1503-4722&mode=design&t=HA8PYxdKVbxgblUJ-4

#### Props
| Status | Name | Type | Default | Description |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <ul><li>[ ] </li></ul>  | `--copyright` | `CSS Variable` | `false` | displaying the copyright (always in the bottom left corner |

#### Stories (besides the `default` story)
  - [ ] `Copyright and caption` - showing both additional content sections

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [x] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by karlbaumhauer** [comment]
result from pre-refinement:
`sd-image` only needed in Figma (design helper component) => pattern in Storybook to show a11y requirements

**Comment by coraliefeil** [comment]
Can we sort out sd-video, sd-media, sd-image together in next week’s pre-refinement or do we need to schedule another meeting? @karlbaumhauer 

FYI @EllaELSA

**Comment by karlbaumhauer** [comment]
> Can we sort out sd-video, sd-media, sd-image together in next week’s pre-refinement or do we need to schedule another meeting? [@karlbaumhauer](https://github.com/karlbaumhauer)
> 
> FYI [@EllaELSA](https://github.com/EllaELSA)

changed the prio to urgent and moved it into pre-refinement. Maybe only clarify the scope of this component and postponing the real pre-refinement to one week later. Therewith we (@mariohamann) could add some details in between.

**Comment by yoezlem** [comment]
We have two options for building the component. 

1. The first option is to create a 'sd-image' component. 
2. The second option is to use a CSS class with 'sd-image' and this would involve with before/after pseudo-elements.

My suggestion would be to write the user story at this point only after we determine which of the two options we are considering. The task here is to first test which option is suitable for us.
@mariohamann @karlbaumhauer

**Comment by karlbaumhauer** [comment]
blocked by #728
