### ISSUE TITLE
feat: ✨ add sd-notification

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#277]
## Description
As a user of the Solid Design System, I would like to have a notification component, providing screen notifications which are displayed either `inline` (inside the pages content) or `toasted` (somewhere on the page above all other content) and can be closed manually or disappear automatically after a certain time, so that important information can be provided to the end-user.

Through this component, 2 different toast-stacks will be provided to organize the layout of multiple toast messages. On the top right and the bottom center. Each `sd-notification` will be assigned to the top right toast-stack by default.

## API
[Figma Master Component](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/eK808lqsVkFESZ29C3jjsX/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=5177-28280&mode=design&t=OGRMRfDYR9b6PlrY-11)
[Component API](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/eK808lqsVkFESZ29C3jjsX/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=12433-4240&mode=design&t=OGRMRfDYR9b6PlrY-11)
## Hand-off
[Specs](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/eK808lqsVkFESZ29C3jjsX/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=12438-8107&mode=design&t=OGRMRfDYR9b6PlrY-11)

#### Props
| Status | Name | Type | Default | Description |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <ul><li>[x] </li></ul>  | `closable` | `boolean` | `false` | adds a close button on the top right |
| <ul><li>[x] </li></ul>  | `closed` | `boolean` | `false` | possibility to open an existing notification item (naming caused by default needs to be false) |
| <ul><li>[x] </li></ul>  | `duration-indicator` | `boolean` | `false` |  shows a growing line on the bottom to indicate the time to disappear |
| <ul><li>[x] </li></ul>  | `duration` | `number` | `infinite` | specifies the time, after which the notification automatically disappears |
| <ul><li>[x] </li></ul>  | `toast-stack` | `top-right` / `bottom-center` | `top-right` | defines the toast-stack in which the notification is displayed |
| <ul><li>[x] </li></ul>  | `variant` | `info` / `success` / `error` / `warning` | `info` | defines the icon and color of the left notification part |

#### Parts
  - [x] use defaults from shoelace
#### Slots
  - [x] `default` - main slot where users can add either text and/or another component (eg. Button)
  - [x] `icon` - offers the possibility to set different icons fore each variant
#### Stories (besides the `default` story)
  - [x] Closable & Variant
  - [x] Toast-stack (only without `duration`)

### Additional Information for the docs
- [x] allowed combinations (regarding A11y) need to be defined and **aligned with Figma** while implementing

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Changes have been pushed and reviewed
- [ ] Documentation has been created/updated
- [ ] Migration Guide has been created/updated
- [ ] Implementation works successfully on `feature` branch
- [ ] Automatic tests have passed on `feature` branch
- [x] Accessibility has been approved on `feature` branch
- [ ] Changes have been merged (`feature` branch has been deleted)
- [ ] Automatic tests have passed on `main` branch
- [ ] Accessibility has been approved on `main` branch

**Comment by coraliefeil** [comment]
Figma Component has been adapted according to the standard slot concept and today's agreements listed in this issue. 

Links in description have been updated leading to figma branch.

**Comment by coraliefeil** [comment]
@Vahid1919 WRT max. / min. width for toasts 
Teams should be able to override the values.
You could set max-width: 320px and leave min-width: [empty]
