### ISSUE TITLE
feat: ✨ add sd-textarea

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#279]
### Components detailed requirements
- [ ] Props, CSS-Properties, Parts & Slots
  - [ ] ...
- [ ] Stories
  - [ ] ...

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item is achievable within a sprint
- [ ] Item is measurable and testable upon completion (Acceptance Criteria)
- [ ] Item dependencies have been identified

## DoD
- [ ] Changes have been pushed and reviewed
- [ ] Documentation has been created/updated
- [ ] Migration Guide has been created/updated
- [ ] Implementation works successfully on `feature` branch
- [ ] Automatic tests have passed on `feature` branch
- [ ] Accessibility has been approved on `feature` branch
- [ ] Changes have been merged (`feature` branch has been deleted)
- [ ] Automatic tests have passed on `main` branch
- [ ] Accessibility has been approved on `main` branch

**Comment by coraliefeil** [comment]
duplicate, closing this one
