### ISSUE TITLE
feat: ✨ add sd-video

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#281]
## Description
The `sd-video` component can be used to wrap external video elements (e. g. from Moving Image or bare `<video>`-Tags) and provide some basic styling for Union Investment. Developers should be able to wire it up with their video service as they need it (e. g. Moving Image), by setting the attributes they need in combination with events they are listening to.

<img width="700" alt="CleanShot 2023-08-28 at 15 44 54@2x" src="https://github.com/solid-design-system/solid/assets/26542182/6feb526b-31fa-4277-9f3c-775f968ccd9f">

Developers should be able to individually show the poster images (on video element) or overlay. When clicking on the play-button, everything should be hidden (ideally with a transition). Therefore overlay and play button should be in one single container which is hidden then.

The play button is the only element which always has to show up, if `playing` is false, as this is needed at least for a11y.

All logic concerning MovingImage, iFrame handling there etc. should stay in the CMS project. This makes it possible to not be restricted too MovingImage, or `<video>` but even could be used in combination wth other services. We would on top save a bunch JS only used for MovingImage... + the iFrame Service + Tracking Logic for Moving Image etc.

## API
https://www.figma.com/file/q8BLLhesaUN88yF46DGNDI/Video?type=design&node-id=536-7064&mode=design&t=aix2pvBggeAfJ8r5-4
needs Update from https://github.com/solid-design-system/figma/issues/125
## Hand-off
https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=2624-18899&mode=design&t=6KqICmYgdsyxxBIT-4
needs Update from https://github.com/solid-design-system/figma/issues/125
### Components detailed requirements
- [ ] Props, CSS-Properties, Parts & Slots
  - [x] @prop `playing` (hides everything when true)
  - [x] @prop `overlay` (show a darker overlay)
  - [x] @slot `play-icon` (to change the icon)
  - [x] @event `sd-play` (when play button is clicked → this should set `playing` to true and remove all buttons etc.)
  - [ ] @method `play()` (changes everything to start and stop the video and hides the overlay and button)
<del>- [ ] @slot `copyright` (**_not_** implemented as this will be part of the sd-media component)</del>
<del>- [ ] @slot/@prop `poster` => **_not_** implemented as this is part of the video itself (html video tag, MovingImage Video, etc.)</del>
- [ ] Samples
  - [ ] Poster (with logic in the play button to show poster handling in the html video element)
- [ ] Documentation => clarify in the description that we don't provide any video player but only the wrapper.

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item is achievable within a sprint
- [ ] Item is measurable and testable upon completion (Acceptance Criteria)
- [x] Item dependencies have been identified

## DoD
- [x] Changes have been pushed and reviewed
- [x] Documentation has been created/updated
- [x] Migration Guide has been created/updated
- [x] Implementation works successfully on `feature` branch
- [x] Automatic tests have passed on `feature` branch
- [x] Accessibility has been approved on `feature` branch
- [x] Changes have been merged (`feature` branch has been deleted)
- [ ] Automatic tests have passed on `main` branch
- [ ] Accessibility has been approved on `main` branch

**Comment by mariohamann** [comment]
I would like to reduce this component to only design-relevant parts we can influence.

<img width="699" alt="CleanShot 2023-08-28 at 15 43 19@2x" src="https://github.com/solid-design-system/solid/assets/26542182/e291954b-4885-4f25-8b53-a0d9e33ed4bf">

Everything we see here is not provided by us but by UI's video service. So we can omit that completely on dev side.

My proposal for the ticket would be:

# sd-video
## Description

The `sd-video` component can be used to wrap external video elements (e. g. from Moving Image or bare `<video>`-Tags) and provide some basic styling for Union Investment. Developers should be able to wire it up with their video service as they need it (e. g. Moving Image), by setting the attributes they need in combination with events they are listening to.

<img width="700" alt="CleanShot 2023-08-28 at 15 44 54@2x" src="https://github.com/solid-design-system/solid/assets/26542182/6feb526b-31fa-4277-9f3c-775f968ccd9f">

1. @prop `play` (hides play button and overlay if false)
2. @slot `play-icon` (to change the icon)
3. @prop `overlay` (show a darker overlay)
4. @slot `poster` (add an optional poster image)
5. @prop `poster` (shows the poster image)
7. @event `sd-play` (when play button is clicked → this should set `play` to false and remove all buttons etc.)

Developers should be able to indivudually show the poster images or overlay. When clicking on the play-button, everything should be hidden to false (ideally with a transition). Therefore overlay, poster and play should be in one single container which is hidden then. Developers could afterwards decide to e. g. only show the play button and the overlay, but not the poster image by setting poster to `false`, `play` to true and leave `overlay` as `true`.

The play button is the only element which always has to show up, if `play` is true, as this is needed at least for a11y.

---

I'm not sure, if I would make a click handler on the whole element or if people should just set this theirself like `<sd-video @click="() => handlePlay()">...</sd-video>`. This could help in regard of a11y, as we could set our focus-styles correctly on the play button.

An alternative would be to get the focus stuff down via CSS, like e. g.: `<button class="absolute w-full top-0 left-0 h-full group flex items-center justify-center"><sd-icon class="group-focus:focus-outline"><sd-icon>`

---

All logic concerning MovingImage, iFrame handling there etc. should stay in the CMS project. This makes it possible to not be restricted too MovingImage, or `<video>` but even could be used in combination wth other services. We would on top save a bunch JS only used for MovingImge...

**Comment by christophsaile** [comment]
@mariohamann I think the interface looks good. I like the approach of using the sd-video as a wrapper for styling because as you said otherwise you would have to add logic for different video services. Have you considered add a slot / prop for a copyright text?, that would also fall into basic styling imo

**Comment by mariohamann** [comment]
We will have an `sd-media` component (AFAIK), which would include a copyright text for either Video, Imagery or even Text.

So it would be something like:

```html
<sd-media>
  <sd-video><video></video></sd-video>
  <p slot="copyright">This is mine!!!</p>
</sd-media>
```

**Comment by karlbaumhauer** [comment]
>We will have an sd-media component (AFAIK), which would include a copyright text for either Video, Imagery or even Text.

Correct. just created an issue for it => #388

**Comment by karlbaumhauer** [comment]
@mariohamann concerning your proposal:
I like the wrapper idea. Keeps it clean and only adds stuff to the library, we actually are in control of. 

My questions so far are:
1. why is the `play` prop `false` when playing? Is this in terms of a11y? I would propose it the other way around... :/ or is this meant to be the prop to activate the play button?
2. can't we just have the `poster` slot as it would not show anything if its empty?

Other than that, I would move this into the refinement.

**Comment by karlbaumhauer** [comment]
edit from pre-refinement:
- leave out the poster => part of HTML video
- play => playing 
- samples: 1x event logic in combination with poster in HTML video

**Comment by karlbaumhauer** [comment]
updated description

**Comment by abudd1094** [comment]
@karlbaumhauer @mariohamann 

- What does the "overlay" look like?  Is this still relevant?  There is no clear example on Figma.
- @slot copyright is still isted in "Components detailed requirements", from contained discussion, we will NOT include copyright in this component and instead use the "sd-media" component as a wrapper?
- Should the "play icon" interact directly with the passed in video element and therefore mutate the public "playing" property when clicked?
- What is meant by:
![image](https://github.com/solid-design-system/solid/assets/39494579/e8604edf-c73b-469e-b73f-2add45004fd3)

**Comment by karlbaumhauer** [comment]
> @karlbaumhauer @mariohamann
> 
> * What does the "overlay" look like?  Is this still relevant?  There is no clear example on Figma.

@van-nguyen-ht https://github.com/solid-design-system/figma/issues/125 seems to be still open. As @abudd1094 is working on this task, can you somehow prioritize this?

> * @slot copyright is still isted in "Components detailed requirements", from contained discussion, we will NOT include copyright in this component and instead use the "sd-media" component as a wrapper?

@abudd1094 your right... this was wrong in the description. I will correct it.

> * From what I can tell, this is a dumb wrapper and any interaction should be implemented from the parent component?  Meaning all we do here is fire an event "sd-play" and mutate the "playing" property when the "play-icon" is clicked?  How can I write a story to demonstrate that without authoring a second component?

I'd suggest to show a sd-video component and add a simple HTML Video in there (maybe even the good old w3schools sample: https://www.w3schools.com/html/html5_video.asp). With this you can add a play icon and let the events fire (which a dev would have to inspect in the dev-tools). Or you find another idea.

> * What is meant by:
>   ![image](https://user-images.githubusercontent.com/39494579/272936601-e8604edf-c73b-469e-b73f-2add45004fd3.png)

We removed the poster slot as the poster has to / can be set in the nested HTML video element (on which we dont have any control). As we have this in our current CL component (ui-video) and its kind of expected, we want to show how to solve the "issue" without a poster property. So just a sample in the component, where the HTML video element has a poster to see what it looks like with the button and overlay.
Does this help?

**Comment by abudd1094** [comment]
PR ready for initial review:
https://github.com/solid-design-system/solid/pull/451

There is one "TODO: REVIEWER" comment that should be removed before final merge.

I created a file "videoExample.ts" in the video folder to write a proper example of the wrapper functionality.  I could not discern a clean way to do this directly in the stories file itself.  Does someone have a hint or better idea?  Please let me know.

It is not clear what we decided regarding copyright, I left an example of sd-media in the description.  Please advise.

**Comment by mariohamann** [comment]
> It is not clear what we decided regarding copyright, I left an example of sd-media in the description. Please advise.

We decided to leave it out AFAIK.

**Comment by abudd1094** [comment]
PR ready for re-review:
https://github.com/solid-design-system/solid/pull/451

**Comment by abudd1094** [comment]
blocked until I have full transparency on requirements
