### ISSUE TITLE
🙌 Epic: Indicator/Selector Elements

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#284]
To provide the above mentioned epic as a new feature to the SDS, the following tasks are already created and need to be closed:
- [x] #148 
- [ ] #275 
- [ ] #272 
- [x] https://github.com/solid-design-system/solid/issues/232

**Comment by mariohamann** [comment]
@coraliefeil @van-nguyen-ht @EllaELSA 

I don't get the concept behind those elements. They are so similar, besides some roundedness and maybe sizes. I would understand to have two of them, but 4 and then even a new one in the select element is way too much IMO.

cc @karlbaumhauer @yoezlem 

## sd-tag
> Tags allow labeling, categorizing, or organizing items using keywords that describe them.
![CleanShot 2023-07-31 at 13 54 45](https://github.com/solid-design-system/solid/assets/26542182/1baea674-1e72-4fff-84b1-5d48c195598a)

## sd-chip

> A small, non-interactive label that represents a status, property, or other metadata.
![CleanShot 2023-07-31 at 13 55 29](https://github.com/solid-design-system/solid/assets/26542182/f82d90c4-7f52-46d6-9f42-0c4a8393875a)

## sd-flag
> Tags allow labeling, categorizing, or organizing items using keywords that describe them.
![CleanShot 2023-07-31 at 13 56 04](https://github.com/solid-design-system/solid/assets/26542182/f844688f-eff3-49c9-beeb-69f3a05c128d)

## sd-badge
> Visual indicator of a quantity related to a particular element. Often displayed next to an icon or label.
![CleanShot 2023-07-31 at 13 56 39](https://github.com/solid-design-system/solid/assets/26542182/8626f2a0-b618-411e-bbfe-b49acd1d218a)

## sd-select / options
In multi-select selects.
![CleanShot 2023-07-31 at 13 57 03](https://github.com/solid-design-system/solid/assets/26542182/fb7c795f-9fa1-4429-bb4f-9b239414c42c)

**Comment by yoezlem** [comment]
Totally agree with Mario. We should make sure that we don't create a multitude of components that essentially represent the same or very similar things. It makes sense from my perspective to consolidate sd-tag, sd-chip, sd-select, and sd-flag.

**Comment by karlbaumhauer** [comment]
> Totally agree with Mario. We should make the usage of the sd-components as simple as possible. This includes eliminating or consolidating redundant components. It makes totally sense from my perspective to merge sd-tag, sd-chip, sd-select, and sd-flag.

not sure about the sd-select but agree to the rest.

IMO we should at least make it clear to the users why we have multiple marking elements.

**Comment by van-nguyen-ht** [comment]
I can see  sd-tag & sd-select/option to be 1 component and  sd-chip & sd-flag to be 1 component otherwise it's a bit challenging to specify with properties or?

**Comment by EllaELSA** [comment]
These are NOT variations of the same element. All elements are explicently needed by the teams and form a UX POV correct.

Tags can filter, they are clickable, they have a function.
The chips show categories, but are not clickable (e.g. show in a teaser on a learning platform in which section it belogs) 
The Flag shows in the same example that there a seats available, or that it is new.
A chips and a flag can live on the same teaser, and need to be distinguished. And both can not be done with a tag.

I think I dont have to explain the difference to a badge which lives as a notifcation element on an inbox icon (e.g.)

Only regarding the select we can talk to @coraliefeil where this was asked for. Maybe this is also do-able with the tag.

**Comment by karlbaumhauer** [comment]
thx @EllaELSA for the explanation. 
IMO this case is something where we might have to find a different approach for DEV and DESIGN as the functionality might be too different.

From what @EllaELSA wrote and from a perspective of simplifying the library as much as possible I would suggest to combine interactive and non-interactive elements.
### sd-tag & sd-select:
- interactive
- have different states (selected or not) and change their content accordingly (close icon)

### sd-chip & sd-flag:
- non-interactive 
- simple slot without any states on the component itself

### sd-badge
IMO the sd-badge can stay on its own as it is some kind of special-case in the indicator elements.

In general we can re-use the components within itself (=> use sd-chip to build sd-select) but should keep them separated in the library to provide a better overview and less complex components.

**Comment by mariohamann** [comment]
## sd-chip & sd-flag
Can we make sure, that e. g. the chip will never be interactive? Is this just not allowed people set e. g. a link on it to link to e. g. a category? So they would always use the `sd-tag` then?

If that's the case, I'm still questioning if we really need those two roundedness, what the benefit of this is, as they could still be distuingished by a color. If we need the different roundedness, I still see this as a single component having a rounded/not-rounded variant.

## sd-tag & sd-select-option
@EllaELSA "Tags can filter, they are clickable, they have a function." Not only for filtering, but interactive, yes, e. g. see the pill having the same design (https://component-library.fe.union-investment.de/latest/storybook/index.html?path=/story/components-pill--configurable&globals=backgrounds.value:!hex(F6F6F6)) but works as a link.

I even would be fine, if those two components would have a rounded/less-rounded-option, but definitely not two components, as this is the only difference here.

**Comment by karlbaumhauer** [comment]
decision from the refinement (29.08.2023):
- sd-chip => CSS component with 4 different color variants
- sd-flag => CSS component with 4 different color variants

@mariohamann / @coraliefeil pls rewrite the tickets (#275 & #272) and move them into "To be refined"
