### ISSUE TITLE
feat: ✨ add sd-scrollable

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#289]
## User Story
As a user of the Solid Design System, I would like to utilize a `sd-scrollable` component, so that I can easily indicate with a shadow and scroll buttons, that there is hidden content to be scrolled.

## Documentation
https://www.figma.com/file/7vU3PYV6MlANamSvmDaQRX/Scrollable?type=design&node-id=2203-386&mode=design&t=EoYe8ercIJ2ZpDoe-4
## Hand-off
https://www.figma.com/file/7vU3PYV6MlANamSvmDaQRX/Scrollable?type=design&node-id=75-4326&mode=design&t=EoYe8ercIJ2ZpDoe-4

#### Props
| Status | Name | Type | Default | Description |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <ul><li>[ ] </li></ul>  | `orientation` | `horizontal` / `vertical` | `horizontal` | defines the scroll orientation |
| <ul><li>[ ] </li></ul>  | `buttons` | `boolean` | `false` | Activate scroll buttons |
| <ul><li>[ ] </li></ul>  | `scrollStep` | `number` | `150` | Amount in px to be scrolled when clicking the buttons. |
| <ul><li>[ ] </li></ul>  | `scrollbars` | `boolean` | `false` | Activate browser scrollbars |
| <ul><li>[ ] </li></ul>  | `shadow` | `boolean` | `false` | Activate a shadow as optional visual scroll indicator |
| <ul><li>[ ] </li></ul>  | `gradient` | `boolean` | `false` | Activate a gradient as optional visual scroll indicator |

#### Events
- [x] button-end clicked
- [ ] button-start clicked
- [ ] end reached
- [ ] start reached

#### CSS-Properties
  - [x] `gradient` - define a custom color for the gradient
#### Parts
  - [ ] every other HTML element (depending on the HTML structure) => NOTE: if highlighting the parts in the `parts` story does not work out of the box, do not spend more effort on it but open a bug ticket to tackle it later.
#### Slots
  - [ ] `content` - default content slot
  - [x] `icon` - slot to replace the buttons icon (chevron)
#### Stories (besides the `default` story)
  - [ ] `Gradient`
  - [ ] `Button`
  - [ ] `Shadow`
  - [ ] `Scrollbar`
  - [x] `Custom Icon` - Replacing the chevrons with another icon
#### Samples
  - [ ] The scrollable sample/story in the `sd-tab-group` should then be replaced with the new `sd-scrollable` and a description should be added to point to the `sd-scrollable` component.

#### Dependencies
- [x] Update [scrollable dialog](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/story/components-sd-dialog--scrolling) using sd-scrollable and initially showing a shadow at the bottom of the scrollable and when scrolled down a shadow at the top. Then users get that they can scroll down.

### Technical information
- Functionality from #280 could be excluded and added here in a more generic way.
- compare functionality/code with the current implementation from [Component Library](https://component-library.fe.union-investment.de/latest/storybook/index.html?path=/docs/components-scrollable--docs)

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by van-nguyen-ht** [comment]
Hi @azraefendic 

for white and primary background, I'll implement the same color for sd-divider: neutral-400 & primary-00. Here's the screenshot. 

![Image](https://github.com/solid-design-system/solid/assets/118520877/acf5f891-8571-4950-9593-2c7ae8db528c)
