### ISSUE TITLE
fix: 🐛 🤔 provide docs how to use registerIconLibrary with UMD bundle

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#296]
## Current behavior
Coming from https://github.com/solid-design-system/solid/pull/295/files we realized, that the registerIconLibrary is currently not working. We have to investigate how to provide this properly from our builds.

## Expected behavior
- People should know how to use the icon library provider.
- Include test integration 

## Steps to reproduce
Tests which were removed in https://github.com/solid-design-system/solid/pull/295/files should be commented "in" and work afterwards.

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by yoezlem** [comment]
[13:20] Hamann, Mario (EXT/Partner) (Guest)

const { registerIconLibrary } = window['Solid Components'];
