### ISSUE TITLE
feat: ✨ add sd-header

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#301]
## Description

The sd-header is meant to be overridable for the usage of its context.

## API

- prop `fixed`: `boolean` → adds shadow and adds fixed behaviour → currentHeight → :root → CSS Variable `--sd-header--height`

We should be able to do this:
```css
body{
padding: var(--sd-header--height);
}
```

- part: `main` to make everything overridable especially paddings and width → provide one responsive sample and non-responsive versions showing the single breakpoints

## Figma Comp 
https://github.com/solid-design-system/figma/issues/72

## Hand-off
https://www.figma.com/file/C0vgSK38CNYY83oAqh5s42/sd-header-V.0.0.1?type=design&node-id=10878-1611&mode=design&t=fNb9P9PYikurbXax-4

### Components detailed requirements
- [x] Props, CSS-Properties, Parts & Slots
  - [x] fixed boolean
- [x] Stories
  - [ ] tbd

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [x] Documentation has been created/updated (if applicable)
- [x] Migration Guide has been created/updated (if applicable)
- [x] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [x] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
@coraliefeil Do you already have a plan/draft for this simple component? :)

**Comment by coraliefeil** [comment]
Yes. In this branch https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/yb2bjJUCaZPBRzLXBw1uzc/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=6625-34519&mode=design&t=SUnvaI9zQvjYUVCz-11

**Comment by karlbaumhauer** [comment]
@mariohamann pls have a look into the figma file and prepare the ticket

**Comment by coraliefeil** [comment]
Here’s my comment from our team chat.

People need the sd-header to be able to build header navigation and mega menus ... using sd-navigation item.

sd-header is not ready yet.
 
ATM they can only build mobile or sidebar menus using sd-drawer. 
 
In Figma the design compoonent needs adjustments for default slot concept ... but other than that the comp is in good shape. 

Could we give sd-header code comp a higher prio to support this dependency? 

What do you think?

**Comment by coraliefeil** [comment]
Pls see if @azraefendic could tackle this. THX

**Comment by karlbaumhauer** [comment]
@coraliefeil I increased the priority and we should have a look into it on Friday.
