### ISSUE TITLE
feat: ✨ add sd-iframe

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#302]
### Components detailed requirements
- [ ] Props, CSS-Properties, Parts & Slots
  - [ ] tbd
- [ ] Stories
  - [ ] tbd

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
We don't have any benefit from design perspective by providing this. On top this highly depends on the iFrame Resizer (12kb). This feels like an utility for CMS project, where it made sense to have this as a component to provide everything from a single logic.

Every other project can easily set an `<iframe>` and embed the resiezr script (if needed!) on their own.

I would therefore suggest to close this one.

**Comment by yoezlem** [comment]
I agree with Mario.
So I would suggest closing the ticket, as I see no added value of the component for our library.
