### ISSUE TITLE
feat: ✨ add sd-portal

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#303]
### Components detailed requirements
- [ ] Props, CSS-Properties, Parts & Slots
  - [ ] tbd
- [ ] Stories
  - [ ] tbd

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
The `ui-portal` is used a single time in the whole Monorepo in a project which currently is going to be written to React. I would suggest to just close this issue as `won't fix`.

**Comment by yoezlem** [comment]
I would also suggest closing the ticket, as I see no added value of the component for our library.
