### ISSUE TITLE
feat: ✨ add supernumber pattern

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#307]
## User Story
As a Solid Design System user, I need a supernumber pattern to highlight key figures. It should include overline, number, subline, and description for clear and consistent presentation of important numerical data.

## Documentation
https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=1663-16479&mode=design&t=4DSpu9hffmhPXlqI-4

## Hand-off
https://www.figma.com/file/DAidYiZR80xAc8nr7eGI3m/Supernumber?type=design&node-id=6-4&mode=design&t=Nyyt2RmAX0zIJKia-0

#### Stories (besides the `default` story)
  - [x] `Default` - for the text above, below & description
  - [x] `Prefix` - is the prefix inside the supernumber -> for (prefix) 200 (number) years (suffix)
  - [x] `Suffix` - is the suffix inside the supernumber
  - [x] `Size` - include 3 sizes, depending on the container-size -> lg, md, sm
  - [x] `Inverted`
  - [x] `i18n` - show internationalization with countUp.js options

### Technical Information
- [x] The text above and under the number are `sd-paragraph` with bold font-weight.
- [x] For the devs: don't use `sd-display` for the number. Adapt everything from the typography section in figma.
- [x] The description is `sd-paragraph`
- [x] The counter will be implemented with https://inorganik.github.io/countUp.js/

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [x] Documentation has been created/updated (if applicable)
- [x] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [x] Relevant stories (Features, A11y) are created/updated
- [x] Implementation works successfully on `feature` branch

**Comment by karlbaumhauer** [comment]
@yoezlem pls take over from me here. Ticket needs to be reformulated regarding the agreements from pre-refinement:
we do a pattern and not a component. Following patterns should be provided:
- with number prefix and suffix
- with animation (https://inorganik.github.io/countUp.js/)
- i18n
- optional texts (text above, below & description)

**Comment by yoezlem** [comment]
@coraliefeil we have different sd-display classes I guess. In storybook, the biggest size is 40px and color would be black. In the Figma files we have primary color and the font-size is: 72px.

also for the sd-display (above and under the subernumber), in storybook we don't provide a bold font-size, it seems in figma we do.

**Comment by coraliefeil** [comment]
I’ve created [#860](https://github.com/solid-design-system/solid/issues/860) to mirror code pattern in figma.
