### ISSUE TITLE
feat: ✨ add sd-map

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#308]
### Components detailed requirements
- [ ] Props, CSS-Properties, Parts & Slots
  - [ ] tbd
- [ ] Stories
  - [ ] tbd

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
I would omit very heavy dependencies like the Google Maps stuff as much as possible. Furthermore the requirements for this component often change and most of the time they have nothing to do with what brand needs. I therefore highly suggest to focus on what brand really needs and what is used in different occasions: the `sd-map-markers`.

https://component-library.fe.union-investment.de/latest/storybook/index.html?path=/story/components-mapmarker--default&globals=backgrounds.value:!hex(F6F6F6)

As soon as design is done with that one, we could easily implement it. AFAIK nothing has to be changed regarding the current API including slots or the structure. Fortunately even stuff like click handling etc. can be ignored completely (as long as Google Maps is used) and we con focus on the styling and documentation.

**Comment by mariohamann** [comment]
@coraliefeil Do we already have a Figma draft for the sd-map-markers?

**Comment by coraliefeil** [comment]
Only WIP ... since we deprioritized it
https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/1zKhsJrAC54nmZFa7aR1te/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=5510-25512&mode=design&t=WrJNRn53Vo3I3RqY-11

**Comment by yoezlem** [comment]
@coraliefeil which component are we talking about? In your Figma file I saw the pins and the location flyout. For the pins we have sd-map-markers. So I am a little bit confuse whats the task here.

**Comment by van-nguyen-ht** [comment]
[Design figma branch ](https://www.figma.com/file/1zKhsJrAC54nmZFa7aR1te/sd-map-marker-V.0.0.1?type=design&node-id=4803-25242&mode=design)

**Comment by yoezlem** [comment]
@mariohamann lets check together what we need here.

**Comment by yoezlem** [comment]
Kann prinzipiell entfernt werden, da wir keine Map (Google Maps Web-Components) erstellen werden. Für weitere Infos: https://github.com/solid-design-system/solid/issues/573#issuecomment-2045376536

**Comment by karlbaumhauer** [comment]
> Kann prinzipiell entfernt werden, da wir keine Map (Google Maps Web-Components) erstellen werden. Für weitere Infos: [#573 (comment)](https://github.com/solid-design-system/solid/issues/573#issuecomment-2045376536)

so ui-surrounding-map is another case fpr the "discontinued list"?

**Comment by yoezlem** [comment]
I would only add a sample of how the sd-map-markers can look inside Google Maps, but without adding and supporting a layer Maps component. Because at the end it would mean, that if the solution architect of Informationsmanagement isn't fast enough, we have to accredit it.

**Comment by karlbaumhauer** [comment]
closed due to #944
