### ISSUE TITLE
feat: ✨ deprecate ui-tile and add migration guide

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#309]
## Description
This component will not be part of the SDS Library.
Nevertheless, we need to add some documentation into our migration guides how to use the `teaser-centered` sample to cover this use-case.

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [x] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [x] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
This looks like a CMS component to me: https://component-library.fe.union-investment.de/latest/storybook/index.html?path=/story/components-tile--configurable&args=icon:book-bookmarks;text:tile+tdasdasdsext&globals=backgrounds.value:!hex(F6F6F6)

![CleanShot 2023-08-28 at 15 01 24@2x](https://github.com/solid-design-system/solid/assets/26542182/7d9734d5-c409-4340-acc8-a7276775d158)

**Comment by coraliefeil** [comment]
@EllaELSA we could just use sd-teaser-centered and get rid of tile
https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=1897-22849&mode=design&t=FzNJCzVzwSqy3wrn-11

The text would look different then ... would this be possible from your perspective?

In terms of consolidating things I would second replacing ui-tile and use sd-teaser-centered.

**Comment by yoezlem** [comment]
will be blocked until we have the sd-teaser-centered component.

**Comment by Vahid1919** [comment]
Removing the blocker since #730 is closed.
