### ISSUE TITLE
feat: ✨ add sd-drawer

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#314]
## Description
> Drawers slide in from a container to expose additional options and information.

https://shoelace.style/components/drawer

## API

Coming from https://github.com/solid-design-system/figma/issues/54#issue-1811521181
https://www.figma.com/file/HHBbD5kdSWjiD8H1lA8jHf/Drawer?type=design&node-id=0-1&mode=design&t=0SAKc9ip7D2bSSNT-11

### Overview

![Image](https://github.com/solid-design-system/figma/assets/26542182/71ae077a-fd1a-4ffb-b7da-ecc160375210)

### Props

![Image](https://github.com/solid-design-system/figma/assets/26542182/72ca144a-38dc-4126-bccf-57f16f7d289a)

![Image](https://github.com/solid-design-system/figma/assets/26542182/e75ae764-8ea5-4097-a82e-e36951a7e555)

### Slots

![Image](https://github.com/solid-design-system/figma/assets/26542182/00f547bf-05fb-469b-9904-ee54d37d1071)

![Image](https://github.com/solid-design-system/figma/assets/26542182/9ef83239-97a0-4099-baee-1e05c0e59b8c)

![Image](https://github.com/solid-design-system/figma/assets/26542182/18511aba-d187-44b6-bd94-9cba92911df4)

## Hand-off

https://www.figma.com/file/yN3BI0cWA3AlcrKWEpBIP5/Drawer?type=design&node-id=1103-913&mode=design&t=Ck5DjbhRklpiyyuc-11

![image](https://github.com/solid-design-system/solid/assets/26542182/2b08d4c9-63a3-421e-a3e3-17e3f9efeb1c)

## Components detailed requirements
- [x] Proceed with this branch: https://github.com/solid-design-system/solid/tree/feat/sd-drawer
- [x] Props
  - [x] `open`
  - [x] `label` (behavior tbd see "open questions")
  - [x] `placement` (left, right)
  - [x]  `contained` prop (only for testing purposes)
- [ ] CSS-Properties
  - [x] --width (width of the drawer and NOT the overlay)
  - [x] remove all shoelace properties
- [ ] Slots
  - [x] `default` (no name)
  - [x] `header`
  - [x] `footer`
- [ ] Stories
  - [x] `open` (a button should be provided to open)
  - [x] `slots`
  - [x] `scrolling` → to show that big content doesn't make the element bigger)
  - [x] `Mouseless` interactive story
  - [x] Initial focus (https://shoelace.style/components/drawer#customizing-initial-focus)
- [x] Parts
  - [x] same as Shoelace but change `header-actions` to e. g. `header-content`
- [x] Migration guide
```js
// ui-offcanvas-panel
  @Prop({ reflect: true, mutable: true }) open: boolean;

  @Prop({ reflect: true }) darken: boolean; // this won't be provided any more 

  @Prop() position: 'left' | 'right' = 'left';

  @Prop() activeBelow: number; // → placement

  @Prop() closeOutside: boolean; // this won't be provided 

  @Event() offcanvasTrigger: EventEmitter<{id: string}>; // this won't be provided any more 
// ui-offcanvas-trigger
// -> not needed anymore, just trigger with methods

// ui-offcanvas-provider
// → not needed anymore
```
## Technical Information
- #289 is still not ready but not blocking the sd-drawer => just make it scrollable without any indicator

## open questions
- [x] what about the label? is it required? only for screen readers?
- [x] what with the initial focus? shouldnt it be inside the drawer? @coraliefeil can you ask your A11y contact about the expected behavior?

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by coraliefeil** [comment]
@azraefendic 
It is advisable to jump directly to the first element (This is expected behaviour usability-wise.). You just have to weigh it against the effort. But it is not a barrier as long as you can focus into the drawer.

**Comment by van-nguyen-ht** [comment]
@azraefendic @mariohamann 
Hi guys, I've updated the [documentation](https://www.figma.com/file/yN3BI0cWA3AlcrKWEpBIP5/Drawer?type=design&node-id=1103-913&mode=design&t=wjsfmGWbVX3RZa5r-11) per discussed. To achieve negative margin for the button, the left padding is left empty while an extra padding can be turn on/off depending on either a button is used in the Header slot or not. 

![Image](https://github.com/solid-design-system/solid/assets/118520877/7294e6fc-fe23-42f3-8e35-e92191a6265f)

**Comment by coraliefeil** [comment]
Got this answer from my dev colleague:

Depends on label and function. Basically, it is never wrong to provide information. In case of doubt, this has to be done via ARIA, but usually the label is somehow missing in the "normal" UX.

@karlbaumhauer @mariohamann FYI
