### ISSUE TITLE
feat: ✨ add sd-footnote - CSS style

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#317]
## Description
As a user exploring the content, I want to access additional information or sources related to the content by viewing footnotes. Footnotes should be displayed at the bottom of the page or below the content they refer to, allowing me to easily reference and comprehend the supplementary details provided.

## Documentation
https://www.figma.com/file/DeZ6iJggYfpSXHcEexNeYs/Footnote?node-id=0%3A1&mode=dev

## Hand-off
https://www.figma.com/file/DeZ6iJggYfpSXHcEexNeYs/Footnote?node-id=6%3A4&mode=dev

### Props
| Status | Name | Type | Default | Description |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <ul><li>[ ] </li></ul>  | `--number` | `CSS Variable` | `false` | This attribute allows content references to be displayed as numbered or unnumbered lists, typically starting with '1'. |
| <ul><li>[ ] </li></ul>  | `--reset` | `CSS Variable` | `false` | This attribute allows to reset already incremented numbers and start counting them from 1 again. |

#### Stories (besides the `default` story)
  - [x] `Number`
  - [ ] `Reset`

#### Samples
  - [ ] `Counter` - Counter can be used to start the numbering from a value other than 1, allowing any desired number as the beginning. For instance, the first sd-footnote could have the number 5, the second sd-footnote would then have the number 6, and so on: https://developer.mozilla.org/en-US/docs/Web/CSS/counter-increment

## Technical Hint
If `sd-footnote--number` is set to true, counting will start until `sd-footnote--reset` is used. With this attribute, the incremented numbers are reset and start counting from 1 again. This ensures that numbers that do not count from 1 can be reset.

You can familiarize yourself with the counter-reset logic through the following documentation: 
- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_counter_styles/Using_CSS_counters
- https://developer.mozilla.org/en-US/docs/Web/CSS/counter-reset

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [x] Implementation works successfully on `feature` branch

**Comment by coraliefeil** [comment]
@karlbaumhauer could this be a style component? I remember our team negociating wether this is a comp or not ... and since we have styles now ... this could be one?

**Comment by karlbaumhauer** [comment]
@coraliefeil yes your right. I have in mind that we already agreed on that. @mariohamann @yoezlem

**Comment by yoezlem** [comment]
Should be work as styles!

**Comment by mariohamann** [comment]
At least we should give it a try. :)

**Comment by coraliefeil** [comment]
@van-nguyen-ht could you refactor this comp and turn it into a css style, pls? Then we can refine it on Friday in the team. Merci.

**Comment by van-nguyen-ht** [comment]
@karlbaumhauer sorry I'm a bit confused, what do you want to stand in the reset property?

**Comment by coraliefeil** [comment]
@van-nguyen-ht that is only rel. for code ...

**Comment by van-nguyen-ht** [comment]
@coraliefeil ah I see thank you for clarifying that. 
Here's the [refactored comp](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=3763-24329&mode=design)

**Comment by coraliefeil** [comment]
@van-nguyen-ht could you give it a new version number, pls? V.1.0.0 
thx

**Comment by van-nguyen-ht** [comment]
@coraliefeil oh I totally forgot the Comps Overview sorry. 
@karlbaumhauer this is done so I'll hand this back to you.
