### ISSUE TITLE
docs: 📚 npm package import stencil / webpack

### ISSUE THREAD

**Issue by christophsaile** [solid-design-system/solid#323]
## Description
When you import a versioned component in a stencil / webpack setup as described in the docs (https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/docs-general-installation--docs#npm) the path is not correct and leads to the following error:
![image](https://github.com/solid-design-system/solid/assets/54807480/5da1322b-bc6a-45ca-ae7c-5748505bbdd2)

changing the import path from 
`import '@solid-design-system/components/versioned/brandshape/brandshape'`

to
`import '@solid-design-system/components/dist/versioned-package/components/brandshape/brandshape';
`
fixes the error.

## Technical Information
Add the documentation in addition to current documentation and make clear that it is for Webpack.

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by niksan9** [comment]
The same is valid for the unversioned components. The correct import structure is
`'@solid-design-system/components/dist/package/components/teaser/teaser'`
