### ISSUE TITLE
fix: 🤔 disabled sd-button changes size when toggled in firefox

### ISSUE THREAD

**Issue by Vahid1919** [solid-design-system/solid#331]
## Current behavior
Toggling an sd-button found in sd-carousel(#324 ) will cause the button to change sizes and therefore shift the entire container. This bug is only found on Firefox and only appears on the first button press.
## Expected behavior
The sd-button would "enable" without any changes in size and position on Firefox. 

## Steps to reproduce
Open the sd-carousel storybook on Firefox. Press the next slide icon. 

https://github.com/solid-design-system/solid/assets/63849626/168f646c-6f29-4be4-a2de-ff464b50a734

## Technical Information
The bug seems to be originating from the `disabled` method. I took a screenshot on the DOM of the button that shifts and a button that functions as expected, in case it'e helpful. 
### Button causes size change
![Button Shifts](https://github.com/solid-design-system/solid/assets/63849626/1e192d0b-fe32-4728-bae2-c45dda5818d5)
### Button works as expected
![Button Works](https://github.com/solid-design-system/solid/assets/63849626/356ffe98-7f41-4ab9-9888-5c6bb3b31b54)

The class attributes automatically change to the second one after the first toggle. Hence, the bug is only present for the first button press. 

- [ ] Find the cause of the bug 
- [ ] Fix the bug

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by Vahid1919** [comment]
I created a new branch with reverted changes from `sd-carousel` (that included `sd-button`)

I was not able to reproduce the error. And the weird changes in the `slot` css mentioned above don't seem to be an issue anymore. As discussed last time, this could be attributed to patches made on the browser side. Will be closing this ticket as it is resolved for now.

**Comment by karlbaumhauer** [comment]
[like]  Karl Baumhauer reacted to your message:
________________________________
