### ISSUE TITLE
feat: ✨ add sd-select-option

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#335]
## Description
This is an option which can be added to an sd-select, e. g.

```
<sd-select label="Select one">
  <sd-option value="option-1">Option 1</sd-option>
  <sd-option value="option-2">Option 2</sl-option>
  <sd-option value="option-3">Option 3</sd-option>
</sl-select>
```

## API
It should provide the same API as the one in Shoelace but use the UI styling. We will update the Figma API as well.

## Hand-off
https://www.figma.com/file/ZphyVFsUHL72voMrJagMeo/Select?type=design&node-id=1013-8034&mode=design&t=RdTNqifFhOAV79KX-4

### Components detailed requirements
- [ ] See Shoelace API

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
I expect this just to be a "subcomponent" in Figma. In dev, this is provided by listing the needed elements as done in Shoelace: https://shoelace.style/components/select#multiple

Therefore we can set the correct properties directly in our select-element like done over here and we don't have to extend anything: https://github.com/shoelace-style/shoelace/blob/414197acc94f441a70ed056cca5db973a732a9d4/src/components/select/select.ts#L760

**Comment by mariohamann** [comment]
It's super restricted in terms of: built into sd-select. No sample. Maybe we should have a common look how multiple works in Shoelace.

**Comment by karlbaumhauer** [comment]
ah... you mean exactly like shoelace did it... I understood to use this as sample and show how users can implement the sd-tag with styles...

If you want to build in the sd-tag and add styles so nobody can change it, I am totally second that. The question would be here if the component is used somewhere else but as the name is pretty strict to the sd-select, I doubt it... @coraliefeil? when we talked about it, we thought it might be used somewhere else... => Independent component.

**Comment by coraliefeil** [comment]
Not to be used anywhere else, strictly in sd-select.

**Comment by karlbaumhauer** [comment]
@mariohamann pls have a look into this ticket. I wasnt sure if the description matches the requirements / ideas.

**Comment by mariohamann** [comment]
This can be closed, as this is not needed as a seperate component but will be part of the `sd-select` – either we can override the `sd-tag` or it will be jsut "built-in" the original component.
