### ISSUE TITLE
chore: 🔧 Add accessibility tests for variant 'success' in sd-badge

### ISSUE THREAD

**Issue by MarcMatthiae** [solid-design-system/solid#336]
## Description
Due to issues with accessibility tests in sd-badge caused by an outdated token, I had to remove them for the 'success' variant. After updating our tokens, we should reintegrate these tests.

## Technical Information
Simply add 'success' to the variants-array in badge.test.ts

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Implementation works successfully on `feature` branch

**Comment by Vahid1919** [comment]
Closing this issue because it is already done. The "success" variant was already in the tests.
