### ISSUE TITLE
feat: ✨ Add sample for sd-button with sd-badge

### ISSUE THREAD

**Issue by MarcMatthiae** [solid-design-system/solid#341]
## Description
Add a sample (story) for showing sd-badge attached to sd-button.

## Hand-off
[LINK TO FIGMA](https://www.figma.com/file/frKFVz9UBKAtsvErLKTeGj/Badge?node-id=1613%3A125&mode=dev)

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by abudd1094** [comment]
https://github.com/solid-design-system/solid/pull/420#issuecomment-1748441480
