### ISSUE TITLE
feat: ✨ add sd-navigation-item

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#346]
## Description
The sd-navigation-item is a flexible component, that can be used to quickly build navigations. Examples of the item are available on Figma: https://www.figma.com/file/2hDs56yh73azMZafmpvEeU/Rework-Navigation?type=design&node-id=750-40814&mode=design&t=p1jVFPsX1m2c2TTq-4

This component doesn't provide stuff like flyouts, but instead only has the "content" of a navigation in mind.

## API

The API will soon be provided in another file, but we can start already with the one over here which was discussed and approved today: https://www.figma.com/file/cvr5GpzGeJzbWIPyi5MhGY/navigation-item?type=design&node-id=0-1&mode=design&t=hENJEUnDugfazCvx-11

<img width="589" alt="CleanShot 2023-08-24 at 14 42 36@2x" src="https://github.com/solid-design-system/solid/assets/26542182/982b3bc3-f900-4c74-9c7a-30d3616c29fc">

### Props

The most important difference is the `horizontal` prop. If set, it can be used for top navigations. If selected, the API is very reduced:
- `disabled`
- `current`: green line at the bottom

If the element is not horizontal, the component can have a lot more options:
- `disabled`
- `current`: green line at the left
- `chevron`: on dev side, this might be just a boolean, as the "accordion"-functionality could be provided with a `children`-slot
- `nested`: this just provides additional padding
- `size`: base (default), lg, 14px
- `divider`: sets a divider at the top which reflects nestedness etc.

If `current` is set, [aria-current](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current) should be added.

### Slots

For `vertical` and `horizontal` the main slot is available. 

The main slot can be used to set additional content like badges.
<img width="762" alt="CleanShot 2023-08-22 at 11 35 22@2x" src="https://github.com/solid-design-system/solid/assets/26542182/dd4a54de-1218-4456-9364-a695500840b3">

The vertical navigation-item in addition can have a description slot. It can be used to offer additional descriptions e. g. in mega menus or in sidebars as well.

<img width="245" alt="CleanShot 2023-08-22 at 11 40 42@2x" src="https://github.com/solid-design-system/solid/assets/26542182/e6e1890f-3eb4-41b8-89c7-cc90b56fc487">

The icons should be slottable as well for themability.

I would suggest implementing a `children` slot, where people can drop-in other sd-navigation-items. If there's something in the children slot, the chevron should show up as like in the accordion. To implement the functionality, I would suggest to use browser-built-in `details` and `summary` elements for that, to build it as fast as possible. (That's something Shoelace does in its newest version of the sl-accordion, too.) 

### Functionality

This is a tough one. So – the whole element should be hoverable and clickable.
When a `href` is provided, it will be a link, if not, it is a button, like we did for the `sd-button` and the `sd-tag`.

~~This is only relevant if the element doesn't have something in the children slot.~~

See comment below.

People should of course be able to listen to an event if there is a button.

## Hand-off
The tokens hand-off will be provided soon – most of the stuff can be read from the colors already.  I would propose to start measuring by eye and make the `hot-potato`-approach instead of doing the component only waterfally.

### Components detailed requirements
- [x] Props
  - [x] horizontal
  - [x] disabled
  - [x] current
  - [x] chevron
  - [x] size
  - [x] indentend
  - [x] relaxed
  - [x] divider
- [ ] CSS-Properties
  - [ ] ...
- [ ] Parts
  - [x] chevron
  - [x] icon-left
  - [x] icon-right
  - [x] description
  - [x] content
  - [ ] ...
- [ ] Slots
   - [x] icons in different states (see `sd-accordion`)
   - [x] default
   - [x] main
   - [x] description
   - [x] children? (only if we don't use nested)
- [ ] Stories
  - [ ] default - slot with bold everywhere (needs to be properly documented)
  - [ ] default and bold - comparison between the two
  - [ ] show how to override the hover color via parts selector to match <img width="370" alt="CleanShot 2023-08-23 at 20 36 45@2x" src="https://github.com/solid-design-system/solid/assets/26542182/e4766290-f4ab-4098-a75d-a26d7487d3ab">
- [ ] Samples 
  - [ ] horizontal first level (add documentation/hint to the sample which clarifies that the sds currently only provides first level and multi-level horizontal navigation will be provided in the future together with the flyout)
  - [ ] vertical behaviour including going one level deeper and swapping content

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by karlbaumhauer** [comment]
@van-nguyen-ht pls move this ticket to ready as soon as you have the handoff done (Alec might be starting earlier).

**Comment by mariohamann** [comment]
As examples from the B2B showed it makes more sense to not provide the component as bold per default.

I updated the component accordingly, as we should in dev. (We only will show a story where we show a bold and a non-bold defualt slot.)

![Image](https://github.com/solid-design-system/solid/assets/26542182/a32fc9d9-e001-41a8-8ef0-ea425836d8bb)

**Comment by abudd1094** [comment]
Hey @mariohamann,

What about for the displayed text "Navigation", will we have a slot or a prop for this?

Do we use "nested" as a prop to configure the behavior of "indented" and "relaxed" (the way they are shown in Figma) or should those two be props themselves?

**Comment by mariohamann** [comment]
We omitted `lnested` becomes sometimes there can be nested components which aren't indented. :D

**Comment by abudd1094** [comment]
I have made good progress on this one but I still don't have access to the first link in the ticket:

![Image](https://github.com/solid-design-system/solid/assets/39494579/a25852b2-a13c-4683-aaae-2a4602e71e64)

Trying to write a comprehensive test / story suite and will bring the results Monday to start the review process.

**Comment by karlbaumhauer** [comment]
> I have made good progress on this one but I still don't have access to the first link in the ticket:
> 
> ![Image](https://user-images.githubusercontent.com/39494579/266587885-a25852b2-a13c-4683-aaae-2a4602e71e64.png)
> 
> Trying to write a comprehensive test / story suite and will bring the results Monday to start the review process.

@coraliefeil could you pls have a look into that?

**Comment by coraliefeil** [comment]
You can now view the file with your work mail.

**Comment by karlbaumhauer** [comment]
> One check related to dependabot seems to fail, can you please advise? 

this has been fixed and as soon as you push another commit, it should not happen again.
> * I did not realize my commits were polluting your inbox / over-charging our test accounts, sorry for that, it will be better next PR

❤️ but not a huge issue. if you leave the PR as a draft, you can ask for feedback and prevent all checks running on each push.

> * I have not done anything with font, this topic is unclear for me at this point. We spoke about installing locally but the information I have is that I will need a license which we don't have yet for me.

Maybe @Vahid1919 / @MarcMatthiae or @azraefendic can help here as they where the last one starting here?!?

> * I have not done anything with "bold" as this requirement is not clear above

Your right. Its not completely clear. @mariohamann can you specify this in more detail? I am not sure if we agreed on using the html tag like in the table-cell...?!?

> * The ticket has not been updated to reflect the requirements spoken about during development, for example the 'vertical' property has now replaced the 'horizontal' property.  @mariohamann would you like me to update the ticket to reflect the outcome to the best of my knowledge or is this best left for someone who has a better overview?  For example, I added initial "mouseenter / leave" events thinking it would be useful for a flyout but after discussion this seems to be thought of as a future feature of this component directly...

Pls send me the changes to the ticket and I will implement them.

> * Lastly, I will be on vacation next week Tuesday to the following Tuesday but will still check GitHub.  Please keep this in mind for the release cycle should there be further required changes.

Thx for the hint. As we dont have a release cycle yet, it will not block anything. Only for the end of the current milestone (Friendly User Phase) on 29th of September, it would be nice to have the component done. But only if your able to. If you need more time, we just dont plan it for that time.

**Comment by abudd1094** [comment]
@coraliefeil 
![image](https://github.com/solid-design-system/solid/assets/39494579/ce2c4e2b-bb6a-4523-badc-49b5d52f8b6b)
Do you mean that the green current bar should be 4px shorter (top and bottom) when not hovered and grow to full height when hovered?

This behavior was not described in the ticket or evident on Figma. 
![image](https://github.com/solid-design-system/solid/assets/39494579/a30cf5ef-a071-4a09-bc36-c5e5071bbb4c)

@karlbaumhauer @mariohamann @yoezlem 
I still have no response regarding the "bold" text.  Please advise.

**Comment by mariohamann** [comment]
@abudd1094 Yes, it should grow when hovered. This came during the work on it. :)

---

Regarding bold:

Just make a Story which has a slot with bold and one without bold on `x` or `y` axis.

**Comment by mariohamann** [comment]
@abudd1094 This might help for hover:

https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-parent-state

**Comment by abudd1094** [comment]
> @abudd1094 Yes, it should grow when hovered. This came during the work on it. :)
> 
> Regarding bold:
> 
> Just make a Story which has a slot with bold and one without bold on `x` or `y` axis.

Quick tip on how to successfully do this?
![image](https://github.com/solid-design-system/solid/assets/39494579/d735505a-3e35-4444-91ce-2b6650f6b832)

**Comment by mariohamann** [comment]
`values: ['<b>Navigation</b>', 'Navigation']`
@abudd1094

**Comment by abudd1094** [comment]
> `values: ['<b>Navigation</b>', 'Navigation']` @abudd1094

This yields:
![image](https://github.com/solid-design-system/solid/assets/39494579/f46450b7-41e7-49b8-a5d4-5395e8938e8a)

**Comment by abudd1094** [comment]
All feedback has been resolved.
