### ISSUE TITLE
docs: 📚 rename Storybooks `default`

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#347]
## Description
In Storybook the first story ist called `default` but in most cases not showing the default behavior as we added content (slot-content) to show a sample. The actual `default` story would be blank in most cases.

A solution would be to rename the story and call it `standard` or something else to make it more clear => **NOTE:** Storybook might not support this idea...

## Where to put the documentation
All components in Storybook.

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
I collected some examples from Storybook Showcase:

- https://govuk-react.github.io/govuk-react/?path=/story/error-summary--default → wrong default
- https://govuk-react.github.io/govuk-react/?path=/story/select--default → wrong default
- https://master--5ccbc373887ca40020446347.chromatic.com/?path=/story/button--basic → no defaults, but calling it "basic"
- https://master--5ccbc373887ca40020446347.chromatic.com/?path=/story/linktabs--default → here defaults, with examples
- https://polaris-viz.shopify.com/?path=/story/polaris-viz-native-charts-sparkbarchart--default → wrong default
- https://opensource.adobe.com/spectrum-web-components/storybook/?path=/story/banner--default → wrong default
- https://opensource.adobe.com/spectrum-web-components/storybook/?path=/story/sidenav--default → wrong default
- https://gitlab-org.gitlab.io/gitlab-ui/?path=/story/base-accordion--default → wrong default
- https://gitlab-org.gitlab.io/gitlab-ui/?path=/story/base-banner--default → wrong default
- https://gitlab-org.gitlab.io/gitlab-ui/?path=/story/base-broadcast-message--default → wrong default
- https://react.carbondesignsystem.com/?path=/story/components-form--default → wrong default
- https://main--61a90feace7802003a4d9c45.chromatic.com/?path=/story/components-avatartoken--default-token → wrong default
- https://main--61a90feace7802003a4d9c45.chromatic.com/?path=/story/components-buttongroup--default → wrong default
- https://main--61a90feace7802003a4d9c45.chromatic.com/?path=/story/components-issuelabeltoken--default-token → wrong default
- https://react.carbondesignsystem.com/?path=/story/components-paginationnav--default → wrong default
- https://react.carbondesignsystem.com/?path=/story/components-tag--default → wrong default
- https://chakra-ui.netlify.app/?path=/story/avatar--default → wrong default
- https://chakra-ui.netlify.app/?path=/story/tabs--default → wrong default
- https://main--5d559397bae39100201eedc1.chromatic.com/?path=/story/all-components-appprovider--default → wrong default
- https://main--5d559397bae39100201eedc1.chromatic.com/?path=/story/all-components-navigation--default → wrong default

So wrapping it up: Everyone shows defaults. Often in defaults even a whole set of component variations is shown. Therefore we're already pretty "basic" in our default example, showing only one example in a quite "reduced" behaviour.

Let's have a look together in next refinement, but from my perspective we're already pretty good in shape. :)

**Comment by mariohamann** [comment]
Not needed with new structure, will be `Playground` in new structure.
