### ISSUE TITLE
docs: 📚 add version to og:title in storybook

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#351]
## Description
https://github.com/solid-design-system/internal/issues/28 now provides a custom title in Storybook and an og:title. The issue here is that it was not possible (on an easy way) to add the version to the title as well.

Adding the version from the package.json would be easy but this only works with fixed versions. The wildcard folders will then show the version from the package.json (eg. 1.6.3) but not the wildcard version (eg. 1.6.x). 

In order to provide a clear and easy way to see the version while sending and receiving links to Storybook, we (somehow) need to add the version to the Storybook title and the og:title.

### Note:
The storybook title is currently changed in `packages/components/scripts/storybook/node-modify-storybook.cjs`
The og:titles are set in `packages/components/.storybook/manager-head.html` but are static. The titles here would need to be modified afterwards.

We could also agree on just having the current version in the title and ignore the wildcard folder as an easy solution. 
Its just the question if the effort adding the the version (including the wildcard versions) is worth the effort.
In this case we just have to add a replace to the title replacement in `packages/components/scripts/storybook/node-modify-storybook.cjs`

eg:
  .replace(
      /<meta property="og:title" content="Solid Design System by Union Investment" \/>/,
      `<meta property="og:title" content="Solid Design System by Union Investment | Version: ${version}" />`
    )
    .replace(
      /<meta name="twitter:title" content="Solid Design System by Union Investment" \/>/,
      `<meta name="twitter:title" content="Solid Design System by Union Investment | Version: ${version}" />`
    )
    .replace(
      /<meta itemprop="name" content="Solid Design System by Union Investment" \/>/,
      `<meta itemprop="name" content="Solid Design System by Union Investment | Version: ${version}" />`
    );
...

## Where to put the documentation
n/a 

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by yoezlem** [comment]
blocked by: [#518](https://github.com/solid-design-system/solid/issues/518)
