### ISSUE TITLE
docs: 📚 show tokens in Storybook

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#355]
## Description

Currently the tokens aren't shown in Storybook. I experience that this is a problem for people starting with the project  + for reviewing tokens, which aren't in use.

I suggest to write automatic stories, which show...

- [ ] shadows
- [ ] z-indexs
- [ ] spacings 
- [ ] opacity
- [ ] font-size
- [ ] font-weight 
- [ ] border-radius
- [ ] risk

and also for **colors**

- [ ] error
- [ ] success

We maybe can use the following for that:
- https://storybook.js.org/docs/web-components/api/doc-block-colorpalette
- https://storybook.js.org/docs/web-components/api/doc-block-icongallery
- https://storybook.js.org/docs/web-components/writing-docs/doc-blocks#typeset

We should write some minimal docs how to e. g. use them with TailwindCSS.

The Stories should get their data automatically from the imported Tailwind Theme from the tokens package.

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by awacode21** [comment]
i currently have the problem, that i need to use the tailwind configuration for a Union Investment product, but i can nowhere see the tokens, their values and how to use them :-( So the problem is real

**Comment by christophsaile** [comment]
It would be nice if the tokens tab would also include error and warning colors. This way you can have an quick overview which colors can be used.
