### ISSUE TITLE
docs: 📚 housekeeping – align slots

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#359]
## Description

We have different implementations of the slot and my initial thing was some kind of pseudo-custom-element css vars etc.

It's interface it NOT good and starting it's starting to get a bit messy:

<img width="879" alt="CleanShot 2023-08-30 at 14 44 38@2x" src="https://github.com/solid-design-system/solid/assets/26542182/f70f46e1-f9a8-405c-aa78-880ed2eabc5a">
<img width="88" alt="CleanShot 2023-08-30 at 14 44 51@2x" src="https://github.com/solid-design-system/solid/assets/26542182/414f4258-9642-4bb3-974f-6df41d0275ec">
<img width="423" alt="CleanShot 2023-08-30 at 14 45 05@2x" src="https://github.com/solid-design-system/solid/assets/26542182/faa9d97e-d174-48c6-af47-9f44f0e89948">
<img width="721" alt="CleanShot 2023-08-30 at 14 46 05@2x" src="https://github.com/solid-design-system/solid/assets/26542182/d8f45b86-af99-4769-8e14-e01346d8e642">

For the `sd-dropdown` I implemented more dynamic BEM-CSS-classes, which you can use to just set an outline, set a background and optionally write content or whatever.

<img width="294" alt="CleanShot 2023-08-30 at 14 45 28@2x" src="https://github.com/solid-design-system/solid/assets/26542182/0e1c4ba6-b2bd-408f-9e79-9eb106d7f05d">

## Summary
- only use the classes used in `sd-dropdown` story
- remove `slot-comp` classes

## Where to put the documentation
- [x] update all related stories
- [ ] add to contribution guide (classes are part of the storybook head => **_ONLY_** to be used in storybook)

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by karlbaumhauer** [comment]
@mariohamann IMO this could go to the refinement as well...
the only question would be: where to we have these classes (figma or github) and is the expected use for theses classes documented? 
If not, pls add this to the ticket.

**Comment by karlbaumhauer** [comment]
edit from refinement:
- classes are part of the storybook head => just to be used in storybook
- add docu to contributing.md
