### ISSUE TITLE
feat: ✨ extend placeholders package with videos

### ISSUE THREAD

**Issue by christophsaile** [solid-design-system/solid#378]
## User Story
As a User of the Solid Design System, I would like to have videos in the placeholder package,
so that I don't have to rely on other dummy data.

### Suggesed Solution
Add a video to the placeholder package. https://github.com/solid-design-system/solid/issues/867#issuecomment-2058947661

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by coraliefeil** [comment]
@EllaELSA if we receive a placeholder video from Brand, pls forward to @karlbaumhauer for implementation. Thanks a lot.

**Comment by christophsaile** [comment]
@EllaELSA any updates on this?

**Comment by EllaELSA** [comment]
@christophsaile please use the video Debbi got for the infinity comp. I got an approval for this from Sandra. Just waiting for the url of the video from Eileen.
Will update this on monday

**Comment by EllaELSA** [comment]
@christophsaile the video we can use ist this one.
https://www.pexels.com/de-de/video/liebe-menschen-garten-zeitlupe-4625767/

**Comment by karlbaumhauer** [comment]
@EllaELSA I had to delete a your comment as you mentioned personal information from people outside this team. Pls make sure you do not provide any personal information in this public repository.

**Comment by coraliefeil** [comment]
@EllaELSA can we offer a video with audio track in addition?

**Comment by karlbaumhauer** [comment]
@EllaELSA What is the current status here? What would be the size of the ticket?

**Comment by EllaELSA** [comment]
Brand suggested the explanatory film from the CD toolbox. If this works for you I can try to get the file. @karlbaumhauer

**Comment by karlbaumhauer** [comment]
This would be benefitial for a start, IMO.

**Comment by yoezlem** [comment]
closed with #1032
