### ISSUE TITLE
feat: ✨ sd-table-cell add sortable sample

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#380]
## User Story
As a user of the Solid Design System, I would like to see a sample of a complete table, in order to easily copy the code and better understand the necessary implementation to have a sortable table using `sd-table-cell`. 

## Description

- Developers using the docs should be able to click on the headers and the table would reflect the changes e. g. the arrow directions and filled states etc.
- Have a look on https://github.com/solid-design-system/solid/issues/380#issuecomment-1722969534 for a starter.
- Check out the docs over here for hover, filled/non-filled and arrow direction. https://www.figma.com/file/KyUiUXKhMLiwCfKYDRh2bO/Table?type=design&node-id=1608-900&mode=design&t=64PFvpLJFQN3o6e5-11
- As this is a sample, we just use Tailwind to style even the interactive cells, e. g. `<th><button class="sd-table-cell text-primary hover:bg-neutral-200 transition-all">Text and arrows here</button></th>` – maybe we have to change the order of Tailwind.css solid-styles.css in Storybook head.

![Image](https://github.com/solid-design-system/solid/assets/26542182/aee60549-e597-47b2-a436-eabbd813170c)

## Dev note

It might make sense to even integrate something like https://gridjs.io

## API
development only

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
I wouldn't recommend this for the following reasons:
1. It goes hand in hand with semantics, where people could mess up stuff.
2. We even don't know if the background is gray or blue and maybe would have to add even more styles.
3. This would need us to add the icon as well to make it "complete".

Looking real stuff it looks like this:
<img width="1242" alt="CleanShot 2023-09-13 at 16 39 45@2x" src="https://github.com/solid-design-system/solid/assets/26542182/eafcdd2d-31b2-45a4-b035-9b66e2e0d371">

https://www.union-investment.de/fonds_depot/fonds-finden

In that case a style as suggested wouldn't help anything.

I therefore suggest to leave it like it is, lead in the Samples with best practices people can follow and leave the final implementation to the users?

**Comment by karlbaumhauer** [comment]
> I wouldn't recommend this for the following reasons:
> 
> 1. It goes hand in hand with semantics, where people could mess up stuff, when they just rely on a style. (Like setting an onclick handler only on the cell – what would be wrong)

Maybe I was not clear in this, but I dont mean to add any semantics/logic here. Just a style which cleans up the table and adds styles we need to make it work. I saw about 15 lines of code just to make it work with the interactive style. This seems not like a very good developer-experience to me.

> 2. We even don't know if the background is gray or blue and maybe would have to add even more styles.

I did not want to touch the color of the cell. This would be another class to be set on the cell. I just mean the stuff about the clickable area and layout in the header cell.

> 3. This would need us to add the icon as well to make it "complete".

The definition of complete is not clear to me... we offer only a small part of a "table" component and therewith will never be complete. An additional class would just get closer to "complete" (IMO).

> 
> Looking real stuff it looks like this: <img alt="CleanShot 2023-09-13 at 16 39 45@2x" width="1242" src="https://user-images.githubusercontent.com/26542182/267691897-eafcdd2d-31b2-45a4-b035-9b66e2e0d371.png">
> 
> https://www.union-investment.de/fonds_depot/fonds-finden
> 
> In that case a style as suggested wouldn't help anything.
> 
> I therefore suggest to leave it like it is, lead in the Samples with best practices people can follow and leave the final implementation to the users?

Lets have a look into it in the refinement. I would like to understand the difference between an "interactive" style and this case. Both would help the developers to easily implement designs we want them to use.

**Comment by karlbaumhauer** [comment]
edit from pre-refinement:
- docu for interactive cells => design provide specifications => add story for interactive cells
- question with design if funds sample is correct (in terms of a11y)
- more real-life samples from design

**Comment by karlbaumhauer** [comment]
We will wait for feedback from F&P. @EllaELSA will try to clarify the need/specifications for an interactive table-cell.

**Comment by MarcMatthiae** [comment]
Since we decided to take out the sortable sample out of ... I will leave my current code here:

    const sortData: ('ascending' | 'descending' | 'none')[] = Array.from(
      { length: tableColumnCount },
      (_, columnIndex) => (columnIndex === 0 ? 'ascending' : 'none')
    );
 // Function to exchange the sort icons and set the aria-sort attribute in the sortable table after a click on a table header
    const sortTable = (column: number) => {
      const sortingOptions: {
        [key: string]: {
          nextSort: 'ascending' | 'descending' | 'none';
          iconName: string;
          ariaSort: string | undefined;
        };
      } = {
        none: { nextSort: 'ascending', iconName: 'system/sort-up', ariaSort: undefined },
        ascending: { nextSort: 'descending', iconName: 'system/sort-up-filled', ariaSort: 'ascending' },
        descending: { nextSort: 'none', iconName: 'system/sort-down-filled', ariaSort: 'descending' }
      };
      const icons = document.querySelectorAll('[id*="sortIcon"]');
      const headerCells = document.querySelectorAll('[id*="sortableHeader"]');

      if (icons && headerCells) {
        headerCells.forEach((headerCell, index) => {
          //Change the sort icon and aria-sort attribute for the clicked column
          if (index === column) {
            const nextSort = sortingOptions[sortData[column]].nextSort;
            const { iconName, ariaSort } = sortingOptions[nextSort];

            sortData[index] = nextSort;
            icons[index].setAttribute('name', iconName);
            ariaSort !== undefined
              ? headerCell.setAttribute('aria-sort', ariaSort)
              : headerCell.removeAttribute('aria-sort');
          }
          //Reset the sort icon and remove the aria-sort attribute for all other columns
          else {
            const { iconName } = sortingOptions['none'];

            sortData[index] = 'none';
            icons[index].setAttribute('name', iconName);
            headerCell.removeAttribute('aria-sort');
          }
        });
      }
    };

        <table class="sd-table sample-table" id="sortableTable" .sortData=${sortData}>
          <thead>
            ${(() => {
              return html`<tr>
                ${headerData.map((cellData, columnIndex) => {
                  return html`<th
                    class="sd-table-cell sd-table-cell--bg-transparent sortable ${columnIndex + 1 < headerData.length
                      ? 'sd-table-cell--divider'
                      : ''}"
                    id="sortableHeader-${columnIndex}"
                    aria-sort=${ifDefined(sortData[columnIndex] === 'none' ? undefined : 'ascending')}
                  >
                    <button class="sd-interactive sd-interactive--reset" @click="${() => sortTable(columnIndex)}">
                      ${cellData}<sd-icon
                        id="sortIcon-${columnIndex}"
                        library="global-resources"
                        name=${sortData[columnIndex] === 'none' ? 'system/sort-up' : 'system/sort-up-filled'}
                      ></sd-icon>
                    </button>
                  </th>`;
                })}
              </tr>`;
            })()}
          </thead>
          <tbody>
            ${tableData.map(rowData => {
              return html`<tr>
                ${rowData.map((cellData, columnIndex) => {
                  return html`<td
                    class="sd-table-cell sd-table-cell--bg-transparent ${columnIndex + 1 < headerData.length
                      ? 'sd-table-cell--divider'
                      : ''}"
                  >
                    ${cellData}
                  </td>`;
                })}
              </tr>`;
            })}
          </tbody>
        </table>

**Comment by coraliefeil** [comment]
@mariohamann @karlbaumhauer – ATM We now only provide only a sample for sortable tables in figma ... which we don’t maintain ... though we agreed on adding sortable feature ... which I think is important because people need that quite often.

Would like to talk about that.

**Comment by karlbaumhauer** [comment]
results from pre-refinement:
- sortable will be a sample and not included into the component => refactor ticket
