### ISSUE TITLE
docs: 📚 how to register icon libraries with UMD bundle

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#382]
## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by karlbaumhauer** [comment]
linked to #296

**Comment by mariohamann** [comment]
We will wait with the docs until @christophsaile implements it, so we can make sure to provide best practices. We already have a rough concept in mind, but would have to test in a more realistic environment.

**Comment by karlbaumhauer** [comment]
@mariohamann sounds good. 
Is this something we need for the 1 Solid Release? Wonder why this is not part of the milestone as it seems like part of proper documentation... :/

**Comment by mariohamann** [comment]
Currently CMS around is the only user of the bundle (AFAIK). We would like to make the docs a proper, tested one in real-life CMS-context instead of jsut prototyping it locally.

**Comment by yoezlem** [comment]
This will be fixed in https://github.com/solid-design-system/solid/issues/382
