### ISSUE TITLE
feat: ✨ quick link to GitHub in Storybook

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#383]
## User Story
As a development user of the Solid Design System, I would like to quickly find the GitHub Project on the Storybook page, so that I can easily inspect more detailed code.

### Suggested Solution
Add a quick link to the GitHub project to the upper right corner of the Storybook page. I could not find the correct keyword for it but there used to be these small black triangles in one of the corners of a website with a GitHub icon. This icon then leads to the GitHub project.

## DoR
- [x] Item has business value
- [ ] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by yoezlem** [comment]
blocked by: [#518](https://github.com/solid-design-system/solid/issues/518)
