### ISSUE TITLE
docs: ✨ (interactive) documentation how to skin Solid Components

### ISSUE THREAD

**Issue by christophsaile** [solid-design-system/solid#390]
## User Story
As a User of the Solid Design System, I would like to have an updated documentation how to customize the colors and see the changes directly in Storybook.

Currently our users can use the following tool to create a color scheme:
https://component-library.dev.fe.union-investment.de/integration/storybook/index.html?path=/story/components-skinning-widget-screenshot-tests--no-attribute

Currently this is missing for the SDS to be able to create different color schemes.

### Suggested Solution
Create a color generator tool similar to https://uicolors.app/create

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by christophsaile** [comment]
I updated the Ticket since the scope and the requirements changed

**Comment by mariohamann** [comment]
@christophsaile We definitely won't provide a Skinning Widget from the very start – I updated the title and content of the ticket to make it more realistic. :)

**Comment by karlbaumhauer** [comment]
interactive part will be extracted into a new ticket.
documentation is enough for the 1st solid release milestone.
