### ISSUE TITLE
ci: 👷 fix dependabot or switch to renovate

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#416]
## User Story
As a developer of the Solid Design System, I would like to have all dependencies regularly updated and checked for vulnerabilities, so that I am sure our project dependencies are secure and well maintained.
### Suggested Solution
As dependabot seems to have issues with `pnpm` (even thought it is supposed to work), I suggest to quickly have a look into possible fixes and, if it cant be fixed right away, switch to [renovate](https://github.com/renovatebot/renovate) as this works fine in the CMS's monorepo with `pnpm`.
## Environment (GitHub Actions or Azure DevOps)
GitHub
## Technical Information
- https://github.com/OWASP/threat-dragon/issues/369
- https://github.com/dependabot/dependabot-core/issues/1736
- https://github.com/dependabot/dependabot-core/issues/6346#issuecomment-1580691400
- See renovate implementation on https://dev.azure.com/Union-Investment/Frontend/_git/union-investment-frontend?path=/.azuredevops/pipelines/renovate.yml&version=GBintegration

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Implementation works successfully on `feature` branch

**Comment by Vahid1919** [comment]
A public discussion that could help with this issue --> https://github.com/dependabot/dependabot-core/issues/6346#issuecomment-1580691400

**Comment by mariohamann** [comment]
If this is not going to be fixed soon, we at least should remove Dependabot and all related PRs as this doesn't show our repo in a good shape.

**Comment by karlbaumhauer** [comment]
@Vahid1919 if you have time and there is nothing left in the milestone to focus on, you could start here... If you need access to the mentioned implementation on azure devops, let me know.
