### ISSUE TITLE
feat: ✨ sd-media-teaser – add component

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#434]
## User Story
As a user of the Solid Design System, I would like to utilize the `sd-media-teaser` component to present information in flexible containers, allowing users to explore collections of related items and actions easily. These teasers should provide a glimpse of information and offer links to access more detailed content.

## API
https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/qP1qJBjApd8H1V9VKmyiaP/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=6462-27893&mode=design&t=K5yaZVXVMlzZI0ly-11
## Hand-off
https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/qP1qJBjApd8H1V9VKmyiaP/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=10880-18451&mode=design&t=K5yaZVXVMlzZI0ly-11
## Figma Documentation
https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/qP1qJBjApd8H1V9VKmyiaP/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=10880-52525&mode=design&t=K5yaZVXVMlzZI0ly-11
## Figma Story:
https://github.com/solid-design-system/solid/issues/553

#### Props
| Status | Name | Type | Default | Description |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <ul><li>[ ] </li></ul>  | `variant` | `gradient-dark` / `gradient-white` / `white` / `primary` / `primary-100` / `neutral-100` | `white` | Allows to adapt the teaser media to their appearance context. |

#### Parts
  - [ ] `base`
  - [ ] every other HTML element (depending on the HTML structure) => NOTE: if highlighting the parts in the `parts` story does not work out of the box, do not spend more effort on it but open a bug ticket to tackle it later.
#### Slots
  - [ ] `media` - for image or video
  - [ ] `meta` - for meta information
  - [ ] `headline` - to add a headline
  - [ ] `expandable` - to add further text between `headline` and `default` slot which will be displayed on hover - NOTE: interactive elements, and texts which are related to the `default` slot content are **_NOT_** allowed as this slot will not be visible on mobile devices.
  - [ ] `default` - default text slot to provide text, interactive elements (buttons, links) and or media copyright.
#### Stories (besides the `default` story)
  - [ ] `variant` - (shows different variants)
  - [ ] `expandable` - (interactive story for screenshot testing)
#### Samples
  - [ ] `expandable` - explains in detail the restrictions from above (slot description)
  - [ ] `links` - explains the different use-cases and how to link the teaser itself **_OR_** add a link to the default slot (no nested links in valid HTML)
  - [ ] `copyright` - shows how to slot a copyright using the `sd-meta`

## Technical Information
- The shadow is quite complex => see ui-teaser for hints and details.

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by coraliefeil** [comment]
@yoezlem I cannot add our issue template content to the description (no rights). Could you do that, pls? Or could you change my rights? Thanks.

**Comment by yoezlem** [comment]
@coraliefeil I will check that..
Which template do you need? 
![image](https://github.com/solid-design-system/solid/assets/98025014/1b6411df-9b35-4c12-ad34-83962ab430d9)

**Comment by yoezlem** [comment]
I guess it will be the New Component Issue, right?
## User Story
As a [PERSONA] of the Solid Design System, I would like to [REQUIRE], as well as [FURTHER_REQUIREMENT],
so that [PRODUCT_VALUE], and [FURTHER_PRODUCT_VALUE].

## API
[LINK TO FIGMA]
## Hand-off
[LINK TO FIGMA]

### Components detailed requirements
- [ ] Props, CSS-Properties, Parts & Slots
  - [ ] tbd
- [ ] Stories
  - [ ] tbd

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch
