### ISSUE TITLE
chore: 🔧 provide Tailwind within CSS (inside .ts and .css files)

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#447]
## User Story
As a developer of the Solid Design System, I would like to be able to use Tailwind in a .ts and .css files, so that code is simplified, easier to maintain and file sizes are reduced.
## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
Related to https://github.com/solid-design-system/solid/issues/448#issuecomment-1755513174
