### ISSUE TITLE
chore: 🔧 integrate PostCSS inside component css-literals

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#448]
## User Story
As a developer of the Solid Design System, I would like to be able to use nesting in css-template literals in components, so that code will be more readable, and easier to maintain.

### Suggested Solution
There's a plugin which can be tested to be used: https://www.npmjs.com/package/postcss-lit

We define a time cap of one working day.

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Implementation works successfully on `feature` branch

**Comment by karlbaumhauer** [comment]
@yoezlem can you give some more insights... (I just created the ticket...)

**Comment by yoezlem** [comment]
sd-radio and sd-radio-group is a good example why it would help us to have the nested feature and the tailwind tokens also in the css part in our components:
**sd-radio:**
<img width="460" alt="image" src="https://github.com/solid-design-system/solid/assets/98025014/93dfd31e-11f5-4cd1-ba77-98cdcf566928">

**sd-radio-group:**
![image](https://github.com/solid-design-system/solid/assets/98025014/7a81b131-b5e5-4265-af88-8ff3468e23ee)

So for this two component, I could save a few lines of css for sure and it would be clearer to read.

**Comment by mariohamann** [comment]
https://www.npmjs.com/package/postcss-lit

This is plugin that exists, but I tested it and it didn't work. This will be really tough one and I'm not sure if it will work. :)
