### ISSUE TITLE
docs: 📚 add bug-hint to Storybook

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#463]
## Description
As a user of Storybook, I would like to quickly know how to handle a bug I just found while going through the library. Therefore I suggest to add a line of text to the top-bar in storybook that says:
"Did you find a bug? Please check the [Know Browser Issues](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/index.html?path=/docs/docs-general-known-browser-issues--docs) before you report an issue on [Jira](https://jira.apps.union-investment.de/browse/PSOLIDDS) or [GitHub](https://github.com/solid-design-system/solid/issues)."
## Where to put the documentation
Storybook

## Technical Information
Storybook offers to write custom addons to implement something like this: https://storybook.js.org/docs/react/addons/writing-addons

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
Yeah. Would be nice if we could add this at one single place for everywhere. Love the idea.
