### ISSUE TITLE
fix: 🤔 misaligned start icon

### ISSUE THREAD

**Issue by Vahid1919** [solid-design-system/solid#467]
## Current behavior
The "start" icon is misaligned within its frame. This makes it necessary to introduce a translate when it is used like in sd-video ( #451 ).  Fix the icon's placement itself (eg: using padding) and remove the added translation in sd-video ( #451 )

## Expected behavior
The icon appears centred without having the need to add additional styling like translations. 

## Technical Information
- Find the "start" icon here --> `packages/components/src/components/icon/library.system.ts`
- Align the icon within it's frame

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
@Vahid1919 Would you mind trying this out with the following (unoptimized: https://jakearchibald.github.io/svgomg/) SVG:

```html
<svg width="64" height="64" viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M57.44 29.7599L20.1067 5.75987C19.6987 5.49587 19.2027 5.33854 18.6667 5.33854C17.1947 5.33854 16.0027 6.53054 16 7.99987V55.9999C16 57.4719 17.1947 58.6665 18.6667 58.6665C19.2027 58.6639 19.6987 58.5065 20.1173 58.2345L20.1067 58.2399L57.44 34.2399C58.1627 33.7545 58.632 32.9412 58.632 32.0185C58.632 31.0959 58.1627 30.2799 57.448 29.8025L57.4373 29.7972L57.44 29.7599ZM21.3333 51.1119V12.8905L51.0667 32.0025L21.3333 51.1119Z" fill="#00358E"/>
</svg>
```

**Comment by Vahid1919** [comment]
> @Vahid1919 Would you mind trying this out with the following (unoptimized: https://jakearchibald.github.io/svgomg/) SVG:
> 
> ```
> <svg width="64" height="64" viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg">
> <path d="M57.44 29.7599L20.1067 5.75987C19.6987 5.49587 19.2027 5.33854 18.6667 5.33854C17.1947 5.33854 16.0027 6.53054 16 7.99987V55.9999C16 57.4719 17.1947 58.6665 18.6667 58.6665C19.2027 58.6639 19.6987 58.5065 20.1173 58.2345L20.1067 58.2399L57.44 34.2399C58.1627 33.7545 58.632 32.9412 58.632 32.0185C58.632 31.0959 58.1627 30.2799 57.448 29.8025L57.4373 29.7972L57.44 29.7599ZM21.3333 51.1119V12.8905L51.0667 32.0025L21.3333 51.1119Z" fill="#00358E"/>
> </svg>
> ```

@mariohamann This version IS centred. I can optimise it and make a PR. 

One question though: is the height and width necessary?
