### ISSUE TITLE
feat: sd-inline-error

### ISSUE THREAD

**Issue by abudd1094** [solid-design-system/solid#501]
## Description

We need to create a wrapper component that enables consistent and user-friendly inline error messages for form elements, such as `sd-input` and `sd-checkbox`, within our web component library. This wrapper component will enhance the user experience by providing a unified approach to displaying validation errors for various input elements.

## Requirements:
1. **Component Name:** The wrapper component should be named `sd-inline-error`.

2. **Usage:** Developers should be able to wrap individual form elements (e.g., `sd-input`, `sd-checkbox`) with the `sd-inline-error` component.

3. **Error Message Display:** When a wrapped form element contains validation errors, the `sd-inline-error` should display an inline error message near the form element. The error message should be easily customizable, including text and styling.

4. **Error Styles:** The error message should be clearly distinguishable from the normal state of the form element, using appropriate visual cues, such as text color and/or icons. We should provide default error styles that can be easily overridden or extended.

5. **Validation Integration:** The `sd-inline-error` should work seamlessly with existing validation mechanisms within our library, such as validation functions or attributes like `required`, `pattern`, etc.

6. **Accessibility:** Ensure that the `sd-inline-error` component adheres to accessibility standards, including ARIA attributes, to support screen readers and assistive technologies.

7. **Customization:** Allow developers to customize the error message content, position, and styling, if necessary.

```html
<sd-inline-error>
      <sd-input name="username" required></sd-input>
</sd-inline-error>
```

## Child Components

Figma designs are linked:
- [sd-input](https://www.figma.com/file/xSIeTnyfW2T21Uw5JgdZOg/Input?type=design&node-id=702-6448&mode=dev)
- [sd-checkbox](https://www.figma.com/file/Q7E9GTBET7Gs2HyH1kbpu5/Checkbox-%2F-Checkbox-Group?type=design&node-id=1046-2361&mode=dev)
- [sd-checkbox-group](https://www.figma.com/file/Q7E9GTBET7Gs2HyH1kbpu5/Checkbox-%2F-Checkbox-Group?type=design&node-id=1083-2406&mode=dev)
- [sd-radio-group](https://www.figma.com/file/LP6fOKJjWupBBAL0rylL7H/Radio-%2F-Radio-Group?type=design&node-id=680-2161&mode=dev)
- [sd-text-area](https://www.figma.com/file/07Bzd23A0QSrSWiXy6w2uM/Text-Area?type=design&node-id=702-6820&mode=dev)

## Acceptance Criteria:

- [ ] `sd-inline-error` accepts a child element (specified above)
- [ ] style meets requirements outlined in Figma
- [ ] stories demonstrate use case for each possible child
- [ ] use cases have corresponding Jest tests

## Resources:
https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation

**Comment by coraliefeil** [comment]
Can we push this to "Ready for Refinement"?

**Comment by karlbaumhauer** [comment]
@mariohamann pls reformulate this according to the newest approach not using a wrapper component

**Comment by karlbaumhauer** [comment]
priority set to urgent as urgently needed.

**Comment by mariohamann** [comment]
Yes, please proceed with that. Thanks!

**Comment by abudd1094** [comment]
I am closing this issue after updating #631 with the relevant information.
