### ISSUE TITLE
fix: 🤔 sd-button type="submit" seems not to working in a form

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#520]
**We received a bug report via Jira. The following issue was identified:**

## Expected behavior
I have a form.
My form contains text fields and the <sd-button> with type="submit".

When the user presses "Enter" in the text field, the presence of the button with type="submit" should trigger the form submission.

## Current Behavior:

> Nothing happens, as if there were no button with type="submit" present.
> 
> Note:
> If I use a standard HTML button with type="submit", everything works smoothly, and the form is submitted when I press "Enter."
> 
> Could it be that the form cannot locate the submit button when it is within the web component? Does type="submit" not work for web components? Do I need additional hidden inputs with type="submit, or hidden buttons with type="submit?
> 
> In summary, is this a user error or an issue within the library's components?
> 
> This code does NOT work:
> `<sd-button class="tw-block tw-mt-2" variant="primary" size="md" type="submit">SUBMIT</sd-button>`
> 
> However, this code does work:
> `<button type="submit">SUBMIT</button>`

## Technical Information
Google Chrome Version 118.0.5993.117 (Official Build) (arm64) with MacBook Pro 14" 2023 and Apple M2 Max Chip

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
I've created a minimal reproduction where it works: https://codepen.io/mariohamann/pen/BaMWJqJ

I responded in the JIRA ticket and hope to get some further feedback there.

**Comment by mariohamann** [comment]
I closed the JIRA ticket as it is more an issue of the `ui-input` and not of our components. :)
