### ISSUE TITLE
docs: 📚 improve sd-dropdown docs

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#522]
## Description
It seems to be not clear enough how the component handles the closing feature. From the docs it is not clear which events from which components are necessary to get the dropdown closed (e.g. sd-selected-event from select-option element).

reference: https://teams.microsoft.com/l/message/19:sycqZKo6K_-P5eYh0H4Xn2UpoKmti8Ar5SICMb9z7C41@thread.tacv2/1699443320239?tenantId=2eb07b91-f9f8-437b-a89e-59f55e565c11&groupId=cec93f98-ceee-42bd-bfde-a6b51fc1194e&parentMessageId=1699443320239&teamName=Solid%20Design%20System%20Community%20(Team)&channelName=General&createdTime=1699443320239

## Where to put the documentation
Storybook
## DoR
- [x] Item has business value
- [ ] Item has been estimated by the team
- [x] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by karlbaumhauer** [comment]
@mariohamann could you add some more technical details, what we need to change here?

**Comment by mariohamann** [comment]
A big issue here was, that our methods didn't show up in Storybook. They do now:

![CleanShot 2024-05-08 at 18 17 53@2x](https://github.com/solid-design-system/solid/assets/26542182/eb965339-9d11-4432-a2d5-3e3514d5e58a)

With that you can now easily see, that you can close the dropdown with the `hide()` method:
https://codepen.io/mariohamann/pen/XWwrGLv

Therefore I would like to close this ticket. Feel free to reopen, if you feel better with that, but I think the method docs are sufficient.
