### ISSUE TITLE
feat: sd-steps – add new component

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#547]
A progress steps component is needed.

sd-progress-steps V.0.0.1

- [x] [Figma Comp](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/qP1qJBjApd8H1V9VKmyiaP/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=2573-18784&mode=design&t=KYgSvIXYa16GcobA-11)
- [x] [Figma refactored branch](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/XQ86g7rO9VAF1zCeb3fMlh/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=2573-18784&mode=design&t=QzHmGsz6GqI0jxVp-11)
- [x] Figma Hand-off
- [x] Figma Documentation
- [ ] Release note

--

Needs refinement:

Have a look into the vertical version, if we will do it all at once or add vertical orientation at a later point.

Request: 
Progress Steps – Vertical, mit Subtext -> wird mitgedacht, aber nicht in V1 enthalten sein 

Draft:
https://www.figma.com/file/RQSSKJKUI90k21fK8DDK3q/Progress-Steps?type=design&node-id=1021-13214

**Comment by karlbaumhauer** [comment]
open questions from pre-refinement: 
- Show edge cases 
- More text
- How elements float with more text and how much space they eat up.

**Comment by karlbaumhauer** [comment]
Results from pre-refinement:
- we will offer horizontal AND vertical variant in one component

**Comment by coraliefeil** [comment]
@van-nguyen-ht pls see last comment and open up a branch to refactor/update comp incl. vertical variants. Merci

**Comment by van-nguyen-ht** [comment]
@coraliefeil may I ask if we implement also the right variant for the horizontal?

**Comment by coraliefeil** [comment]
@van-nguyen-ht I added some comments in the figma branch. just a few little things. Thanks a lot. Look pretty good.

**Comment by van-nguyen-ht** [comment]
alright thank you for your comment, then I'll label it as "waiting for dev"

**Comment by karlbaumhauer** [comment]
@van-nguyen-ht 
Do I miss something in figma or is the focus style missing here?

@EllaELSA / @coraliefeil the current ui-component has the "showFirstEllipsis" and "showLastEllipsis" property to display an ellipsis on mobile, in case the space does not fit to all steps. Did we discontinued this feature as well (like the cornered feature) or is this missing in figma?

**Comment by coraliefeil** [comment]
I left some comments for you @van-nguyen-ht

**Comment by coraliefeil** [comment]
@karlbaumhauer pls provide a link where we can see the described behavior ... I could not inspect it [here](https://component-library.dev.fe.union-investment.de/integration/storybook/index.html?path=/story/components-progress-steps--configurable&args=activeStep:2;variantWhite:!true;cornered:!false&globals=backgrounds.value:!hex(F6F6F6))
Thanks

**Comment by karlbaumhauer** [comment]
> @karlbaumhauer pls provide a link where we can see the described behavior ... I could not inspect it [here](https://component-library.dev.fe.union-investment.de/integration/storybook/index.html?path=/story/components-progress-steps--configurable&args=activeStep:2;variantWhite:!true;cornered:!false&globals=backgrounds.value:!hex(F6F6F6)) Thanks

unfortunately the whole story is broken. You need to resize the window to a very small viewpoint you see the "broken" behavior, which we might need to include (not broken). For more information, see the description on the properties "showLastEllipsis" & "showFirstEllipsis".

From what I understand, the component shows an ellipsis if the space does not fit for all items...
