### ISSUE TITLE
docs: sd-qr-code – add documentation

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#551]
qr-code will be deprecated. Teams can use https://shoelace.style/components/qr-code to impl. a qr-code

## To do:

- [x] Figma: Deprecate sd-qr-code
- [x] Storybook Migration guide

**Comment by coraliefeil** [comment]
Should this still be a solid comp?

**Comment by yoezlem** [comment]
Needs to be discussed!

**Comment by coraliefeil** [comment]
I would like to remove this from the library and discuss that in the next pre-refinement. @yoezlem

**Comment by van-nguyen-ht** [comment]
@yoezlem I've already deprecated in Figma, now I hand over to you for the migration guide.
