### ISSUE TITLE
sd-play-button – refactor as subcomp

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#552]
To do (Figma only): 

- [x] Refactor component to serve as a subcomponent that is only used inside sd-media/video
- [x] Relocate docs from sd-play-button to sd-media/video
- [x] Publish updated sd-media
- [x]  Publish updated sd-video with _sd-video/playbutton
- [x] Add (deprecation) info to release notes.

**Comment by coraliefeil** [comment]
I would like to talk about this design comp ... we don’t have it in storybook and we use it more as a subcomponent in sd-video.

Guess this can be potentially refactored as such.

@yoezlem 
@karlbaumhauer

**Comment by van-nguyen-ht** [comment]
[Figma Branch ](https://www.figma.com/file/bmXfiOfGDL5Z2uIkY56rYj/sd-play-button--%3E-nested-comp?type=design&node-id=1664-16133&mode=design
)

**Comment by coraliefeil** [comment]
I left some comments in the [Figma Branch](https://www.figma.com/file/bmXfiOfGDL5Z2uIkY56rYj/sd-play-button--%3E-nested-comp?type=design&node-id=1664-16133&mode=design)

**Comment by mariohamann** [comment]
Not sure what I can add here. As long as you don't publish this sounds just like an internal refactoring.

**Comment by van-nguyen-ht** [comment]
@mariohamann oh Mario, there's a question Coralie for you as she couldn't find the focus on play button in [storybook](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/iframe.html?args=&globals=&id=components-sd-video--mouseless&viewMode=story)

**Comment by yoezlem** [comment]
@coraliefeil @van-nguyen-ht please estimate the ticket.

**Comment by coraliefeil** [comment]
Estimated 2 SP.

@van-nguyen-ht No, that was not my question.

@mariohamann pls see [my question here ](https://www.figma.com/file/bmXfiOfGDL5Z2uIkY56rYj?type=design&node-id=23391-42614&mode=design#791779275)

**Comment by mariohamann** [comment]
Answered. :)

**Comment by van-nguyen-ht** [comment]
@coraliefeil since Mario is already clarified, shall I publish this update?

**Comment by coraliefeil** [comment]
yes, pls ship it. Thanks a lot ;)
