### ISSUE TITLE
feat: ✨ sd-teaser-media – add component

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#553]
## User Story
As a user of the Solid Design System, I would like to have 1 teaser comp showing an image in the background, as well as clear usage guidelines, so that I know exactly when to use which teaser comp.

### Suggested Solution

Combine sd-teaser-full-image and sd-teaser-full-image-centered to reduce complexity into just 1 component.

Component name and version number: 
sd-teaser-media V.1.0.0

### Components detailed requirements
- [x] Variants, Props, Slots 
  - [ ] tbd
- [x] Samples
  - [ ] tbd
## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified
## DoD
- [x] Brand approval (if neccessary)
- [x] Figma documentation file incl. hand-off has been created/updated (if applicable)
- [x] Tokens have been applied/updated (if applicable)
- [x] Crosslinks are created/updated
- [x] Implementation works successfully on `figma` branch
- [x] Published in Figma and communicated in release notes
- [x] Issues for dependencies have been created (if neccessary)

[Figma Branch](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/qP1qJBjApd8H1V9VKmyiaP/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=6462-27893&mode=design&t=8ARXhKQyjsc6nh8l-11)

**Comment by coraliefeil** [comment]
Crosslinks need to be added after code comp is released

**Comment by coraliefeil** [comment]
@van-nguyen-ht pls update all links (storybook was missing) and add the comp to the overview page
also did you publish renamed media teaser?
When all is done pls close this issue. thx

**Comment by van-nguyen-ht** [comment]
@coraliefeil yes the task is done, I'll close this issue.
