### ISSUE TITLE
docs: breakpoint

### ISSUE THREAD

**Issue by van-nguyen-ht** [solid-design-system/solid#554]
Adding to documentation information on responsiveness i.e.: Breakpoints indicated in component property.

[Figma Documentation](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-–-Component-Library?type=design&node-id=24059-13837&mode=design&t=28TIBq5ijpA1ANNO-11)

**Comment by van-nguyen-ht** [comment]
@yoezlem Hello Özlem, since I have no more tasks and I have time now, can I take care of this ticket in this iteration?

**Comment by yoezlem** [comment]
Sure.
But please estimate it before putting it into our current iteration!

**Comment by van-nguyen-ht** [comment]
this worths a minimum so I'll put 2

**Comment by coraliefeil** [comment]
Could you review Van‘s docs in thehttps://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-–-Component-Library?node-id=24059-13837&t=PZ5UuibpocB0FhA1-11, pls? THX

**Comment by van-nguyen-ht** [comment]
@karlbaumhauer thank you, I added the details according to your comments.
