### ISSUE TITLE
feat[design]: ✨ implement sd-pagination component

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#557]
## User Story
As a stakeholder of the Solid Design System, I would like to utilize sd-pagination, so that I can split up information over multiple pages.

### Suggested Solution
Approved by brand: [Figma Branch](https://www.figma.com/file/LiEAPa5PkSJyjkyAE9RNsi/sd-pagination-V.0.0.1?type=design&node-id=9401-33&mode=design)

Please see if that can be build using sd-interactive.
Maybe sd-interactive needs to get a current state (black number + green bar below).
Could also be used in the carousel as well for the current slide.
But keep in mind that we also have sd-breadcrumb where the current page should look different (additional text color, no green accent)

Used by: 
[sd-carousel
](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/LiEAPa5PkSJyjkyAE9RNsi/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=9280-15296&mode=design&t=i2BZsU3uZaYkQwhC-11)

Component name and version number: 
sd-pagination V.0.0.1

### Components detailed requirements
- [x] Variants, Props, Slots 
  - [ ] tbd
- [x] Samples
  - [ ] tbd
## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified
## DoD
- [x] Brand approval (if neccessary)
- [x] Figma documentation file incl. hand-off has been created/updated (if applicable)
- [x] Tokens have been applied/updated (if applicable)
- [ ] Crosslinks are created/updated
- [x] Implementation works successfully on `figma` branch
- [ ] Published in Figma and communicated in release notes
- [ ] Issues for dependencies have been created (if neccessary)

## Questions

- [ ] Shoelace does not offer a pagination comp. Found one on [Ant Design](https://ant.design/components/pagination). Is there a code base dev would like to build on?

- [x] I’m wondering what exactly should happen when people click on the "..." ... in Ant Design Buttons left/right show on hover leading to hidden pages ... not sure what the best UX / easiest implementation should be.
-> On a second thought ... we don’t need the truncation (...) to be functional at all. We’ll omit that and keep it very basic.

- [x] Use sd-interactive for numbers?

**Comment by van-nguyen-ht** [comment]
Hello @coraliefeil and @mariohamann I did some research and I propose if the ellipsis (...) doesn't have to be interactive and mainly to indicate further pages, perhaps we can set the rule as:

-If there's not enough space: always show the first, current and last page. The ellipsis should be shown next to the last number of either ends
![Screen Shot 2023-11-24 at 10 48 25](https://github.com/solid-design-system/solid/assets/118520877/bd04dcef-144c-4001-a43b-f39b523266d9)

-Or if the ellipsis could be gotten rid of altogether like the design of the carousel variant number?
![Screen Shot 2023-11-24 at 12 53 41](https://github.com/solid-design-system/solid/assets/118520877/e65e4639-c02b-4f01-b0a0-316e62a9d67e)

**Comment by van-nguyen-ht** [comment]
> Especially those two conflict a lot:
> 
> ![CleanShot 2023-11-13 at 09 08 32](https://private-user-images.githubusercontent.com/26542182/282399924-120af2a7-0b61-42cc-a54b-8a8a22f0f2a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA3MzM1MDMsIm5iZiI6MTcwMDczMzIwMywicGF0aCI6Ii8yNjU0MjE4Mi8yODIzOTk5MjQtMTIwYWYyYTctMGI2MS00MmNjLWE1NGItOGE4YTIyZjBmMmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTIzVDA5NTMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjODY2MjRjNmNhMjYwYmUxZjIyOTFmNjA3MWZkOTIyYWNiZGVhYzc3NDljZDI0MTA0NTk0NTNkZDk5YTcwMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1mRfMf0oOsd1XdMC5wwo2RNffpIDJULFniormc-18Ew)

I found the [example](https://nextui.org/docs/components/pagination) in Next UI, they use the ellipsis as a forward control

**Comment by coraliefeil** [comment]
There is no interactivity needed. Like I said before.

> On a second thought ... we don’t need the truncation (...) to be functional at all. We’ll omit that and keep it very basic.

**Comment by coraliefeil** [comment]
@van-nguyen-ht pls add explanation [to this concept](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/LiEAPa5PkSJyjkyAE9RNsi/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=9401-34&mode=design&t=LrzW46Q66XY16yeK-11).
THX

**Comment by van-nguyen-ht** [comment]
@mariohamann @coraliefeil would you mind helping reviewing the [component](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/LiEAPa5PkSJyjkyAE9RNsi/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=15933-1169&mode=design&t=GyHh2lMuk8xPAIHN-11)? Thank you very much!

**Comment by coraliefeil** [comment]
I left comments in the figma branch... I suggest @mariohamann is reviewing after they are implemented.

**Comment by van-nguyen-ht** [comment]
Hi Mario, I resolved Coralie's documentation comments. Can you review? Thank you

**Comment by van-nguyen-ht** [comment]
thank you @mariohamann I've updated the documentation from your feedbacks.

**Comment by yoezlem** [comment]
@van-nguyen-ht what else needs to be done here? Only releasing the component? I would create another Ticket for that und would close this one as I created a parent Epic Story for this subtask.
