### ISSUE TITLE
feat: ✨ sd-dialog - adjust default slot

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#560]
## User Story

As a stakeholder of the Solid Design System, I would like to see design & code pariety as much as possible, so that I can work effectively with the system having a clear and common understanding. 

### Suggested Solution

Serving #229 as basis

- [x] [Figma Branch](https://www.figma.com/file/WwLYG6UHIUUGGKa59tjGhJ/sd-dialog-V.0.0.2?type=design&node-id=1559-15353&mode=design)

Component name and version number: 

sd-dialog V.1.0.0

### Components detailed requirements

- [x] Variants, Props, Slots 
  - [x] default slot
  - [x] Renamed closable boolean to “close-button” due to dev perspective (That does not affect other cloasble booleans we already have!
  - [x] Add footer slot with default primary button.
- [x] Samples
  - [x] Add sample with button group secondary + primary
  - [x] Add sample without close button and document that the close action as well as the focus state then has to be on the primary button.

## DoR

- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Brand approval (if neccessary)
- [x] Figma documentation file incl. hand-off has been created/updated (if applicable)
- [x] Tokens have been applied/updated (if applicable)
- [ ] Crosslinks are created/updated
- [x] Implementation works successfully on `figma` branch
- [x] Published in Figma and communicated in release notes
- [ ] Issues for dependencies have been created (if neccessary)

**Comment by coraliefeil** [comment]
@van-nguyen-ht you can publish this one as soon as you have time for it. Code comp is almost done and will be published shortly. Thank you.

**Comment by van-nguyen-ht** [comment]
The component is published
