### ISSUE TITLE
feat: ✨ add new status badge (CSS style component)

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#566]
## User Story
As a user of the Solid Design System, I would like to have a status badge which I can use to show a certain status in my design. 

## Stakeholder Request
[Jira ticket](https://jira.apps.union-investment.de/browse/PSOLIDDS-10)

### Suggested Solution

[Design Draft Figma Branch](https://www.figma.com/file/oBzkYMYK7uA0j0aO5qIBYF/sd-badge?type=design&node-id=16050-1113&mode=design)

In code it can be a css style component.

### Component name and version number:

sd-status-badge V.1.0.0

### Components detailed requirements
The component consists of a colored circle background with a white status asset on top.
Status assets are another, internal categorie we use as icons in our solid components.
Status assets are neither content icons nor system icons and need to be implemented as such in Storybook.
Status assets can be swapped according to the desired status (exclamation, clock, ...)
Additionally a text can be shown on the right hand side (maybe only shown as a sample?)

#### Styles
| Status | Name | Type | Default | Description |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <ul><li>[ ] </li></ul>  | `&--variant` | `success` / `warning` / `error` / `info` | 

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified
## DoD
- [x] Brand approval (if neccessary)
- [x] Figma documentation file incl. hand-off has been created/updated (if applicable)
- [x] Tokens have been applied/updated (if applicable)
- [ ] Crosslinks are created/updated
- [x] Implementation works successfully on `figma` branch
- [ ] Published in Figma and communicated in release notes
- [ ] Issues for dependencies have been created (if neccessary)

**Comment by coraliefeil** [comment]
@karlbaumhauer could you pls consolidate this issue here with #51 THX

**Comment by karlbaumhauer** [comment]
As agreed with @coraliefeil, I renamed the prop and values to match a more generic usage of colors.

**Comment by coraliefeil** [comment]
Pls review if the updated description here reflects what we discussed today. Thank you!

**Comment by mariohamann** [comment]
I'm not sure what to review here. Please re-assign. And: Shouldn't it be either `variant` or `color˙?

**Comment by mariohamann** [comment]
Reads find to me. I just have concerns, that we violate our principles `Reusable` and `Maintainable` with this compenent instead of improving the other one but if you're 100% it's worth it...

**Comment by coraliefeil** [comment]
I looked into [Atlassian DS ](https://www.figma.com/community/file/1182078880306369227/ads-components)and they have a badge comp with numbers only ... like we have it.
And for status badges they define them as parts ... if you look into avatar comp or flag comp for example.

**Comment by coraliefeil** [comment]
Did I miss to assign you in my last comment?

Do you still have concerns? I’m quite confident to proceed according to latest agreements.

**Comment by mariohamann** [comment]
In general yes, but as said, if you think it's worth it, let's do it.

**Comment by coraliefeil** [comment]
@mariohamann could you review this, pls? Thank you.

**Comment by coraliefeil** [comment]
@mariohamann is your review done, right?

**Comment by coraliefeil** [comment]
@yoezlem I would like to publish this thingy prior to the code as we are not expecting any breaking changes during code phase. Are you ok with that?
