### ISSUE TITLE
feat: refactor sd-input according to code comp

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#570]
## User Story
As a stakeholder of the Solid Design System, I would like to see code and design components in sync as far as possible, so that design and dev share the same basis, and products can be developed fast and effectively.

### Suggested Solution
Refactor design component while coding.

### Component name and version number:
sd-input V.1.0.0

[Figma Branch](https://www.figma.com/file/UPenHXItO4QfghNFBgiHCg/sd-input-V.1.0.0?type=design&node-id=29-78&mode=design)

### Components detailed requirements
- [x] Variants, Props, Slots
  - [ ] tbd
- [x] Samples
  - [ ] tbd
## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified
## DoD
- [x] Brand approval (if neccessary)
- [x] Figma documentation file incl. hand-off has been created/updated (if applicable)
- [x] Tokens have been applied/updated (if applicable)
- [x] Crosslinks are created/updated
- [x] Implementation works successfully on `figma` branch
- [x] Published in Figma and communicated in release notes
- [x] Issues for dependencies have been created (if neccessary)

**Comment by van-nguyen-ht** [comment]
@coraliefeil corali
I handed it over to you.
