### ISSUE TITLE
feat: sd-map-marker – add component

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#573]
Map marker components are needed.

[description]

sd-map-marker V.0.0.1

[figma link]

- [x] Clarify Requirements
- [x] Figma Component Draft
- [x] Brand Approval
- [x] Figma Component Refined (incl. Tokens)
- [ ] Figma Test
- [ ] Figma Review
- [ ] Figma Release

Storybook:

Surrounding map (am besten mit Typ "bar" testbar) https://component-library.dev.fe.union-investment.de/feat_PB2B-5245-create-map-marker-component/storybook/index.html?path=/story/components-surrounding-map--configurable&args=placeType:bar&globals=backgrounds.value:!hex(F6F6F6)

MapMarker (am besten oben auf "Docs" klicken): https://component-library.dev.fe.union-investment.de/feat_PB2B-5245-create-map-marker-component/storybook/index.html?path=/story/components-mapmarker--default&globals=backgrounds.value:!hex(F6F6F6)

**Comment by coraliefeil** [comment]
Could you bring the design comp into a good shape, pls? Thank you.

**Comment by van-nguyen-ht** [comment]
@mariohamann Hi Mario, I saw questions & comments on the file like image inside and blue variant, the storybook doesn't have that so I'm wondering if that's needed to be implemented?

**Comment by van-nguyen-ht** [comment]
@mariohamann another question is would this component has a focused state? I read [here] that it could be made accessible (https://developers.google.com/maps/documentation/javascript/markers)

**Comment by van-nguyen-ht** [comment]
per discussion with @mariohamann in Daily, component will have these additions:
-hovered & selected state for pin-center variant
-hovered state for cluster variant
-focused state

**Comment by van-nguyen-ht** [comment]
component is ready for review @mariohamann @coraliefeil :)

**Comment by coraliefeil** [comment]
@van-nguyen-ht pls update / fill out issue description according to our issue templates. Merci

**Comment by van-nguyen-ht** [comment]
per discussion with @ella:
-no blue variant for pin 
-only content icon would be used

**Comment by coraliefeil** [comment]
Ah ok, no blue marker then ... alright. Then change it back, pls ;)

Left some comments.

Thank you <3

**Comment by van-nguyen-ht** [comment]
@coraliefeil Implemented what you wrote. I'll put the ticket into Ready to wait for development.

**Comment by coraliefeil** [comment]
@van-nguyen-ht thanks 

Add link to figma branch to this ticket here so we can refine it for implementation.
https://github.com/solid-design-system/solid/issues/308

I’ll get brand approval in the meantime.

**Comment by mariohamann** [comment]
1. I don't know. Doesn't seem to change anything.
2. The other pins are provided by Google Maps itself, while the UI one's are set by the app or whatever. Nothing that has to bother us.
3. Customization is easily doable as shown here: https://mapstyle.withgoogle.com We should maybe more think about providing a theme.
4. Not sure, if we have a way to make it in the shape of the element. Maybe it will look like this, yes.

**Comment by coraliefeil** [comment]
@van-nguyen-ht pls publish the comp. Code comp has been released on Friday.

**Comment by van-nguyen-ht** [comment]
complete, this ticket will be closed after #1006 is closed
