### ISSUE TITLE
docs: 📚 add "Experimental" folder in root path

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#577]
## Description
In order to provide a better overview on "experimental" components in Storybook, I would love to add a separate folder "Experimental" as Audi is doing it in their Storybook but in same level as "components", "styles", "utilies".
This gives the users the possibility to quickly see which components are not stable, instead of opening each component individually.

![Image](https://github.com/solid-design-system/solid/assets/98025014/3f638f6d-a6b2-48ff-b91c-cbf3818e6ff8)

## Where to put the documentation
Storybook
## DoR
- [x] Item has business value
- [ ] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by yoezlem** [comment]
blocked by: [#518](https://github.com/solid-design-system/solid/issues/518)

**Comment by karlbaumhauer** [comment]
Currently we only have the style `sd-list` as experimental component.
In addition to this, the following components are missing the status and version in the docs header:
- sd-link
- sd-tab-group

@mariohamann / @yoezlem is the list actually still experimental? what is the status of the other 2 comps?

**Comment by karlbaumhauer** [comment]
closed as we currently have no experimental components. The idea can be picked up as soon as we have new experimental comps.
