### ISSUE TITLE
ci: 👷 prevent PR checks in draft mode

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#580]
## User Story
As a developer of the Solid Design System, I would like to open up draft PRs without all required checks starting automatically, as well as have them started as soon as draft mode has been removed, so that I can prevent deployments and screenshot test run as long as the PR is still work in progress, and the project can save money and resources.
### Suggested Solution
Evaluate why draft PRs currently trigger all checks and prevent this to happen.
## Environment (GitHub Actions or Azure DevOps)
GitHub
## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
If this works out: Maybe it's possible that Renovate converts PRs to draft, too, when it wasn't able to merge.

**Comment by Vahid1919** [comment]
i found this discussion related to this ticket: https://github.com/orgs/community/discussions/25722


This specific comment seems to be working the best, but also take a look at the following comments about some side effects: https://github.com/orgs/community/discussions/25722#discussioncomment-3248917
