### ISSUE TITLE
ci: 👷 prevent renovate trigger checks multiple times

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#581]
## User Story
As a developer of the Solid Design System, I would like to prevent renovate PRs trigger all checks to run 2 times as soon as the `main` has been updated, so that unnecessary checks are prevented, and the project saves money and resources.
### Suggested Solution
Figure out why the checks run 2 times only on renovate PRs (it does not happen on feature PRs) and prevent it.
## Environment (GitHub Actions or Azure DevOps)
GitHub
## Technical Information
Renovate rebases all PRs as soon as `main` has been updated. This behavior is correct and works as expected. The problem seems to be only as soon as we publish a feature, where sematic-release commits a new version directly to the `main` branch. This seems to be the second trigger in the renovate PRs. 

Easiest way could be deactivating the rebase feature in renovate and rebasing manually in the necessary PRs (especially as the patch and minor versions will be approved and merge automatically and no rebase would happen anyway).

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Implementation works successfully on `feature` branch

**Comment by Vahid1919** [comment]
https://docs.renovatebot.com/configuration-options/#rebasewhen
