### ISSUE TITLE
ci: 👷 reduce chromatic snapshots in PR process

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#582]
## User Story
As a developer of the Solid Design System, I would like to reduce the amount of chromatic snapshots in the PR process by removing automated runs, so that the project can save money and resources, and still has the same testing and security coverage as right now with a full automation.
### Suggested Solution
The first idea for a solution would describe the following process in a PR:

1. Chromatic workflow is set to manual trigger and does not run automatically in a PR
2. Passed chromatic checks are only valid until PR or `main` branch has been updated => new manual trigger is necessary
3. To merge a PR, a passed chromatic check is still required (it seems like the branch protection rule has a feature for this)
4. In Renovate PRs, the chromatic check needs to run automatically in order to use the auto-approve and auto-merge feature

## Environment (GitHub Actions or Azure DevOps)
GitHub
## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Implementation works successfully on `feature` branch

**Comment by yoezlem** [comment]
https://github.com/synergy-design-system/synergy-design-system/pull/235/files
