### ISSUE TITLE
docs: 📚 Document z-index tokens

### ISSUE THREAD

**Issue by Vahid1919** [solid-design-system/solid#583]
## Description
We recently added support for z-index tokens for tailwind (PR: #576, Issue: https://github.com/solid-design-system/solid/issues/521). This should be documented. 

## Where to put the documentation
Storybook -> tokens

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by yoezlem** [comment]
Will be fixed with Ticket: #355 - so I will close this one!
