### ISSUE TITLE
fix: 🤔 Typo in Theme Generator

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#588]
## Current behavior
Typo -> Soid Theme Generator
![image](https://github.com/solid-design-system/solid/assets/98025014/d39f24fe-b90f-42c3-9609-ada9d9d18e23)

## Expected behavior
Fix Typo -> Solid Theme Generator

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by Vahid1919** [comment]
This will be closed by #592
