### ISSUE TITLE
fix: 🤔 string values not being updated in Storybook after clearing them

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#590]
## Current behavior
When removing a string from a value field in Storybook, the respective sample component is not updated.

## Expected behavior
The sample component shows exactly the configuration set with the control fields.

## Steps to reproduce
eg. enter a label in the label-field on the `sd-input` and empty the value afterwards. The label will still be shown.
Can be reproduced with any other component using a string attribute.

## Technical Information
- HTML is updated in the "show code" area in Storybook but the sample above is not
- should be tested with older versions of lit, WC-storybook-helper and Storybook itself

NOTE: 
if this is an internal bug in our project, we fix it. If we have dependencies with other packages, a follow-up ticket should be created to discuss further handling.

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by azraefendic** [comment]
On hold for now, waiting for an update from Storybook.

**Comment by christophsaile** [comment]
fyi: this happens because storybook is not rerendering the component when a control changes. Therefore code that is placed in the connectedCallback, firstUpdate (...) is not triggered again. We have the same issue now in the CMS Project.

**Comment by azraefendic** [comment]
Yeah it's a bug in Storybook.. The last version where it was still working was v7.3.2.

**Comment by Vahid1919** [comment]
This does not seem to be an issue on the latest storybook pre-release version (https://stackblitz.com/github/storybookjs/sandboxes/tree/next/lit-vite/default-ts/after-storybook?file=src%2Fstories%2FButton.stories.ts)

Perhaps we can keep an eye on an update and see if that makes a fix.
