### ISSUE TITLE
feat: ✨ move `sd-chip` & `sd-flag` to style components

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#595]
## User Story
As a user of the Solid Design System, I would like to have the `sd-chip` & `sd-flag` component moved to the set of style components in Figma, so that I have a clear expectation of the component, know where to find it and Figma is aligned with Storybook.
### Suggested Solution
Move the component to the other style components and rename the properties to match the style components naming convention.
## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by van-nguyen-ht** [comment]
duplication of [figma #160](https://github.com/solid-design-system/figma/issues/160) & [figma #159](https://github.com/solid-design-system/figma/issues/159)
