### ISSUE TITLE
docs: 📚 add migration guide for `sd-carousel`

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#604]
## Description
The `sd-carousel` is missing a migration guide from the respective ui-component (Component Library) to our SDS Component.

A migration guide template can be found in the root folder of the repository, under: `templates/migration-guide-template.mdx`

Link to the respective ui-component: https://dev.azure.com/Union-Investment/Frontend/_git/union-investment-frontend?path=/packages/libs/component-library/src/components/ui-slider
## Where to put the documentation
Storybook
## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Migration Guide has been created/updated (if applicable)

**Comment by Vahid1919** [comment]
This is already done -  https://github.com/solid-design-system/solid/blob/main/packages/components/src/docs/Migration/ui-slider.mdx
