### ISSUE TITLE
fix: 🤔 optimize initial validation in form components

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#631]
>NOTE: 
This applies to all form elements / input components. The description below only handles the `sd-input` component as an example.
The fix should be implemented into all necessary components (`sd-switch`, `sd-checkbox`, `sd-radio-group`, `sd-input`, `sd-textarea` & `sd-select`).

## Current behavior
1. When using a required `sd-input` without any user interaction, the field is marked as red. This isn't very friendly UX: https://codepen.io/mariohamann/pen/KKJxXQx
2. When using a required `sd-input` with a prefilled value, the input still shows an error state (red). Only when interacting with the input, the components switches to the success state (green): https://codepen.io/mariohamann/pen/poGOWdO

## Expected behavior
There should be no validation indication until the user interacted with the field. It should never show an invalid/valid state as long as the user didn't interact.

## Technical Information
See https://shoelace.style/getting-started/form-controls#styling-invalid-form-controls for more details about the expected behavior. Especially about the attributes "data-valid" and "data-user-valid" to be used for visual validation states.

## Use-case:
The user builds a contact form, where the (logged in) end-user data is prefilled. The end-user then can edit the values or leave them like they are.
## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

-------------------------------------------------------------------------------------------------------------------------
As of 05.12.2023 we are combining the following ticket with this one: 
https://github.com/solid-design-system/solid/issues/501

We will use the `data-user-valid` and `data-user-invalid` attributes provided by the `formController` to condition our component styles based on form validity state and user interaction.

## Requirements: for each listed component...

- [ ] add private boolean state `showInvalidStyle`
- [ ] add private boolean state `showValidStyle` (if component has valid style)
- [ ] condition validity styles on `this.showValidStyle` and `this.showInvalidStyle`
- [ ] render div at bottom with id "error-message" for displaying inline error
- [ ] add query errorMessage for consistent access
- [ ] update handleInvalid method to display browser validation messages in errorMessage.textContent property

## Components
- [x] `sd-switch` 
- [x] `sd-input`
- [x] `sd-textarea`
- [x] `sd-select`
- [x]  `sd-checkbox`
- [x]  `sd-radio-group` #641 

## Delimitations
- `sd-checkbox-group` is handled in #640

**Comment by mariohamann** [comment]
@coraliefeil Please clarify UX for initial validation.

**Comment by coraliefeil** [comment]
Yes to everything Mario is saying.

**Comment by karlbaumhauer** [comment]
> Yes to everything Mario is saying.

its an OR suggestion... ;-) which expected behavior should be implemented? No validation until user interaction OR as soon as the component has been loaded (added to the page)

**Comment by karlbaumhauer** [comment]
thx @coraliefeil. I changed the description.

**Comment by abudd1094** [comment]
There is no form or validation behavior built into sd-checkbox-group.  The figma design suggests it should behave like a radio group in the context of a form (the difference being a checkbox group can have more than one value selected?):
![image](https://github.com/solid-design-system/solid/assets/39494579/dffca8ef-2b64-4230-81b6-556a269c3b98)

What is the idea here?  Are all of the checkboxes in a checkbox group supposed to conform to one value that is submitted as a single field in a form?  What does the value look like in that case, a space-delimited string like in sd-select?  

Example:
If checkbox 1 (value="value-1") and checkbox 2 (value="value-2") in a checkbox group are selected, the "value" attribute for the checkbox group is a single string equal to "value-1 value-2" ?

For this to be implemented, we need to add all of the relevant form attributes used in the other form elements (form, name, value, required...) to checkbox group.  At the moment, only individual checkboxes give the possibility to be used as individual form fields, which means the design is not possible.

Please advise @solid-design-system/core-development @solid-design-system/design

**Comment by mariohamann** [comment]
Validation should only happen in the checkbox. We don't new things in checkbox-group, it's just for styling.

**Comment by mariohamann** [comment]
We explicitly didn't list checkbox-group in the kist at the top. :)

**Comment by abudd1094** [comment]
> We explicitly didn't list checkbox-group in the kist at the top. :)

The list at the top of what?  This ticket?  There is no list, and in the other combined ticket, I made the list (and it includes sd-checkbox-group).

"We don't new things in checkbox-group, it's just for styling." --- I don't know what you mean, please be more descriptive.  According to the linked design, there would be an asterisk in the label for the checkbox group, not the individual checkbox, and the error text would show up below the group, not the individual checkbox.

Based on your comments @mariohamann , I understand that the design is false, and I should do nothing to further implement it in the checkbox group.

**Comment by mariohamann** [comment]
There is list at the top:

> The fix should be implemented into all necessary components (sd-switch, sd-checkbox, sd-radio-group, sd-input, sd-textarea & sd-select).

Yes, design is wrong. Nothing more to implement in group.
