### ISSUE TITLE
docs: 📚 evaluate restructure of contributing.md

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#632]
## Description
In order to get the last parts missing in the guide, I would like to go through the structure of the new contributing.md from https://github.com/solid-design-system/internal/issues/27 together with @abudd1094 

The goal is to make sure all topics are addressed for new developers in the SDS. 
## Where to put the documentation
GitHub
## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by abudd1094** [comment]
# (SOLID Design Principles in Software Development)[https://www.freecodecamp.org/news/solid-design-principles-in-software-development/]

## What are SOLID Design Principles?
SOLID is a set of five design principles that aid in designing robust, testable, extensible, and maintainable object-oriented software systems. Each principle addresses specific challenges in software development.

- **Single Responsibility Principle (SRP)**
  - A class, module, or function should have only one reason to change, i.e., it should perform a single responsibility.
  - Example: Separating classes for animal information, sound, and feeding.

- **Open-Closed Principle (OCP)**
  - Classes, modules, and functions should be open for extension but closed for modification.
  - Example: Using abstraction to add new animal types without modifying existing code.

- **Liskov Substitution Principle (LSP)**
  - Child classes must be substitutable for their parent classes, ensuring seamless replacement.
  - Example: Dog and Cat classes replacing the parent Animal class.

- **Interface Segregation Principle (ISP)**
  - Clients should not be forced to implement interfaces or methods they do not use.
  - Example: Breaking down large interfaces into smaller, specific ones.

- **Dependency Inversion Principle (DIP)**
  - High-level modules should not depend on low-level modules; both should depend on abstractions.
  - Example: Using abstractions to decouple high-level and low-level modules.

## Conclusion
Implementing SOLID principles leads to a large but maintainable codebase, enabling developers to make changes without causing major issues. These principles contribute to bug-free, flexible, scalable, and reusable software systems.
