### ISSUE TITLE
ci: 👷 make chromatic only run after passed tests and linting

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#639]
## User Story
As a developer of the Solid Design System, I would like to have chromatic only running after all linting and test workflows have been passed successfully, so that "broken" code changes do not trigger any unnecessary screenshot testing, and waste snapshots from our current plan.
### Suggested Solution
https://github.com/synergy-design-system/synergy-design-system/commit/f03eb657822217e20be8cbd9574061e30dea1312
## Environment (GitHub Actions or Azure DevOps)
GitHub
## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
Closed with https://github.com/solid-design-system/solid/commit/6033de1bcaa547fc7cb69e5f20c10fcae8a5da98
