### ISSUE TITLE
fix: 🤔 adopt properties in `sd-list`

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#649]
## Current behavior
The figma file shows multiple properties, the development does not use (due to being a style-component). These properties need to be marked as pure design-properties (*).
## Expected behavior
The component API is aligned with the development sytle-component properties.
## Steps to reproduce
N/A
## Technical Information
N/A
## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by van-nguyen-ht** [comment]
@karlbaumhauer Hi Karl

for sd-list-item I've marked * for **ordered** & **level**

![Image](https://github.com/solid-design-system/solid/assets/118520877/b466980b-b001-461b-aa41-d4d3a7fe4f16)

though I'm not sure what to mark * in sd-list, can you suggest? Thank you

![Image](https://github.com/solid-design-system/solid/assets/118520877/99b3e271-19be-48ca-af66-f0d1a4b0f592)

**Comment by karlbaumhauer** [comment]
@van-nguyen-ht for the list itself it would be the variant, which is a pure figma property.

**Comment by van-nguyen-ht** [comment]
done
