### ISSUE TITLE
fix: 🤔 teaser variant 'white border-neutral-400', - no border around media slot

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#651]
## Current behavior

Teaser variant 'white border-neutral-400' shows a border around the media element / image.

[Link](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/story/components-sd-teaser--variant-and-inset)

## Expected behavior

No border around the image pls. Only around lower part / white area with border left, right, bottom. (No border between media element and white are)

## Technical Information
The media slot should overlap the border (with negative margin or translate calc(100 + 1px)) - probably the most cleanest solution.
## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by saemik94** [comment]
When the media slot is above the text I get the idea (green), but what about the case when the media slot is on the left side (red)?

![teaser](https://github.com/solid-design-system/solid/assets/76621625/cde391c7-50ac-4abc-ab33-bdb792d15ee6)

**Comment by coraliefeil** [comment]
It is hard to see ... the border is not shown around the whole component.
The media slot overlays the border/container.
If no media slot / element is desired the border is shown aroudn the whole component.
![Bildschirmfoto 2023-12-14 um 20 13 27](https://github.com/solid-design-system/solid/assets/41894356/ce4d4278-4f0c-4df5-8b2a-62abce4fcc77)
![Bildschirmfoto 2023-12-14 um 20 14 07](https://github.com/solid-design-system/solid/assets/41894356/546be5d4-031c-471c-8704-befeb2fa7388)

**Comment by karlbaumhauer** [comment]
ok, thx @coraliefeil that makes sense. I will have a look into with @mariohamann later in our pre-refinement and make sure we update the description if necessary.
