### ISSUE TITLE
docs: 🤔 storybook code-view showing source code instead of cleaned up component tags

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#661]
## Current behavior
When opening the "show code" dropdown in the "Default" story of a component, the original source code of the story is displayed.

![Image](https://github.com/solid-design-system/solid/assets/48211526/167041d7-696b-40b7-b740-c6c98cdd4fe7)

## Expected behavior
When opening the "show code" dropdown in the "Default" story of a component, a cleaned up code version of the story is displayed.

![Image](https://github.com/solid-design-system/solid/assets/48211526/9b36b45a-d6d7-4219-b78c-c181eeb5220d)

## Technical Information
Happens since version 1.32.x (or maybe even 1.31.x but this version is not available on the CDN)
This part of the code is taking care of the "cleanup" => https://github.com/solid-design-system/solid/blob/f99d1f4c159cbd2c4d26a675170858590b52a913/packages/components/scripts/storybook/helper.ts#L538-L556
## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by azraefendic** [comment]
I found that this issue comes from adding background colors option in the preview ([see here](https://github.com/solid-design-system/solid/commit/b05a90ce1b392331f3b5c8b1dd991424bf584e24#diff-fa2909f2ae1c2b6b0c3710b27e556083f35005f15d2890089e8d2a431fc4ab43R7-R36)).
It somehow overwrites the default preview and when removed works fine again.
