### ISSUE TITLE
feat: ✨ Create dedicated spacing tokens for 1px

### ISSUE THREAD

**Issue by Vahid1919** [solid-design-system/solid#664]
## User Story
As a Developer of the Solid Design System, I want to enhance the efficiency and maintainability of our codebase by introducing a dedicated spacing token for 1px in the Solid Design System. This will allow me to use a standardised value directly, eliminating the need to rely on arbitrary values which create unnecessary bloat.

Example: We are currently using arbitrary values in sd-teaser #663, and is currently in the development version of sd-tab. 

### Suggested Solution
Create a style(spacing) token for 1px (and more granular values -> could be discussed in refinement) 

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by coraliefeil** [comment]
@van-nguyen-ht you can tackle this one. @yoezlem is fine with it.

**Comment by van-nguyen-ht** [comment]
I created a PR and assigned you @Vahid1919 :)

**Comment by Vahid1919** [comment]
This is resolved by #1152
