### ISSUE TITLE
docs: 📚  Add Subfolders for samples inside components

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#675]
## User Story
As a user of the Solid Design System, I would like to have samples in subfolders within the component to better understand what belongs to a component and what doesn't. Additionally, this would make it more organized and readable, as well as better collaboration with the Design System.

### Suggested Solution
Add subfolders for all components which have samples

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by yoezlem** [comment]
blocked by: [#518](https://github.com/solid-design-system/solid/issues/518)

**Comment by yoezlem** [comment]
@mariohamann since we will no longer add samples in the component section, do we need that ticket or can we close that one?

**Comment by mariohamann** [comment]
We can close it!
