### ISSUE TITLE
docs: 📚 add privacy statement to storybook

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#687]
## Description
In order to cover legal regulations, we need a privacy statement page in our storybook.
As an imprint file will follow, a new "legal" chapter in our storybook needs to be created. This ticket only covers the first page ("privacy") in the legal chapter, and contains the following text:

[sds-privacy.md](https://github.com/solid-design-system/solid/files/13953369/sds-privacy.md)

The legal section from [DB](https://db-ui.github.io/elements/?path=/story/20-legal-datenschutzerklaerung--datenschutzerklaerung) is used as structure sample.

## Where to put the documentation
Storybook
## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by yoezlem** [comment]
Privacy Statement is well written and can be add to our storybook.
Thx @karlbaumhauer
