### ISSUE TITLE
fix: 🤔 navigation-item -> add part selectors to all elements

### ISSUE THREAD

**Issue by awacode21** [solid-design-system/solid#689]
## Current behavior
At the moment it is not possible to access all parts of the navigation-item to adjust styling.
I tried to adjust the styles of the container which wraps the content. But it has no part selector.
Instead the` <slot> `element has the part "content".

Doesn't the "content" part selector sit on the wrong element? shouldn't it be one element above? I think it does not really make sense to set it on the slot, since as a user i have full access to the content i provide for the slot and can style it without any boundaries. So having it there is not very helpful. But having it one element above on the parent of the slot it would make much more sense!

## Expected behavior
To have part selectors for all relevant elements within navigation-item.

## Steps to reproduce
<img width="828" alt="Bildschirmfoto 2024-01-17 um 13 47 27" src="https://github.com/solid-design-system/solid/assets/30939926/d2b9aae0-12e9-4e11-8852-410acd6720a5">
Try to add styles to the container that wraps the content slot. It is not possible as it does not provide a part selector

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
I've just created a PR which you can follow along: https://github.com/solid-design-system/solid/pull/693
