### ISSUE TITLE
feat: ✨ add sd-[COMPONENT_NAME]

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#692]
## User Story
As a [PERSONA] of the Solid Design System, I would like to [REQUIRE], as well as [FURTHER_REQUIREMENT], so that [PRODUCT_VALUE], and [FURTHER_PRODUCT_VALUE].

## Documentation
[LINK TO FIGMA]
## Hand-off
[LINK TO FIGMA]

#### Props
| Status | Name | Type | Default | Description |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <ul><li>[ ] </li></ul>  | `name` | `type` | `default` | description |
| <ul><li>[ ] </li></ul>  | `name` | `type1` / `type2` | `default` | description |

#### Slots
  - [ ] `name` - description
  - [ ] `name` - description

### Open Questions towards development
- [ ] Question1
- [ ] Question2

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Brand approval (if neccessary)
- [ ] Figma documentation file incl. hand-off has been created/updated (if applicable)
- [ ] Tokens have been applied/updated (if applicable)
- [ ] Crosslinks are created/updated
- [ ] Implementation works successfully on `figma` branch
- [ ] Published in Figma and communicated in release notes
- [ ] Issues for dependencies have been created (if neccessary)

**Comment by mariohamann** [comment]
@coraliefeil Closable? :)

**Comment by coraliefeil** [comment]
test
