### ISSUE TITLE
fix: 🤔 form fields - success validation always shows up 

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#695]
## Current behavior
 
default success validation visible when a form filled is filled

![Image](https://github.com/solid-design-system/solid/assets/41894356/b67af41b-5a44-4a2f-9f57-d5aa23c29dbf)

## Expected behavior

![Image](https://github.com/solid-design-system/solid/assets/41894356/7090dc9b-1179-42ec-82db-73559a6156bc)

We need an option, that one can ask for the accepted state and only then it should appear if everything is fine.
 
So error is always showing when there is an error, success only when the attribute is set.

We can't do something like "success" only if something is required as we actually don't know, what the validation is and it could be everything.

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by awacode21** [comment]
I would like to have that feature/fix for my current work.
