### ISSUE TITLE
feat: ✨ delete preferred values for icons (*Figma)

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#699]
## User Story
As a ds maintainer of the Solid Design System, I would like to add new icons with as little effort as possible, so that consumers can find and use also new icons very easily.

### Suggested Solution

Preferred values for icons is not working optimally. When adding new icons to the sets. all components with preferred icon set would need an update which is not practical at all.

As long as Figma does not support any dynamic when adding new icons, this feature should not be used.

Therefore we go trough all comps and delete this feature. And we update the info on where and how to consume icons.

List updated comps:

- [x] sd-button
- [x] sd-dialog
- [x] sd-drawer
- [x] sd-input
- [x] sd-link
- [x] sd-expandable
- [x] sd-navigation-item
- [x] sd-quickfact
- [x] sd-radio-button-group & _sd-radio-button
- [x] sd-teaser's sample/media-02
- [x] sd-teaser-centered
- [x] sd-headline
- [x] sd-header sample lg+md+sm
- [x] sd-list-item
- [x] sd-table's sample-icon

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [x] Implementation works successfully on `feature` branch
- [x] Docs/Guidlines updated
- [x] Published
- [x] Release notes

**Comment by karlbaumhauer** [comment]
@van-nguyen-ht this ticket is closed but still 'in progress'. Pls set either the correct status or re-open the issue.
