### ISSUE TITLE
fix: 🤔 Input based controls do not work in sd-dialog stories

### ISSUE THREAD

**Issue by Vahid1919** [solid-design-system/solid#702]
## Current behavior
While implementing sd-dialog ( #668 ), we realised that input based Controls are not working in the Docs page of the `sd-dialog` story.

![Image](https://github.com/solid-design-system/solid/assets/63849626/a0552006-df03-4d48-b456-7d0fc1c6c9ec)

## Expected behavior
Attribute controls like 'headline' or slots should let you insert text in the controls and show that change in the canvas. They should work the same way they do on the individual stories for sd-dialog. 

## Steps to reproduce
Open the sd-dialog component Docs page and try to use the input-based Controls. (eg: headline attribute, slots, css properties) 

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by yoezlem** [comment]
Duplicate: [#1029](https://github.com/solid-design-system/solid/issues/1029)
