### ISSUE TITLE
feat: ✨ sd-tooltip - add template for label + info-tooltip

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#705]
## User Story
As a stakeholder of the Solid Design System, I would like to see how an info-tooltip works in code, so that I don’t have to figure it out myself.

### Suggested Solution

[Link to Figma Template](https://www.figma.com/design/YDktJcseQIIQbsuCpoKS4V/Component-Docs?node-id=3274-20693&node-type=section&t=SyBWLsQrsSjnJHhx-11)

- [ ]  Add all samples we have in Figma to the Storybook Template
- [ ] Move **sd-tooltip with sd-select** sample from sd-select template to sd-tooltip template
- [ ] Add link to template in the docs of all used components
    - [ ] tooltip
    - [ ] input
    - [ ] textarea
    - [ ] select
    - [ ] check if any others are used and link them as well.
- [ ] Add this template to #1142 

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by yoezlem** [comment]
Dupcliate of: https://github.com/solid-design-system/solid/issues/1437
