### ISSUE TITLE
feat: ✨ add sd-brandshape-image

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#707]
## User Story
As a stakeholder of the Solid Design System, I would like to mask images using the brandshape, so that my visuals look very on brand.

## Open Questions

- [ ] Is this a css style comp or full-fledge comp? 
- [ ] Can this be refactored/built diffrently according to sd-brandshape (top&bottom fixed height, center part can vary - whole form as a mask)?

## Documentation
-> First we need to refactor figma comp and then pass on the ticket for coding.

#### Props
| Status | Name | Type | Default | Description |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <ul><li>[ ] </li></ul>  | `name` | `type` | `default` | description |
| <ul><li>[ ] </li></ul>  | `name` | `type1` / `type2` | `default` | description |

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Brand approval (if neccessary)
- [ ] Figma documentation file incl. hand-off has been created/updated (if applicable)
- [ ] Tokens have been applied/updated (if applicable)
- [ ] Crosslinks are created/updated
- [ ] Implementation works successfully on `figma` branch
- [ ] Published in Figma and communicated in release notes
- [ ] Issues for dependencies have been created (if neccessary)

**Comment by yoezlem** [comment]
@coraliefeil I don't think we can offer that as a pure CSS solution. Earlier, I checked if we could add another property to the existing Brandshape for a background image. However, that doesn't work either because the component currently consists of three parts.

@mariohamann @karlbaumhauer I would recommend that we build a new component. Perhaps we can base it on the sd-brandshape.

Lets talk about that in our Pre-Refinement on friday.

**Comment by karlbaumhauer** [comment]
@mariohamann @yoezlem could we add a style comp with just a svg-mask? This class then could be added to any image and would just mask the image accordingly.

**Comment by mariohamann** [comment]
I incorporated this ticket into https://github.com/solid-design-system/solid/issues/792 so we can close this one.

**Comment by karlbaumhauer** [comment]
closed as covered with #792
