### ISSUE TITLE
docs: 📚 improve sd-notification docs

### ISSUE THREAD

**Issue by christophsaile** [solid-design-system/solid#718]
## Description
The current documentation does not explicitly show that the "toastStack" notifications actually need JS implementation rather than using the `sd-notification` tag inside the HTML. 
A more detailed description on how to implement the toastStack variant of the component would be helpful. 

Currently it only says which attributes should be added to the component itself but the fact, that actually the shown JS is the code which needs to be added, is not mentioned:
![Image](https://github.com/solid-design-system/solid/assets/48211526/32250e74-42be-4ba9-b813-9f98efc2da4b)

When adding just the attributes to the component, it will be shown on the bottom-center of the wrapping container and not on the bottom-center of the screen. This leads to the assumption that a wrapper with the classes shown in the browser HTML, needs to be added.
## Where to put the documentation
Storybook
## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by karlbaumhauer** [comment]
@christophsaile thx for the bug ticket. We will try to fix it asap.

@Vahid1919 any thoughts on this already or is it an actual documentation bug?
