### ISSUE TITLE
fix: 🤔 sd-headline does not include a line-height style

### ISSUE THREAD

**Issue by christophsaile** [solid-design-system/solid#727]
## Current behavior
Currently neither the sd-headline nor the sd-headline--size styles include a line-height.
![grafik](https://github.com/solid-design-system/solid/assets/54807480/92aefe65-6eda-42c9-9581-c4bf2a3121e0)

## Expected behavior
The sd-headlien style includes a line-height style like the sd-paragraph

## Technical Information
see details in [Figma](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=674-13666&mode=design&t=VxS2a2hyTlbIlNBO-11) 
- [ ] sd-headline-text-4xl -> lineHeight: 1.2
- [ ] sd-headline-text-3xl -> lineHeight: 1.2
- [ ] sd-headline-text-xl -> lineHeight: 1.2
- [ ] sd-headline-text-lg -> lineHeight: 1.5
- [ ] sd-headline-text-base -> lineHeight: 1.5
- [ ] sd-headline-mobile-text-4xl -> lineHeight: 1.2
- [ ] sd-headline-mobile-text-3xl -> lineHeight: 1.2

- [x] Please make sure to check also sd-leadtext, sd-display and sd-meta.

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated 
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
@karlbaumhauer @yoezlem @coraliefeil I believe this needs very high priority.

**Comment by coraliefeil** [comment]
Here you can find all headline styles with their dedicated line-height
https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=674-13666&mode=design&t=VxS2a2hyTlbIlNBO-11

all text style tokens come with a line-height ... thats combined in the tokens studio plugin

sd-headline-text-4xl -> lineHeight":"120%"

sd-headline-text-3xl -> lineHeight":"120%"

sd-headline-text-xl -> lineHeight":"120%"

sd-headline-text-lg -> lineHeight":"150%"

sd-headline-text-base -> lineHeight":"150%"

sd-headline-mobile-text-4xl -> lineHeight":"120%"

sd-headline-mobile-text-3xl -> lineHeight":"120%"
