### ISSUE TITLE
Relevant stories (Features, A11y) are created/updated

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#729]

**Comment by karlbaumhauer** [comment]
@mariohamann this was by accident right? Would love to know how you got to this... ;-)

**Comment by mariohamann** [comment]
https://github.com/solid-design-system/solid/issues/727

![CleanShot 2024-02-02 at 12 38 01](https://github.com/solid-design-system/solid/assets/26542182/e224f9ff-38fa-4061-90e9-21ba1ea8c816)


Apparently I clicked on of the action items to open an issue. Oooops.
