### ISSUE TITLE
feat: ✨ add more samples to `sd-teaser`

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#730]
## User Story
As a user of the Solid Design System, I would like to see more `sd-teaser` samples in storybook, so that I can easily copy-paste the code for use-cases which are not a variant of the component but used regularly.

Therefore 2 additional samples should be added:
- [ ] center aligned teaser
- [ ] standard teaser with icon

Figma Updates:

- [x] Add center alignment option to the [figma documentation](https://www.figma.com/file/E8ULo6VaieYcXCC1H0zNF0/Teaser?type=design&node-id=1643-4838&mode=design&t=z0lyoQKyxwlYaLbp-11). 
- [x] Deprecate sd-teaser-centered
- [x] Communicate to use sd-teaser with center alignment instead

See the comments here in the ticket and the sample section in [Figma](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=6473-32846&mode=design&t=RBXa9R4iZYzoWUU1-4).

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by coraliefeil** [comment]
@solid-design-system/development Maybe add it to current or next iteration and deprioritize sth else?

**Comment by coraliefeil** [comment]
@karlbaumhauer like discussed here’s the issue for you to see how this can be done in code. Thanks

**Comment by karlbaumhauer** [comment]
@coraliefeil so its technically possible to build it with the current `sd-teaser`:
![Image](https://github.com/solid-design-system/solid/assets/48211526/d7ae2e8a-d9a9-465a-b87c-8cf7e5e09301)

The things every user would have to change is (spacings are even only guessed at some point):
![Image](https://github.com/solid-design-system/solid/assets/48211526/2fd72a5c-14eb-4680-8f4d-b01e22023b8b)
![Image](https://github.com/solid-design-system/solid/assets/48211526/1c14d7f5-b2bc-4609-ba82-4113d888f142)

So the question if we provide a component needs to be answered.

For me personally, its depending on the following:
1. how often will this be used? if not very often, we could start with a sample => maybe @EllaELSA has some deeper insights here.
2. With the current teaser variants, we only provide "color"-variants and this would be the first component (from what I remember), where we would provide a "functional"-variant. This can be ok, if necessary but does not really follow what we did so far.
3. Technically, I am not sure if we could provide a style component, which can be added to the current teaser and will apply all the changes above. Therewith we could provide a simple solution, which would not mismatch with the approach only to have "color"-variants => @mariohamann is this even possible and/or does this make sense at all? I feel like the changes are quite a lot to make before it looks like its supposed to.

@yoezlem FYI

Maybe you can all add some thoughts here and this time we definitely need to document what we agreed on... ;-)

**Comment by mariohamann** [comment]
I wouldn't provide a style for that. This feels to me like doing the work for others. I would more show this as a sample and give it back to CMS. This proves the flexibility of the basic component even more and reduces work on our side A LOT.

**Comment by karlbaumhauer** [comment]
Edit from pre-refinement:

- This will be a sample in the teaser
- Another sample with standard teaser and icon should be added as well => see collection of samples in [Figma](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=6473-32846&mode=design&t=RBXa9R4iZYzoWUU1-4)
