### ISSUE TITLE
fix: 🤔 replace hard coded opacities with new tokens

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#731]
## Current behavior

Due to missing availability of some opacity tokens, some opacities (like "55", "75", "80", "90") have been hard coded. 

## Expected behavior
As they now have been added with #732, the hard coded values need to be replaced with the respective tokens.

## Technical Information
Mainly to be found in the `sd-teaser-media` but needs to be checked in the whole code base.

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
@coraliefeil

**Comment by coraliefeil** [comment]
We do have the challenge in Figma that we don’t have color token + opacity token but need to use a transparent color token due to how we build/layer the comps.

**Comment by karlbaumhauer** [comment]
@coraliefeil I see only "55", "75" & "80" added in your PR but the original ticket mentioned also "90" as required token. Can you pls double check this and (in case its missing) add the 90 as well? I think more or less all the opacities used in the `sd-teaser-media` component right @saemik94 ?

**Comment by coraliefeil** [comment]
90 was already available ... at least in figma tokens plugin we have it

**Comment by karlbaumhauer** [comment]
> 90 was already available ... at least in figma tokens plugin we have it

@saemik94 can you confirm that?

**Comment by Vahid1919** [comment]
I did a search for custom opacities and did not find any in the ranges mentioned above. 
The only custom opacity is for opacity-[100%] but unfortunately opacity-100 does not exist so it would not make sense to remove them now. I will create a follow up ticket to include opacity-100 and remove those specific hardcoded opacities. 

@mariohamann please let me know if I missed something since you opened this issue.

**Comment by mariohamann** [comment]
Maybe it was already fixed meanwhile. Thanks for taking care!
