### ISSUE TITLE
feat: ✨ add "triangle" property to `sd-container`

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#737]
## User Story
As a user of the Solid Design System, I would like to add a visual triangle to the `sd-container`, so that I can easily rebuild the visual experience of the current `ui-cms-text-infobox` component.

### Documentation
[Figma Branch](https://www.figma.com/file/1HEtYBfo8XZrvOE0plRosK/sd-container---add-triangle?type=design&node-id=1664-15968&mode=design)

#### Props
| Status | Name | Type | Default | Description |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| <ul><li>[ ] </li></ul>  | `--triangle-` | `left` / `right` / `top` / `bottom` | `none` | define the position of the triangle cut-out |

#### CSS-Properties
  - [ ] `triangle-background` - defines the background color of the triangle as the default is white and the container can be added on another background.

#### Stories

- [ ] Triangle - shows the cut-out on each side.

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by karlbaumhauer** [comment]
@coraliefeil pls add a respective Figma link as soon as you can provide something. 

should we use this ticket for design as well or do you want to have another one?

**Comment by coraliefeil** [comment]
Will do - thx. We can use this ticket here.

**Comment by karlbaumhauer** [comment]
as discussed with the PO (Team CdA) today, @abudd1094 might be starting with this one in the next days. In case we dont have the design ready at this point, we might need to clarify the specs on the run. 

The current cms component implementation can be used as design basis, as long as you will not be changing much. Maybe @coraliefeil you can have a look into it asap and let us know if the specs (size, color etc) will stay as currently implemented and then we will have more time to add the Figma component.

**Comment by coraliefeil** [comment]
Ready for pre-refinement.
