### ISSUE TITLE
docs: 📚 refactor `sd-icon` implementation docu

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#752]
## Description
For starters working with the SDS, the documentation about how to use the `sd-icon` could be improved and restructured.

### Suggestion
The information is all there, but the overview suffers because each point is divided into the 4 possible options.

Suggestion: Structure of [Docs/General/Installation](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/docs-general-installation--docs) into 4 options:

    CDN + Unversioned 
    CDN + Versioned 
    Package + Unversioned 
    Package + Versioned 
Each with a decision aid (pro/contra). Then the necessary Todos in each option.

Include registerIconLibrary() directly in the above Todos (instead of currently hidden in sd-icon). Prefer reference from sd-icon to above Docs/General/Installation.

## Where to put the documentation
Storybook
## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by rolbr** [comment]
Die Infos sind eigentlich alle da, nur leidet die Übersicht, weil jeder Punkt in die 4 möglichen Optionen unterteilt wird.

Vorschlag: Gliederung von [Docs/General/Installation](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/docs-general-installation--docs) in 4 Optionen: 

        CDN + Unversioniert 
        CDN + Versioniert 
        Package + Unversioniert 
        Package + Versioniert 

Jeweils mit Entscheidungshilfe (pro/contra). Darin dann pro Option die nötigen Todos. 

Einbinden von registerIconLibrary() direkt in die obigen Todos aufnehmen (statt bisher versteckt in sd-icon). Lieber Verweis von sd-icon auf obige Docs/General/Installation.

**Comment by yoezlem** [comment]
@mariohamann please optimize

**Comment by yoezlem** [comment]
@mariohamann please add SP

**Comment by mariohamann** [comment]
At the time when the ticket was written, it was needed to setup `registerIconLibrary`. Meanwhile this changed, as we now include a default library. Therefore I don't see this as part of "General Installation" but definitely something that belongs to icons.

I will nevertheless will rewrite the docs now, so they match up with our newest docs.
