### ISSUE TITLE
feat: ✨ replace FinanzAgenda logo with partner logo

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#760]
## User Story
As a brand manager of the Solid Design System, I would like to replace FinanzAgenda Logo in the header and show a partnerlogo, so that the given sample and guidance are more generic.

### Suggested Solution
replace FinanzAgenda logo with partner logo - display grey container with text "partnerlogo"

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [x] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [x] Relevant stories (Features, A11y) are created/updated
- [x] Implementation works successfully on `feature` branch

**Comment by coraliefeil** [comment]
@van-nguyen-ht pls pass on the ticket to DEV so they can update Storybook accordingly ... we cannot close this issue yet.

**Comment by van-nguyen-ht** [comment]
@azraefendic Hi Azra would you mind updating Storybook accordingly? Thank you
