### ISSUE TITLE
fix: 🤔 sd-tab-group scroll buttons lack disabled state indication

### ISSUE THREAD

**Issue by Vahid1919** [solid-design-system/solid#763]
## Current behavior
Currently when you are at the right-most/left-most end of the sd-tab-group (#280), although the scroll buttons don't make any visual change, they are not disabled. 
## Expected behavior
The left scroll button should be disabled when scrolling further to the left is not possible, and vice versa.

## Steps to reproduce
Open the "Scrollable" story for the sd-tab-group.

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by yoezlem** [comment]
Duplicate https://github.com/solid-design-system/solid/issues/955
So I will close this one.
