### ISSUE TITLE
feat: ✨ add quote pattern in Figma

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#765]
## User Story
As a consumer of the Solid Design System, I would like to see same patterns in code and design, so that I can have a coherent experience and can understand the DS better.

### Suggested Solution
Mirror [storybook quote pattern](https://64469bd84c5ea1ce2dd5d016-dplmjnzdec.chromatic.com/?path=/docs/pattern-quote--docs) in figma

## DoR
- [x] Item is clear and well-defined

## DoD
- [x] Implementation works successfully on `feature` branch

**Comment by van-nguyen-ht** [comment]
[Figma implementation](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=20699-8071&mode=design)
