### ISSUE TITLE
fix: add search icon in Header pattern (Figma)

### ISSUE THREAD

**Issue by EllaELSA** [solid-design-system/solid#770]
## User Story
As a designer of the Solid Design System, I would like to see the search icon in the header example (Pattern), so that I have a seamless view of what happens with the header elements in mobile.

### Suggested Solution
[See reworked navigation concept](https://www.figma.com/file/2hDs56yh73azMZafmpvEeU/Rework-Navigation?type=design&node-id=1139-36066&mode=design&t=al89iVtQDoedS9UY-11)

### Implementation

- [x] [sample/header/md](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=10878-1756&mode=design&t=y5sRMrBldMsjbplj-11)
- [x] [sample/header/sm](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=10878-1734&mode=design&t=y5sRMrBldMsjbplj-11)
- [x] Publish figma component
- [x] Update documentation
- [ ] Update storybook samples accordingly

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by coraliefeil** [comment]
@van-nguyen-ht when could you pick that one up? @EllaELSA says CMS teams need it asap ...
