### ISSUE TITLE
docs: 🤔 button group order/stacking

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#771]
## Current behavior
[Link to Storybook](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/story/components-sd-dialog--extended-footer)

button group does not stack vertically on mobile viewport
![Image](https://github.com/solid-design-system/solid/assets/41894356/6850050c-9d33-4c78-bc65-2f7db3d4c43a)

Also in button groups the primary button is shown on the left hand side.
![Image](https://github.com/solid-design-system/solid/assets/41894356/ff7305f6-8b6e-4595-9a3d-0cf563962ce9)

## Expected behavior

button group should per default stack vertically on mobile viewport and can be overriden if desired
https://www.figma.com/file/fPGhgNZv98U4H69Gu2tlWi/Button?type=design&node-id=971-4578&mode=design&t=jlonZFop4yXvVu9O-11

Also in button groups the primary button should always be shown on the ride hand side.
https://www.figma.com/file/ASD84ZPlImePMJ888oCyqK/Dialog?type=design&node-id=1635-1538&mode=design&t=i1BXWbflfibeWvYw-11

## Technical Information
This only pertains to the sample and not the component itself.

## DoR
- [x] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by Vahid1919** [comment]
@yoezlem I can change the order of buttons in storybook of course, but for the stacking, this feels like a component level fix. I have to set the footer component to `flex-col` on smaller screens. 

 If it is a default behavior should we not set the behavior for the footer component? That would mean this ticket will have to be a fix and not just docs. What do you think?
