### ISSUE TITLE
docs: 📚 create a list of deselected ui-components

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#800]
## Description
Currently our users don't know if a component has been deselected for migration into the SDS. This can potentially lead to a team waiting for a component, which will never come. 

A list of deselected ui-components should therefore be added into the introduction of our migration docs.

## Suggested Solution
```
### 🚫 Discontinued ui-components from [Component Library](https://component-library.fe.union-investment.de/latest/storybook/index.html) 🚫

Teams that have been using the following components should be aware that they will **not** be supported in the **Solid Design System (SDS) library**. If you have been relying on these components, it’s essential to implement their functionality in your own custom library.

>Note: Our practice involves detailed discussions about each UI component before migrating it into the SDS. As a result, this list will be regularly updated and adjusted.

- ui-contact
- ui-link-list
- ui-superteaser
- ui-tag-group

### Most likely discontinued ui-components 🚫 ⁇ 🚫

**Ui-components** from the following list appear unlikely to be included in the SDS Library, as they are highly specific to a **CMS context**.

> Note: This list is **highly non-binding** since we have not yet begun discussions about these components. If you are considering migrating any of them in the near future, please reach out to the SDS team for further evaluation.

- ui-portal
- ui-qr-code
- ui-social-follow-links
- ui-social-share-buttons
- ui-teaser-article
```
## Where to put the documentation
Storybook
## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by karlbaumhauer** [comment]
@yoezlem as soon as you have the list, pls add it here and move it into refinement.

**Comment by yoezlem** [comment]
**Deprecated and will not come with Solid DS**
ui-tile
ui-contact
ui-image -> changed to sd-media  | sd-copyright
ui-link-list
ui-superteaser -> cannot find any Ticket for that?
ui-tag-group -> cannot find any Ticket for that?

**Will Probably marked as deperacted**
ui-portal -> https://github.com/solid-design-system/solid/issues/303
ui-qr-code -> https://github.com/solid-design-system/solid/issues/551
ui-social-follow-links -> cannot find any Ticket for that?
ui-social-share-buttons -> cannot find any Ticket for that?
ui-teaser-article -> cannot find any Ticket for that?

@karlbaumhauer @coraliefeil @mariohamann Please check if I forgot something.

**Comment by karlbaumhauer** [comment]
> **Deprecated and will not come with Solid DS** ui-tile ui-contact ui-image -> changed to sd-media | sd-copyright ui-link-list ui-superteaser -> cannot find any Ticket for that? ui-tag-group -> cannot find any Ticket for that?
> 
> **Will Probably marked as deperacted** ui-portal -> #303 ui-qr-code -> #551 ui-social-follow-links -> cannot find any Ticket for that? ui-social-share-buttons -> cannot find any Ticket for that? ui-teaser-article -> cannot find any Ticket for that?
> 
> @karlbaumhauer @coraliefeil @mariohamann Please check if I forgot something.

thx @yoezlem 

so for this list, (IMO) we only need to add the following:
- ui-contact
- ui-link-list
- ui-superteaser => (we never even opened a ticket as it was too obvious)
- ui-tag-group => (we never even opened a ticket as it was too obvious)

The others are already covered in specific migration files:
- ui-tile => #309 
- ui-image => migration guide is missing => #808

For the upcoming, I like the ide to mention it but would phrase it very carefully.
