### ISSUE TITLE
feat: ✨ customizable sd-popup max-height

### ISSUE THREAD

**Issue by saemik94** [solid-design-system/solid#817]
## User Story
As a user of the Solid Design System, I would like to set a custom max-height for the `sd-popup`, so that when using the autocomplete feature the size of the result list can be choosen.

## Related Tickets
https://jira.apps.union-investment.de/browse/PB2B-3883

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by saemik94** [comment]
Blocked by #269

**Comment by mariohamann** [comment]
I just found out: You can easily set a `max-height` when the element inside the `sd-popup` has a `max-height`.

e.g.

```html
<sd-popup>
   <div style="max-height: 120px"></div>
</sd-popup>
```
