### ISSUE TITLE
chore: 🔧 move office hour due to extended iteration

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#840]
## Description
As we extended the 7th iteration to align with other teams, we need to move the office hour from the 2nd of April to the 9th of April. From that on, it will be in the 3-weeks frequency again.

## Technical Information
The meeting should be changed after the office hour in the 6th iteration. This keeps the link and invitations the same and people will get notified correctly.

**Comment by yoezlem** [comment]
Maybe we should decouple our office hour and iterations. 
Basically, during the office hour, we don't discuss what we worked on in the last iteration - instead, we talk about the features and fixes we've already implemented and answer questions. So, I would suggest we keep the office hour as it is.

**Comment by karlbaumhauer** [comment]
> Maybe we should decouple our office hour and iterations. Basically, during the office hour, we don't discuss what we worked on in the last iteration - instead, we talk about the features and fixes we've already implemented and answer questions. So, I would suggest we keep the office hour as it is.

fine for me. We can leave the schedule then and I will close this ticket.
