### ISSUE TITLE
fix: loading a single component loads all components

### ISSUE THREAD

**Issue by rolbr** [solid-design-system/solid#859]
## Current behavior
Loading a single component via CDN triggers loading of ALL components

## Expected behavior
Only the requested component is loaded

## Steps to reproduce
Save as .html and run in browser:
```
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <script src="https://solid-design-system.fe.union-investment.de/2.8.2/versioned-components/es/button.js" type="module"></script>
  </body>
</html>
```

## Technical Information
Loading button.js works as expected.
However, it imports and loads ./solid-components2.js which in turn imports and loads all other components.

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
Apparently this is a bug since... `v1.0.1`:

- 1.0.0: https://codepen.io/mariohamann/pen/BaEZzPq
- 1.0.1: https://codepen.io/mariohamann/pen/wvZeWxQ

Which is quite... embarassing.

It came from this change: https://github.com/solid-design-system/solid/pull/213

**Comment by mariohamann** [comment]
The problem comes from the chunking strategy of rollup. With the following settings it works fine, as we explicitly generate the chunks for the utilities:

```js
/**
     * Build step for browsers (includes lit etc.)
     * - umd: Combined js file, faster to load, but not tree-shakeable, recommended
     * - es: Chunked js files, usable in browser, makes it possible to pick single components
     */
    build: {
      outDir: 'dist',
      rollupOptions: {
        input: path.resolve(__dirname, 'src/solid-components.ts'),
        output: {
          manualChunks(id) {
            if (id.includes('utilities')) {
              const paths = id.split('/');
              const name = paths[paths.length - 1].replace('.ts', '');
              return `${name}`;
            }
            return null;
          },
          entryFileNames: 'es/solid-components.js',
          // Modern JS bundles (no JS compilation, ES module output)
          format: 'esm',
          chunkFileNames: 'es/[name].js',
          dir: 'dist/components'
        },
        plugins: [
          // Resolve bare module specifiers to relative paths
          resolve(),
          // Minify HTML template literals
          // eslint-disable-next-line @typescript-eslint/no-unsafe-call
          customMinifyHTMLLiteralsPlugin(),
          // Minify ES and UMD bundles
          customMinifyPlugin({
            ecma: 2020,
            module: true,
            compress: { defaults: true, passes: 2 },
            mangle: true
          }),
          // Print bundle summary
          summaryPlugin({ showGzippedSize: true }),
          // Generate web types
          webTypesPlugin()
        ]
      }
```

The problem is, that the `lib` had to be deactivated here and there's no UMD bundle now. Maybe we therefore need an additional build step in the end or similar.
