### ISSUE TITLE
fix: 🤔 replace video with placeholder video

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#867]
## Current behavior

1. The [provided video](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/story/components-sd-video--video-element) is not the one from the placeholder package.

2. I cannot turn on subtitles -> How does it work? How do subtitles look like? 

## Expected behavior
Show this video from the placeholder package: (#378 )
https://github.com/solid-design-system/solid/issues/867#issuecomment-2058947661

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [x] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [x] Relevant stories (Features, A11y) are created/updated
- [x] Implementation works successfully on `feature` branch

**Comment by yoezlem** [comment]
@EllaELSA could you put a video with audio track in it?

**Comment by EllaELSA** [comment]
@coraliefeil I had a chat with Brand regarding this. She suggested the Corporate Design explanatory film from the toolbox. Does this work for you? let me know then I can try to get it 
[CD-Toolbox (union-investment.de)](https://cd.union-investment.de/)

**Comment by EllaELSA** [comment]
I have the mp4 now 

https://github.com/solid-design-system/solid/assets/124053512/8265bd18-fd4e-4edc-bd54-1c3504f38080

**Comment by yoezlem** [comment]
@EllaELSA Could you send the audio again? Somethings not right with it.

**Comment by yoezlem** [comment]
@EllaELSA nvm its working now. Maybe I had slow Internet connection yesterday.

**Comment by yoezlem** [comment]
@coraliefeil I added the video in our placeholder package. For subtitles we need the `<track>` attribute and a .vtt file: https://developer.mozilla.org/en-US/docs/Web/Media/Audio_and_video_delivery/Adding_captions_and_subtitles_to_HTML5_video#html_markup

We can add this to a new task and I would close this one after https://github.com/solid-design-system/solid/pull/1032 is reviewed

**Comment by yoezlem** [comment]
Looks like a duplicate to -> [#378](https://github.com/solid-design-system/solid/issues/378)

**Comment by yoezlem** [comment]
For subtitles and subtitles menu we need styles I believe. 

So thats for me another feature - I would create another feature story for that.

**Comment by yoezlem** [comment]
https://github.com/solid-design-system/solid/issues/1037

**Comment by yoezlem** [comment]
Part one is done => #1032.
For part two we have now Task: #1037.
