### ISSUE TITLE
fix: 🤔 sd-dialog -> close icon missing after global-resources change

### ISSUE THREAD

**Issue by awacode21** [solid-design-system/solid#895]
## Current behavior
the close icon of the close button within sd-dialog is not rendered:
<img width="684" alt="Bildschirmfoto 2024-03-22 um 15 00 08" src="https://github.com/solid-design-system/solid/assets/30939926/8d32261e-33d9-40e7-b953-bb959f7430f6">

It looks like the library that is referenced is wrong:
<img width="641" alt="Bildschirmfoto 2024-03-22 um 15 01 42" src="https://github.com/solid-design-system/solid/assets/30939926/b63b0e20-0513-4a63-b03b-324d75ac3db3">
here it is referencing to global-resources, but as far as i understood it should reference library="default" instead. Then the icon would be shown.

## Expected behavior
the close icon should be rendered so user can see the close option:
<img width="679" alt="Bildschirmfoto 2024-03-22 um 15 00 47" src="https://github.com/solid-design-system/solid/assets/30939926/e15ac17f-679f-42ff-bbff-5af7b43c344c">

## Steps to reproduce
Reproduction: [https://codepen.io/awacode/pen/MWxZNQE](https://codepen.io/awacode/pen/MWxZNQE)

## Technical Information
All devices, All browsers

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
Just to make that clear: it should point to library=system — this is the library we use internal in our components.

**Comment by awacode21** [comment]
any plans when this will get fixed?
