### ISSUE TITLE
fix: 🤔 Renovate can't merge PR's anymore (with and without conflicts)

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#899]
## Current behavior
For all new update Tickets we have, renovate are not able to merge it. Even if quality gate is successfully running. Somehow we have always merge conflicts inside the update PR.

## Expected behavior
If quality gate is successfully done, renovate should merge the update npm packages without having trouble with and without merge conflicts.

**without conflicts:**
https://github.com/solid-design-system/solid/pull/894
<img width="1159" alt="image" src="https://github.com/solid-design-system/solid/assets/98025014/5e0c1155-0ed3-4757-8023-a4e6163789d8">

**with conflicts:**
https://github.com/solid-design-system/solid/pull/893
<img width="1104" alt="image" src="https://github.com/solid-design-system/solid/assets/98025014/829b13cb-b2a0-4569-93d3-1b4e19d50ab9">

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by karlbaumhauer** [comment]
@solid-design-system/development from my perspective this is not an issue with renovate. 

![MicrosoftTeams-image](https://github.com/solid-design-system/solid/assets/48211526/bd004594-0099-4588-89dd-d2786ce64a54)

As seen in the screenshot, this sample PR was ready to merge but the quality gate was never triggered. I assume this is something which needs to be re-configured in GitHub settings. Probably in the branch protection rules.

In general my expectation would be: 
no user and no bit should be able to merge anything without quality gate has been triggered and passed.
