### ISSUE TITLE
fix: 🤔 tabs do not grow with longer tab titles

### ISSUE THREAD

**Issue by koepferd** [solid-design-system/solid#901]
## Current behavior
When an sd-tab has a longer title than ~10 characters the text will overflow the tab size.
![Bildschirmfoto 2024-04-02 um 08 15 15](https://github.com/solid-design-system/solid/assets/8968377/2452beaf-8e7c-493c-96bb-005bd031607f)
For the part "base" there is a width of w-20 fixed. I suppose this should rather be min-width.

## Expected behavior
The tab width grows with longer tab titles.

## Steps to reproduce
Use a longer tab title in storybook.

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by yoezlem** [comment]
https://github.com/solid-design-system/solid/pull/904
