### ISSUE TITLE
feat: ✨ add testing-attribute to all components

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#931]
## User Story
As a tester, I would like to have a testing attribute on all components, so that I can use a `querySelector` and filter by this specific attribute to find all SDS-components inside the HTML of a website. As the component tag-name does not allow wildcards, I cannot use the tag-name to also address/filter versioned components (as the tag-name containes the version e.g. sd-button-2-1-0).
### Suggested Solution
We automatically add a specific testing attribute to all components, on which the testers can rely to filter the DOM and adress all Solid components.

As suggested from the testers in the [JIRA ticket](https://jira.apps.union-investment.de/browse/PSOLIDDS-28), the attribute should be like:
name: `data-testing-id`
value: `[component-tag-namem]` (without any version infomation)

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
I would use something different, as often in tests `data-testid` is used to explicitly set test IDs – and they should be unique.

https://testing-library.com/docs/queries/bytestid/

I would go more with something like `data-sd-component` or similar. We could BTW do the some with `data-sd-version` as well, as tracking asked several times for a version.

**Comment by karlbaumhauer** [comment]
> I would use something different, as often in tests `data-testid` is used to explicitly set test IDs – and they should be unique.
> 
> https://testing-library.com/docs/queries/bytestid/
> 
> I would go more with something like `data-sd-component` or similar. We could BTW do the some with `data-sd-version` as well, as tracking asked several times for a version.

good idea. I will try to clarify this.

**Comment by karlbaumhauer** [comment]
closed as duplicate to #1059
