### ISSUE TITLE
fix: sd-navigation-item - href attribute default value

### ISSUE THREAD

**Issue by mmisojcic** [solid-design-system/solid#935]
## Description

**sd-navigation-item** will have **href** html attribute attached even if value is not provided.
This will render button tag inside the slot, as it should, but will cause page reload when clicked.

This is reproducible on level 1 navigation on [realestate](https://realestate.union-investment.com/) page.

**Comment by mariohamann** [comment]
Closed with https://github.com/solid-design-system/solid/commit/554e9f7ab9a43f6566017c68e7063cf6b5220bb7
