### ISSUE TITLE
fix: 🤔 sd-icon - number "190307_" shown on hover

### ISSUE THREAD

**Issue by clemens-vi** [solid-design-system/solid#936]
## Current behavior
If the **sd-icon** component is used with the **"system/close-circle"** icon, a tooltip with the number **"190307_"** is displayed on hover.

## Expected behavior
No tooltip is shown

## Steps to reproduce
create a **sd-icon** instance with **name="system/close-circle"** set, render in browser and hover over the icon.

## Technical Information
The behavious is caused by an obsolete "<title>" tag in the svg markup of the icon.

-> Could you please go through the existing SVG icons and clean them up - and clarify with the UX designers where this title tag comes from and optimize the export / import process so that all svg icons are automatically cleaned and this no longer happens?

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by rolbr** [comment]
https://fe-celum-icons-prod.azureedge.net/union-investment/system/close-circle.svg
<img width="400" alt="grafik" src="https://github.com/solid-design-system/solid/assets/5709376/3cb7c7b4-bdcd-4bc2-af16-39f2c02b6ff4">

**Comment by karlbaumhauer** [comment]
as the title comes from the SVG file itself, which is provided by the DAM CDN, its not in our technical responsibility to change it. Therefore I close this ticket and ask @clemens-vi to report this to the DAM team.
