### ISSUE TITLE
docs: 📚 fix countup.js in templates

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#941]
## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by karlbaumhauer** [comment]
duplicate to #943 
FYi @Vahid1919
