### ISSUE TITLE
fix: 🤔 supernumber animation not working in hosted storybook docs

### ISSUE THREAD

**Issue by christophsaile** [solid-design-system/solid#943]
## Current behavior
The supernumber animation is not working in the hosted storybook docs. Locally the animation is working.

## Expected behavior
Animation is working on hosted Storybook

## Steps to reproduce
https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/story/pattern-supernumber--animation

## Technical Information
![grafik](https://github.com/solid-design-system/solid/assets/54807480/a70bef70-9aea-4d92-90ca-941f2bee3ebc)

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
Thanks for the hint, we just published a fix. @christophsaile
