### ISSUE TITLE
docs: 📚  sd-header - UI Logo full

### ISSUE THREAD

**Issue by van-nguyen-ht** [solid-design-system/solid#959]
## Current behavior
Logo miss missing. "Union Investment" words
[Reference](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/story/components-sd-header--small-viewport-sample-2&args=fixed-attr:!true&globals=viewport:mobile1)
![Image](https://github.com/solid-design-system/solid/assets/118520877/beed208c-d4d2-4f09-a476-57312cba4b64)

## Expected behavior 
Full logo must be used to be consistent
[Reference](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/story/components-sd-header--sample-a-sm&args=fixed-attr:!true&globals=viewport:mobile1)
![Image](https://github.com/solid-design-system/solid/assets/118520877/9c4da831-383f-4f42-bb88-c5a4f2d557fe)

## Steps to reproduce
[Figma](https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=11799-67441&mode=design&t=eQrg3kiZ0cqMwK8U-11)

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by yoezlem** [comment]
Seems to be solved.
