### ISSUE TITLE
docs: 📚 supernumber pattern - add information/guidance

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#961]
## Description

[Request from 16.04.2024
](https://teams.microsoft.com/l/message/19:sycqZKo6K_-P5eYh0H4Xn2UpoKmti8Ar5SICMb9z7C41@thread.tacv2/1713276435713?tenantId=2eb07b91-f9f8-437b-a89e-59f55e565c11&groupId=cec93f98-ceee-42bd-bfde-a6b51fc1194e&parentMessageId=1713276435713&teamName=Solid%20Design%20System%20Community%20(Team)&channelName=General&createdTime=1713276435713)

Missing the following information:

The supernumber is only displayed in one variant (all text elements enabled). In the old component the text above and below the number were optional so it would be nice to have this reflected in the design as well (for example in case of different spacings).

In the design the supernumber has 3 sizes (lg, md, sm) can you give guidance when to use which size for example:

Use sm when the component is smaller than 300px
Use md when the component is smaller than 400px
….

Since the component is called supernumber are you still allowed to place normal text inside the highlighted area or for example only a number + unit?

--

https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/pattern-supernumber--docs

```
Default
Used to highlight and convey important key figures. The component consists of overline, number, subline and description. Supernumber is used as a subcomponent inside sd-container.
```

- [ ] Refactor Storybook descriptions: 
  - [x] This is a pattern - replace all "component" phrases with "pattern"
  - [x] Specify which parts are optional (overline, subline, description) and that prefix / suffix are static. Specify - use prefix/suffix option of countup.js ... sizes are examples ...
  - [x] make clear, that we just provide samples how to use the countUp plugin (eg: "Use the `prefix` option to add a prefix to the supernumber." => "If you need a prefix, you can use the `prefix` option from countUp.")
- [x] To do Figma: Specify which parts are optional (overline, subline, description)
- [x] To do Figma: Explain sizes
- [x] To do Figma: Add prefix / suffix info about animation
- [x] Storybook bug - small mobile overline/subline need to be centered

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by christophsaile** [comment]
Hey @coraliefeil, @karlbaumhauer after your refinement tmrw can you give me rough timeline when you can provide the informations for us?
Since we need these informations indirect for the annual report which has a deadline we are bit in hurry.
Our latest possible release would be the 13.05. but better would be the 29.04 so we have more time for testing.

**Comment by karlbaumhauer** [comment]
@christophsaile as discussed, we will put this on our topic list for tomorrow and come back to you asap.

**Comment by yoezlem** [comment]
After finishing the Dev part please add CMS in it.

**Comment by coraliefeil** [comment]
I removed figma label since all design task are done.

**Comment by coraliefeil** [comment]
So since the comp is called supernumber for use cases where emphasizing a number is intended ... I would say preferrably a number ... but of course people can write sth in there as well ... if that makes sense content/-conceptwise.
With that said ... I would not restrict supernumber to numbers only.

**Comment by coraliefeil** [comment]
"Supernumbers are preferably entered in the form of numbers, but can also be entered in the form of text in order to fulfill certain use cases."
